import { BlockType } from '../types/landingPage';
import { SiteTemplate } from '../types/site';

const makeTheme = (o: Record<string, any>) => ({
  primaryColor: '#2563eb',
  secondaryColor: '#059669',
  backgroundColor: '#ffffff',
  textColor: '#1e293b',
  fontFamily: 'Inter, sans-serif',
  headingFontFamily: 'Inter, sans-serif',
  fontSize: { base: '1rem', heading1: '3rem', heading2: '2rem', heading3: '1.5rem' },
  borderRadius: '0.75rem',
  spacing: { xs: '0.5rem', sm: '1rem', md: '1.5rem', lg: '2rem', xl: '4rem' },
  ...o,
});

const IMG = {
  luxury: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop',
  luxury2: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&h=800&fit=crop',
  rural: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=800&fit=crop',
  rural2: 'https://images.unsplash.com/photo-1500076656116-558758c991c1?w=1200&h=800&fit=crop',
  urban: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop',
  urban2: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1200&h=800&fit=crop',
  bold: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop',
  bold2: 'https://images.unsplash.com/photo-1600607687644-c7f34b5e9d3e?w=1200&h=800&fit=crop',
  cinema: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=1200&h=800&fit=crop',
  cinema2: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1200&h=800&fit=crop',
  classic: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=800&fit=crop',
  classic2: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?w=1200&h=800&fit=crop',
  tech: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&h=800&fit=crop',
  tech2: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200&h=800&fit=crop',
  beach: 'https://images.unsplash.com/photo-1499793983394-2d6e66b9b832?w=1200&h=800&fit=crop',
  beach2: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=800&fit=crop',
  commercial: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop',
  commercial2: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop',
  eco: 'https://images.unsplash.com/photo-1518005068251-37900150dfca?w=1200&h=800&fit=crop',
  eco2: 'https://images.unsplash.com/photo-1609081219671-c6bf8c3a2e45?w=1200&h=800&fit=crop',
};

export const SITE_TEMPLATES: SiteTemplate[] = [
  {
    id: 'premium-luxo',
    name: 'Luxo Imobiliário Premium',
    description: 'Template luxuoso com paleta dourada/escura para imobiliárias de alto padrão',
    thumbnail: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=300&fit=crop',
    category: 'universal',
    globalTheme: makeTheme({
      primaryColor: '#C9A84C',
      secondaryColor: '#1A1A1A',
      backgroundColor: '#0D0D0D',
      textColor: '#F5F5F5',
      fontFamily: 'Playfair Display, serif',
      headingFontFamily: 'Playfair Display, serif',
    }),
    menuConfig: [
      { id: 'lux-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'lux-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'lux-m3', label: 'Sobre', type: 'page', pageId: 'sobre', order: 2 },
      { id: 'lux-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'lux-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Viver o Extraordinário', subtitle: 'Residências que definem o luxo', backgroundImage: IMG.luxury, overlayOpacity: 0.5, ctaText: 'Explorar Coleção', ctaLink: '#imoveis', height: 650, alignment: 'center', textColor: '#F5F5F5' }, styles: { padding: '0px' } },
          { id: 'lux-stats', type: BlockType.STATS, order: 1, visible: true, config: { stats: [{ value: '500+', label: 'Imóveis Vendidos', icon: '🏡' }, { value: '15+', label: 'Anos de Mercado', icon: '⭐' }, { value: '98%', label: 'Clientes Satisfeitos', icon: '👥' }, { value: '+R$2B', label: 'Em Negócios', icon: '💰' }], columns: 4, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#1A1A1A' } },
          { id: 'lux-text', type: BlockType.TEXT, order: 2, visible: true, config: { content: '<h2 style="text-align:center;color:#C9A84C">Coleção Exclusiva</h2><p style="text-align:center;color:#F5F5F5">Cada imóvel em nossa coleção é selecionado com critérios rigorosos de excelência, localização e sofisticação.</p>', fontSize: 16, fontWeight: 400, color: '#F5F5F5', alignment: 'center' }, styles: { padding: '60px 20px' } },
          { id: 'lux-grid', type: BlockType.PROPERTY_GRID, order: 3, visible: true, config: { columns: 3, gap: 24, showFilters: false, maxItems: 6, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '0px 20px 60px' } },
          { id: 'lux-cta', type: BlockType.CTA, order: 4, visible: true, config: { title: 'Agende uma Visita Privativa', description: 'Nossa equipe está pronta para apresentar as melhores opções', buttonText: 'Falar com Consultor', buttonLink: '#contato', backgroundColor: '#C9A84C', textColor: '#0D0D0D' }, styles: { padding: '80px 20px' } },
          { id: 'lux-testimonials', type: BlockType.TESTIMONIALS, order: 5, visible: true, config: { testimonials: [{ name: 'Ana Carolina Mendes', rating: 5, text: 'Excelente experiência. Encontrei a cobertura perfeita com toda privacidade e sofisticação que procurava.' }, { name: 'Roberto Almeida', rating: 5, text: 'Profissionalismo e discrição em cada etapa. Recomendo para quem busca o melhor.' }, { name: 'Fernanda Costa', rating: 5, text: 'Atendimento impecável do início ao fim. Superou todas as expectativas.' }], layout: 'carousel', showRating: true }, styles: { padding: '60px 20px', backgroundColor: '#1A1A1A' } },
          { id: 'lux-map', type: BlockType.MAP, order: 6, visible: true, config: { latitude: -23.5614, longitude: -46.6558, zoom: 14 }, styles: { padding: '0px', height: '400px' } },
          { id: 'lux-broker', type: BlockType.BROKER_CARD, order: 7, visible: true, config: { name: 'Mariana Vieira', photoUrl: '', creci: '12345-J', specialty: 'Alto Padrão & Coberturas', phone: '(11) 99999-0000', email: 'mariana@imobzy.com', description: 'Especialista em imóveis de alto padrão com mais de 10 anos de experiência.' }, styles: { padding: '60px 20px' } },
          { id: 'lux-footer', type: BlockType.FOOTER, order: 8, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0D0D0D' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'lux-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Nossa Coleção', subtitle: 'Propriedades selecionadas com excelência', backgroundImage: IMG.luxury2, overlayOpacity: 0.5, height: 400, alignment: 'center', textColor: '#F5F5F5' }, styles: { padding: '0px' } },
          { id: 'lux-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 30, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'lux-imp-carousel', type: BlockType.PROPERTY_CAROUSEL, order: 2, visible: true, config: { autoplay: true, interval: 4000, showArrows: true, showDots: true, itemsPerView: 3 }, styles: { padding: '0px 20px 60px' } },
          { id: 'lux-imp-cta', type: BlockType.CTA, order: 3, visible: true, config: { title: 'Não encontrou o que procura?', description: 'Fale conosco e encontraremos o imóvel ideal para você', buttonText: 'Fale Conosco', buttonLink: '#contato', backgroundColor: '#C9A84C', textColor: '#0D0D0D' }, styles: { padding: '60px 20px' } },
          { id: 'lux-imp-footer', type: BlockType.FOOTER, order: 4, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0D0D0D' } },
        ],
      },
      {
        title: 'Sobre',
        slug: 'sobre',
        isHome: false,
        blocks: [
          { id: 'lux-sob-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Tradição em Excelência', subtitle: 'Mais de 15 anos conectando pessoas ao lar dos sonhos', backgroundImage: IMG.luxury, overlayOpacity: 0.6, height: 400, alignment: 'center', textColor: '#F5F5F5' }, styles: { padding: '0px' } },
          { id: 'lux-sob-text', type: BlockType.TEXT, order: 1, visible: true, config: { content: '<h2 style="color:#C9A84C">Nossa História</h2><p>Fundada em 2009, nossa imobiliária se tornou referência no segmento de alto padrão. Acreditamos que cada cliente merece um atendimento personalizado e sigiloso.</p><p>Com uma equipe de especialistas certificados, utilizamos tecnologia e experiência para transformar sonhos em realidade.</p>', fontSize: 16, fontWeight: 400, color: '#F5F5F5', alignment: 'left' }, styles: { padding: '60px 20px' } },
          { id: 'lux-sob-timeline', type: BlockType.TIMELINE, order: 2, visible: true, config: { title: 'Nossa Trajetória', items: [{ title: 'Fundação', description: 'Início das operações em São Paulo', time: '2009' }, { title: 'Expansão', description: 'Abertura de filiais no Rio e BH', time: '2014' }, { title: 'Prêmio', description: 'Melhor imobiliária de alto padrão', time: '2019' }, { title: 'Consolidação', description: '+500 imóveis vendidos', time: '2024' }] }, styles: { padding: '60px 20px', backgroundColor: '#1A1A1A' } },
          { id: 'lux-sob-stats', type: BlockType.STATS, order: 3, visible: true, config: { stats: [{ value: '500+', label: 'Imóveis Vendidos', icon: '🏡' }, { value: '15+', label: 'Anos', icon: '⭐' }, { value: '98%', label: 'Satisfação', icon: '👥' }], columns: 3, animated: true }, styles: { padding: '60px 20px' } },
          { id: 'lux-sob-testimonials', type: BlockType.TESTIMONIALS, order: 4, visible: true, config: { testimonials: [{ name: 'Ana Carolina', rating: 5, text: 'Experiência impecável do início ao fim.' }, { name: 'Roberto Almeida', rating: 5, text: 'Profissionalismo e discrição exemplares.' }], layout: 'grid', showRating: true }, styles: { padding: '60px 20px', backgroundColor: '#1A1A1A' } },
          { id: 'lux-sob-footer', type: BlockType.FOOTER, order: 5, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0D0D0D' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'lux-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Agende sua Consulta Privativa', subtitle: 'Atendimento exclusivo e personalizado', backgroundImage: IMG.luxury2, overlayOpacity: 0.5, formTitle: 'Solicite uma Visita', formSubtitle: 'Preencha e entraremos em contato', submitText: 'Solicitar', height: 600, textColor: '#F5F5F5', showBadges: true, badges: [{ icon: 'shield', title: 'Sigilo Total', description: 'Sua privacidade é nossa prioridade' }, { icon: 'star', title: 'Atendimento VIP', description: 'Consultor dedicado' }, { icon: 'clock', title: 'Resposta Rápida', description: 'Em até 2 horas' }] }, styles: { padding: '0px' } },
          { id: 'lux-con-map', type: BlockType.MAP, order: 1, visible: true, config: { latitude: -23.5614, longitude: -46.6558, zoom: 14 }, styles: { padding: '0px', height: '400px' } },
          { id: 'lux-con-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0D0D0D' } },
        ],
      },
    ],
  },
  {
    id: 'natureza-viva',
    name: 'Natureza Viva',
    description: 'Template orgânico para imobiliárias rurais com fazendas e sítios',
    thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
    category: 'rural',
    globalTheme: makeTheme({
      primaryColor: '#2D5016',
      secondaryColor: '#8B6914',
      backgroundColor: '#FDF8F0',
      textColor: '#2C2C2C',
      fontFamily: 'Lora, serif',
      headingFontFamily: 'Playfair Display, serif',
    }),
    menuConfig: [
      { id: 'nv-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'nv-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'nv-m3', label: 'Sobre', type: 'page', pageId: 'sobre', order: 2 },
      { id: 'nv-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'nv-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Onde a Natureza é o Luxo', subtitle: 'Imóveis rurais para quem busca paz e prosperidade', backgroundImage: IMG.rural, overlayOpacity: 0.4, ctaText: 'Ver Propriedades', ctaLink: '#imoveis', height: 600, alignment: 'center', textColor: '#FDF8F0' }, styles: { padding: '0px' } },
          { id: 'nv-features', type: BlockType.FEATURES, order: 1, visible: true, config: { features: [{ title: 'Áreas de Pasto', description: 'Larga pastagem para pecuária de qualidade', icon: '🌾' }, { title: 'Água Natural', description: 'Rios e nascentes em toda a propriedade', icon: '💧' }, { title: 'Infraestrutura Rural', description: 'Currais, galpões e estradas internas', icon: '🏗️' }], columns: 3 }, styles: { padding: '60px 20px', backgroundColor: '#FDF8F0' } },
          { id: 'nv-stats', type: BlockType.STATS, order: 2, visible: true, config: { stats: [{ value: '200+', label: 'Fazendas Vendidas', icon: '🏡' }, { value: '50k+', label: 'Hectares', icon: '🌳' }, { value: '12', label: 'Anos', icon: '⭐' }, { value: '20', label: 'Estados', icon: '🗺️' }], columns: 4, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#2D5016' } },
          { id: 'nv-grid', type: BlockType.PROPERTY_GRID, order: 3, visible: true, config: { columns: 2, gap: 24, showFilters: true, maxItems: 6, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'nv-cta', type: BlockType.CTA, order: 4, visible: true, config: { title: 'Encontre sua Terra', description: 'Oportunidades únicas no mercado rural brasileiro', buttonText: 'Ver Oportunidades', buttonLink: '#imoveis', backgroundColor: '#2D5016', textColor: '#FDF8F0' }, styles: { padding: '80px 20px' } },
          { id: 'nv-testimonials', type: BlockType.TESTIMONIALS, order: 5, visible: true, config: { testimonials: [{ name: 'João Pedro Santos', rating: 5, text: 'Encontrei a fazenda perfeita. Documentação 100% e atendimento excepcional.' }, { name: 'Maria Clara Oliveira', rating: 5, text: 'Investimento seguro e retorno garantido. Equipe muito competente.' }], layout: 'grid', showRating: true }, styles: { padding: '60px 20px', backgroundColor: '#FDF8F0' } },
          { id: 'nv-broker', type: BlockType.BROKER_CARD, order: 6, visible: true, config: { name: 'Carlos Eduardo Lima', photoUrl: '', creci: '54321-J', specialty: 'Imóveis Rurais', phone: '(62) 99999-0000', email: 'carlos@imobzy.com', description: 'Especialista em fazendas e áreas rurais no cerrado.' }, styles: { padding: '60px 20px' } },
          { id: 'nv-footer', type: BlockType.FOOTER, order: 7, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#2D5016' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'nv-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Nossas Propriedades', subtitle: 'Fazendas, sítios e chácaras selecionados', backgroundImage: IMG.rural2, overlayOpacity: 0.4, height: 400, alignment: 'center', textColor: '#FDF8F0' }, styles: { padding: '0px' } },
          { id: 'nv-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 2, gap: 24, showFilters: true, maxItems: 30, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'nv-imp-map', type: BlockType.MAP, order: 2, visible: true, config: { latitude: -15.7801, longitude: -47.9292, zoom: 6 }, styles: { padding: '0px', height: '400px' } },
          { id: 'nv-imp-footer', type: BlockType.FOOTER, order: 3, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#2D5016' } },
        ],
      },
      {
        title: 'Sobre',
        slug: 'sobre',
        isHome: false,
        blocks: [
          { id: 'nv-sob-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Conectando Pessoas à Terra', subtitle: 'Especialistas no mercado rural há mais de uma década', backgroundImage: IMG.rural, overlayOpacity: 0.5, height: 400, alignment: 'center', textColor: '#FDF8F0' }, styles: { padding: '0px' } },
          { id: 'nv-sob-text', type: BlockType.TEXT, order: 1, visible: true, config: { content: '<h2 style="color:#2D5016">Nossa História</h2><p>Nascemos do amor pela terra e pelo campo. Há mais de 12 anos, ajudamos famílias e investidores a encontrarem as melhores propriedades rurais do Brasil.</p><p>Nossa equipe conta com engenheiros agrônomos, advogados ambientais e corretores especializados.</p>', fontSize: 16, fontWeight: 400, color: '#2C2C2C', alignment: 'left' }, styles: { padding: '60px 20px' } },
          { id: 'nv-sob-timeline', type: BlockType.TIMELINE, order: 2, visible: true, config: { title: 'Marcos', items: [{ title: 'Início', description: 'Primeiras operações em Goiás', time: '2012' }, { title: 'Expansão', description: 'Presença em 5 estados', time: '2016' }, { title: 'Líder', description: 'Referência em imóveis rurais', time: '2020' }] }, styles: { padding: '60px 20px', backgroundColor: '#FDF8F0' } },
          { id: 'nv-sob-footer', type: BlockType.FOOTER, order: 3, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#2D5016' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'nv-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Fale com um Especialista Rural', subtitle: 'Atendimento personalizado para cada propriedade', backgroundImage: IMG.rural2, overlayOpacity: 0.4, formTitle: 'Entre em Contato', formSubtitle: 'Preencha e retornaremos em breve', submitText: 'Enviar', height: 550, textColor: '#FDF8F0', showBadges: true, badges: [{ icon: 'shield', title: 'Documentação', description: 'Imóveis regularizados' }, { icon: 'star', title: 'Seleção', description: 'Propriedades verificadas' }, { icon: 'clock', title: 'Agilidade', description: 'Resposta em 24h' }] }, styles: { padding: '0px' } },
          { id: 'nv-con-footer', type: BlockType.FOOTER, order: 1, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#2D5016' } },
        ],
      },
    ],
  },
  {
    id: 'urbano-clean',
    name: 'Urbano Clean',
    description: 'Design minimalista para imobiliárias urbanas com apartamentos e lofts',
    thumbnail: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&h=300&fit=crop',
    category: 'urban',
    globalTheme: makeTheme({
      primaryColor: '#2563EB',
      secondaryColor: '#64748B',
      backgroundColor: '#FFFFFF',
      textColor: '#1E293B',
      fontFamily: 'Inter, sans-serif',
      headingFontFamily: 'Inter, sans-serif',
    }),
    menuConfig: [
      { id: 'uc-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'uc-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'uc-m3', label: 'Sobre', type: 'page', pageId: 'sobre', order: 2 },
      { id: 'uc-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'uc-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Seu Novo Lar Urbano', subtitle: 'Apartamentos e lofts nas melhores regiões', backgroundImage: IMG.urban, overlayOpacity: 0.5, formTitle: 'Busca Rápida', formSubtitle: 'Encontre o imóvel ideal', submitText: 'Buscar', height: 600, textColor: '#ffffff', showBadges: false }, styles: { padding: '0px' } },
          { id: 'uc-stats', type: BlockType.STATS, order: 1, visible: true, config: { stats: [{ value: '800+', label: 'Imóveis', icon: '🏢' }, { value: '12', label: 'Bairros', icon: '📍' }, { value: '4.9★', label: 'Avaliação', icon: '⭐' }, { value: '24h', label: 'Atendimento', icon: '⏰' }], columns: 4, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#F8FAFC' } },
          { id: 'uc-grid', type: BlockType.PROPERTY_GRID, order: 2, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 6, sortBy: 'date', cardStyle: 'modern' }, styles: { padding: '0px 20px 60px' } },
          { id: 'uc-features', type: BlockType.FEATURES, order: 3, visible: true, config: { features: [{ title: 'Busca Inteligente', description: 'Encontre por bairro, preço e tipo', icon: '🔍' }, { title: 'Fotos 360°', description: 'Veja cada cômodo em detalhes', icon: '📷' }, { title: 'Visita Virtual', description: 'Conheça sem sair de casa', icon: '🏠' }, { title: 'Financiamento', description: 'Simule seu financiamento', icon: '💰' }], columns: 4 }, styles: { padding: '60px 20px', backgroundColor: '#F8FAFC' } },
          { id: 'uc-cta', type: BlockType.CTA, order: 4, visible: true, config: { title: 'Cadastre seu Imóvel', description: 'Divulgue para milhares de compradores', buttonText: 'Cadastrar', buttonLink: '#contato', backgroundColor: '#2563EB', textColor: '#ffffff' }, styles: { padding: '80px 20px' } },
          { id: 'uc-testimonials', type: BlockType.TESTIMONIALS, order: 5, visible: true, config: { testimonials: [{ name: 'Lucas Ferreira', rating: 5, text: 'Encontrei meu apartamento em 2 dias. Processo super simples!' }, { name: 'Camila Santos', rating: 5, text: 'Plataforma muito fácil de usar. Recomendo!' }, { name: 'Rafael Costa', rating: 5, text: 'Atendimento rápido e eficiente.' }], layout: 'carousel', showRating: true }, styles: { padding: '60px 20px' } },
          { id: 'uc-footer', type: BlockType.FOOTER, order: 6, visible: true, config: {}, styles: { padding: '40px 20px' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'uc-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Encontre seu Imóvel', subtitle: 'Filtros avançados para sua busca', backgroundImage: IMG.urban2, overlayOpacity: 0.4, height: 350, alignment: 'center', textColor: '#ffffff' }, styles: { padding: '0px' } },
          { id: 'uc-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 30, sortBy: 'date', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'uc-imp-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px' } },
        ],
      },
      {
        title: 'Sobre',
        slug: 'sobre',
        isHome: false,
        blocks: [
          { id: 'uc-sob-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Sobre Nós', subtitle: 'Conectando pessoas aos melhores imóveis urbanos', backgroundImage: IMG.urban, overlayOpacity: 0.4, height: 350, alignment: 'center', textColor: '#ffffff' }, styles: { padding: '0px' } },
          { id: 'uc-sob-text', type: BlockType.TEXT, order: 1, visible: true, config: { content: '<h2>Nossa Missão</h2><p>Simplificar a compra e aluguel de imóveis urbanos com tecnologia e atendimento humanizado. Acreditamos que encontrar o lar ideal não precisa ser complicado.</p>', fontSize: 16, fontWeight: 400, color: '#1E293B', alignment: 'left' }, styles: { padding: '60px 20px' } },
          { id: 'uc-sob-features', type: BlockType.FEATURES, order: 2, visible: true, config: { features: [{ title: 'Verificado', description: 'Todos os imóveis são auditados', icon: '✅' }, { title: 'Rápido', description: 'Processo ágil e digital', icon: '⚡' }, { title: 'Seguro', description: 'Documentação garantida', icon: '🛡️' }], columns: 3 }, styles: { padding: '60px 20px', backgroundColor: '#F8FAFC' } },
          { id: 'uc-sob-footer', type: BlockType.FOOTER, order: 3, visible: true, config: {}, styles: { padding: '40px 20px' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'uc-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Agende uma Visita', subtitle: 'Estamos prontos para ajudá-lo', backgroundImage: IMG.urban2, overlayOpacity: 0.4, formTitle: 'Fale Conosco', formSubtitle: 'Preencha o formulário', submitText: 'Enviar', height: 550, textColor: '#ffffff', showBadges: false }, styles: { padding: '0px' } },
          { id: 'uc-con-map', type: BlockType.MAP, order: 1, visible: true, config: { latitude: -23.5505, longitude: -46.6333, zoom: 14 }, styles: { padding: '0px', height: '400px' } },
          { id: 'uc-con-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px' } },
        ],
      },
    ],
  },
  {
    id: 'moderno-bold',
    name: 'Moderno Bold',
    description: 'Design impactante com vermelho vibrante para imobiliárias ousadas',
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop',
    category: 'universal',
    globalTheme: makeTheme({
      primaryColor: '#DC2626',
      secondaryColor: '#111827',
      backgroundColor: '#FFFFFF',
      textColor: '#111827',
      fontFamily: 'Montserrat, sans-serif',
      headingFontFamily: 'Montserrat, sans-serif',
      borderRadius: '0px',
    }),
    menuConfig: [
      { id: 'mb-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'mb-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'mb-m3', label: 'Sobre', type: 'page', pageId: 'sobre', order: 2 },
      { id: 'mb-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'mb-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'COMPRE COM FORÇA', subtitle: 'Imóveis que mudam sua vida', backgroundImage: IMG.bold, overlayOpacity: 0.6, ctaText: 'VER IMÓVEIS', ctaLink: '#imoveis', height: 650, alignment: 'center', textColor: '#ffffff' }, styles: { padding: '0px' } },
          { id: 'mb-divider1', type: BlockType.DIVIDER, order: 1, visible: true, config: { style: 'solid', color: '#DC2626', thickness: 4, width: '100%' }, styles: { padding: '0px' } },
          { id: 'mb-stats', type: BlockType.STATS, order: 2, visible: true, config: { stats: [{ value: '500+', label: 'Imóveis', icon: '🏡' }, { value: '300+', label: 'Clientes', icon: '👥' }, { value: '15', label: 'Anos', icon: '⭐' }, { value: '50+', label: 'Parceiros', icon: '🤝' }], columns: 4, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#111827' } },
          { id: 'mb-grid', type: BlockType.PROPERTY_GRID, order: 3, visible: true, config: { columns: 3, gap: 24, showFilters: false, maxItems: 6, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'mb-divider2', type: BlockType.DIVIDER, order: 4, visible: true, config: { style: 'solid', color: '#DC2626', thickness: 4, width: '100%' }, styles: { padding: '0px' } },
          { id: 'mb-cta', type: BlockType.CTA, order: 5, visible: true, config: { title: 'Pronto para Mudar de Vida?', description: 'Comece agora mesmo', buttonText: 'COMEÇAR', buttonLink: '#contato', backgroundColor: '#DC2626', textColor: '#ffffff' }, styles: { padding: '80px 20px' } },
          { id: 'mb-testimonials', type: BlockType.TESTIMONIALS, order: 6, visible: true, config: { testimonials: [{ name: 'Marcos Ribeiro', rating: 5, text: 'Processo rápido e transparente. Recomendo!' }, { name: 'Juliana Alves', rating: 5, text: 'Excelente atendimento. Voltarei a comprar!' }], layout: 'grid', showRating: true }, styles: { padding: '60px 20px', backgroundColor: '#111827' } },
          { id: 'mb-broker', type: BlockType.BROKER_CARD, order: 7, visible: true, config: { name: 'André Martins', photoUrl: '', creci: '67890-J', specialty: 'Imóveis Residenciais', phone: '(11) 98888-0000', email: 'andre@imobzy.com', description: 'Corretor destemido com resultados comprovados.' }, styles: { padding: '60px 20px' } },
          { id: 'mb-footer', type: BlockType.FOOTER, order: 8, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#111827' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'mb-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'ENCONTRE SEU IMÓVEL', subtitle: 'Filtros poderosos, resultados reais', backgroundImage: IMG.bold2, overlayOpacity: 0.5, height: 350, alignment: 'center', textColor: '#ffffff' }, styles: { padding: '0px' } },
          { id: 'mb-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 30, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'mb-imp-cta', type: BlockType.CTA, order: 2, visible: true, config: { title: 'CADASTRE SEU IMÓVEL GRÁTIS', description: 'Divulgue para milhares de compradores', buttonText: 'CADASTRAR', buttonLink: '#contato', backgroundColor: '#DC2626', textColor: '#ffffff' }, styles: { padding: '60px 20px' } },
          { id: 'mb-imp-footer', type: BlockType.FOOTER, order: 3, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#111827' } },
        ],
      },
      {
        title: 'Sobre',
        slug: 'sobre',
        isHome: false,
        blocks: [
          { id: 'mb-sob-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'QUEM SOMOS', subtitle: 'Impacto e resultado desde 2009', backgroundImage: IMG.bold, overlayOpacity: 0.6, height: 350, alignment: 'center', textColor: '#ffffff' }, styles: { padding: '0px' } },
          { id: 'mb-sob-text', type: BlockType.TEXT, order: 1, visible: true, config: { content: '<h2>Nossa Força</h2><p>Somos uma imobiliária que pensa grande. Com estratégia e determinação, entregamos resultados reais para nossos clientes.</p>', fontSize: 16, fontWeight: 400, color: '#111827', alignment: 'left' }, styles: { padding: '60px 20px' } },
          { id: 'mb-sob-timeline', type: BlockType.TIMELINE, order: 2, visible: true, config: { title: 'Nossos Marcos', items: [{ title: 'Fundação', description: 'Início agressivo no mercado', time: '2009' }, { title: 'Crescimento', description: '100 imóveis no 1º ano', time: '2010' }, { title: 'Liderança', description: 'Top 5 da região', time: '2018' }] }, styles: { padding: '60px 20px', backgroundColor: '#111827' } },
          { id: 'mb-sob-stats', type: BlockType.STATS, order: 3, visible: true, config: { stats: [{ value: '500+', label: 'Imóveis', icon: '🏡' }, { value: '95%', label: 'Satisfação', icon: '⭐' }], columns: 2, animated: true }, styles: { padding: '60px 20px' } },
          { id: 'mb-sob-footer', type: BlockType.FOOTER, order: 4, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#111827' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'mb-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'VAMOS CONVERSAR', subtitle: 'Atendimento direto e sem enrolação', backgroundImage: IMG.bold2, overlayOpacity: 0.6, formTitle: 'FALE CONOSCO', formSubtitle: 'Resposta garantida', submitText: 'ENVIAR', height: 550, textColor: '#ffffff', showBadges: false }, styles: { padding: '0px' } },
          { id: 'mb-con-map', type: BlockType.MAP, order: 1, visible: true, config: { latitude: -23.5505, longitude: -46.6333, zoom: 14 }, styles: { padding: '0px', height: '400px' } },
          { id: 'mb-con-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#111827' } },
        ],
      },
    ],
  },
  {
    id: 'cinema-imovel',
    name: 'Cinema Imóvel',
    description: 'Experiência imersiva cinematográfica para imobiliárias que valorizam storytelling',
    thumbnail: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400&h=300&fit=crop',
    category: 'universal',
    globalTheme: makeTheme({
      primaryColor: '#3B82F6',
      secondaryColor: '#1E3A5F',
      backgroundColor: '#0F172A',
      textColor: '#E2E8F0',
      fontFamily: 'Raleway, sans-serif',
      headingFontFamily: 'Raleway, sans-serif',
    }),
    menuConfig: [
      { id: 'ci-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'ci-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'ci-m3', label: 'Galeria', type: 'page', pageId: 'galeria', order: 2 },
      { id: 'ci-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'ci-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'A História do Seu Novo Lar Começa Aqui', subtitle: 'Descubra imóveis que contam histórias', backgroundImage: IMG.cinema, overlayOpacity: 0.6, height: 700, alignment: 'center', textColor: '#E2E8F0' }, styles: { padding: '0px' } },
          { id: 'ci-video', type: BlockType.VIDEO, order: 1, visible: true, config: { url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', autoplay: false, loop: false, muted: true, controls: true }, styles: { padding: '60px 20px', backgroundColor: '#0F172A' } },
          { id: 'ci-text', type: BlockType.TEXT, order: 2, visible: true, config: { content: '<h2 style="text-align:center;color:#3B82F6">Cada imóvel tem uma história</h2><p style="text-align:center;color:#E2E8F0">Nós ajudamos você a encontrá-la. Explore nosso catálogo e descubra o lugar perfeito para escrever o próximo capítulo da sua vida.</p>', fontSize: 17, fontWeight: 400, color: '#E2E8F0', alignment: 'center' }, styles: { padding: '60px 20px' } },
          { id: 'ci-carousel', type: BlockType.PROPERTY_CAROUSEL, order: 3, visible: true, config: { autoplay: true, interval: 5000, showArrows: true, showDots: true, itemsPerView: 3 }, styles: { padding: '0px 20px 60px' } },
          { id: 'ci-grid', type: BlockType.PROPERTY_GRID, order: 4, visible: true, config: { columns: 3, gap: 24, showFilters: false, maxItems: 6, sortBy: 'date', cardStyle: 'modern' }, styles: { padding: '0px 20px 60px' } },
          { id: 'ci-stats', type: BlockType.STATS, order: 5, visible: true, config: { stats: [{ value: '500+', label: 'Imóveis', icon: '🏡' }, { value: '15+', label: 'Anos', icon: '⭐' }, { value: '98%', label: 'Satisfação', icon: '👥' }], columns: 3, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#1E3A5F' } },
          { id: 'ci-gallery', type: BlockType.GALLERY, order: 6, visible: true, config: { images: [{ src: IMG.cinema, alt: 'Vista aérea', caption: 'Vista panorâmica' }, { src: IMG.cinema2, alt: 'Interiores', caption: 'Ambientes sofisticados' }, { src: IMG.bold, alt: 'Fachada', caption: 'Arquitetura moderna' }, { src: IMG.urban, alt: 'Área externa', caption: 'Áreas de lazer' }], columns: 2, gap: 16, lightbox: true }, styles: { padding: '60px 20px' } },
          { id: 'ci-testimonials', type: BlockType.TESTIMONIALS, order: 7, visible: true, config: { testimonials: [{ name: 'Patricia Mendes', rating: 5, text: 'A experiência de compra foi cinematográfica. Cada detalhe pensado.' }, { name: 'Thiago Rocha', rating: 5, text: 'Encontrei exatamente o que procurava. Equipe excepcional.' }], layout: 'grid', showRating: true }, styles: { padding: '60px 20px', backgroundColor: '#0F172A' } },
          { id: 'ci-cta', type: BlockType.CTA, order: 8, visible: true, config: { title: 'Descubra seu Próximo Capítulo', description: 'A jornada até o lar perfeito começa aqui', buttonText: 'Começar Jornada', buttonLink: '#contato', backgroundColor: '#3B82F6', textColor: '#ffffff' }, styles: { padding: '80px 20px' } },
          { id: 'ci-footer', type: BlockType.FOOTER, order: 9, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0F172A' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'ci-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Explore Nosso Catálogo', subtitle: 'Imóveis selecionados com curadoria', backgroundImage: IMG.cinema2, overlayOpacity: 0.5, height: 400, alignment: 'center', textColor: '#E2E8F0' }, styles: { padding: '0px' } },
          { id: 'ci-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 30, sortBy: 'date', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'ci-imp-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0F172A' } },
        ],
      },
      {
        title: 'Galeria',
        slug: 'galeria',
        isHome: false,
        blocks: [
          { id: 'ci-gal-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Galeria de Projetos', subtitle: 'Imagens que contam histórias', backgroundImage: IMG.cinema, overlayOpacity: 0.5, height: 350, alignment: 'center', textColor: '#E2E8F0' }, styles: { padding: '0px' } },
          { id: 'ci-gal-gallery', type: BlockType.GALLERY, order: 1, visible: true, config: { images: [{ src: IMG.cinema, alt: 'Projeto 1' }, { src: IMG.cinema2, alt: 'Projeto 2' }, { src: IMG.bold, alt: 'Projeto 3' }, { src: IMG.urban, alt: 'Projeto 4' }, { src: IMG.luxury, alt: 'Projeto 5' }, { src: IMG.bold2, alt: 'Projeto 6' }], columns: 3, gap: 16, lightbox: true }, styles: { padding: '60px 20px' } },
          { id: 'ci-gal-video', type: BlockType.VIDEO, order: 2, visible: true, config: { url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', autoplay: false, loop: false, muted: true, controls: true }, styles: { padding: '60px 20px' } },
          { id: 'ci-gal-footer', type: BlockType.FOOTER, order: 3, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0F172A' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'ci-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Vamos Conversar', subtitle: 'Inicie sua história conosco', backgroundImage: IMG.cinema2, overlayOpacity: 0.5, formTitle: 'Entre em Contato', formSubtitle: 'Conte-nos o que procura', submitText: 'Enviar', height: 550, textColor: '#E2E8F0', showBadges: false }, styles: { padding: '0px' } },
          { id: 'ci-con-broker', type: BlockType.BROKER_CARD, order: 1, visible: true, config: { name: 'Ricardo Teles', photoUrl: '', creci: '11111-J', specialty: 'Imóveis Premium', phone: '(11) 97777-0000', email: 'ricardo@imobzy.com', description: 'Especialista em imóveis de alto padrão e investimento.' }, styles: { padding: '60px 20px', backgroundColor: '#1E3A5F' } },
          { id: 'ci-con-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0F172A' } },
        ],
      },
    ],
  },
  {
    id: 'classico-brasileiro',
    name: 'Clássico Brasileiro',
    description: 'Template tradicional com azul marinho e dourado para imobiliárias consolidadas',
    thumbnail: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&h=300&fit=crop',
    category: 'universal',
    globalTheme: makeTheme({
      primaryColor: '#1E3A5F',
      secondaryColor: '#B8860B',
      backgroundColor: '#FAFAFA',
      textColor: '#2C3E50',
      fontFamily: 'Merriweather, serif',
      headingFontFamily: 'Playfair Display, serif',
    }),
    menuConfig: [
      { id: 'cl-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'cl-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'cl-m3', label: 'Sobre', type: 'page', pageId: 'sobre', order: 2 },
      { id: 'cl-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'cl-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Tradição que Constrói Confiança', subtitle: 'Desde 1995 conectando famílias ao lar ideal', backgroundImage: IMG.classic, overlayOpacity: 0.5, ctaText: 'Conheça Nossos Imóveis', ctaLink: '#imoveis', height: 600, alignment: 'center', textColor: '#FAFAFA' }, styles: { padding: '0px' } },
          { id: 'cl-divider', type: BlockType.DIVIDER, order: 1, visible: true, config: { style: 'solid', color: '#B8860B', thickness: 2, width: '200px' }, styles: { padding: '30px 0', textAlign: 'center' } },
          { id: 'cl-text', type: BlockType.TEXT, order: 2, visible: true, config: { content: '<h2 style="text-align:center;color:#1E3A5F">Excelência Imobiliária</h2><p style="text-align:center;color:#2C3E50">Atendimento personalizado com a seriedade e compromisso que só uma tradição de mais de 25 anos pode oferecer.</p>', fontSize: 17, fontWeight: 400, color: '#2C3E50', alignment: 'center' }, styles: { padding: '40px 20px 60px' } },
          { id: 'cl-grid', type: BlockType.PROPERTY_GRID, order: 3, visible: true, config: { columns: 3, gap: 24, showFilters: false, maxItems: 6, sortBy: 'price', cardStyle: 'classic' }, styles: { padding: '0px 20px 60px' } },
          { id: 'cl-stats', type: BlockType.STATS, order: 4, visible: true, config: { stats: [{ value: '500+', label: 'Imóveis Vendidos', icon: '🏡' }, { value: '28', label: 'Anos de Tradição', icon: '⭐' }, { value: '99%', label: 'Satisfação', icon: '👥' }, { value: '+R$1.5B', label: 'Em Negócios', icon: '💰' }], columns: 4, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#1E3A5F' } },
          { id: 'cl-testimonials', type: BlockType.TESTIMONIALS, order: 5, visible: true, config: { testimonials: [{ name: 'Dr. Paulo Henrique', rating: 5, text: 'Tradição e confiança. Excelente assessoria imobiliária.' }, { name: 'Sra. Helena Costa', rating: 5, text: 'Família que confia há gerações. Serviço impecável.' }, { name: 'Eng. Ricardo Souza', rating: 5, text: 'Profissionalismo que inspira confiança.' }], layout: 'carousel', showRating: true }, styles: { padding: '60px 20px', backgroundColor: '#FAFAFA' } },
          { id: 'cl-timeline', type: BlockType.TIMELINE, order: 6, visible: true, config: { title: 'Nossa Trajetória', items: [{ title: 'Fundação', description: 'Início das operações com excelência', time: '1995' }, { title: 'Expansão', description: 'Presença em 3 estados', time: '2005' }, { title: 'Centenário Virtual', description: '500º imóvel vendido', time: '2015' }, { title: 'Inovação', description: 'Plataforma digital', time: '2020' }] }, styles: { padding: '60px 20px', backgroundColor: '#F0ECE0' } },
          { id: 'cl-footer', type: BlockType.FOOTER, order: 7, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#1E3A5F' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'cl-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Nosso Portfólio', subtitle: 'Imóveis selecionados com tradição', backgroundImage: IMG.classic2, overlayOpacity: 0.4, height: 400, alignment: 'center', textColor: '#FAFAFA' }, styles: { padding: '0px' } },
          { id: 'cl-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 30, sortBy: 'price', cardStyle: 'classic' }, styles: { padding: '60px 20px' } },
          { id: 'cl-imp-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#1E3A5F' } },
        ],
      },
      {
        title: 'Sobre',
        slug: 'sobre',
        isHome: false,
        blocks: [
          { id: 'cl-sob-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Nossa História', subtitle: 'Mais de 25 anos de tradição', backgroundImage: IMG.classic, overlayOpacity: 0.5, height: 400, alignment: 'center', textColor: '#FAFAFA' }, styles: { padding: '0px' } },
          { id: 'cl-sob-text', type: BlockType.TEXT, order: 1, visible: true, config: { content: '<h2 style="color:#1E3A5F">Valores Fundamentais</h2><p>Com ética, transparência e dedicação, construímos uma das mais respeitadas imobiliárias do mercado. Cada cliente é tratado com a atenção que merece.</p>', fontSize: 17, fontWeight: 400, color: '#2C3E50', alignment: 'left' }, styles: { padding: '60px 20px' } },
          { id: 'cl-sob-timeline', type: BlockType.TIMELINE, order: 2, visible: true, config: { title: 'Marcos Importantes', items: [{ title: '1995', description: 'Fundação da empresa' }, { title: '2005', description: 'Expansão regional' }, { title: '2015', description: '500 vendas' }, { title: '2024', description: 'Plataforma digital' }] }, styles: { padding: '60px 20px', backgroundColor: '#F0ECE0' } },
          { id: 'cl-sob-stats', type: BlockType.STATS, order: 3, visible: true, config: { stats: [{ value: '28', label: 'Anos', icon: '⭐' }, { value: '500+', label: 'Vendas', icon: '🏡' }], columns: 2, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#1E3A5F' } },
          { id: 'cl-sob-broker', type: BlockType.BROKER_CARD, order: 4, visible: true, config: { name: 'José Carlos Fontes', photoUrl: '', creci: '00001-J', specialty: 'Diretor Geral', phone: '(11) 3000-0000', email: 'jose@imobzy.com', description: 'Fundador e diretor com 28 anos de experiência no mercado.' }, styles: { padding: '60px 20px' } },
          { id: 'cl-sob-footer', type: BlockType.FOOTER, order: 5, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#1E3A5F' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'cl-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Fale Conosco', subtitle: 'Atendimento com a seriedade que você merece', backgroundImage: IMG.classic2, overlayOpacity: 0.5, formTitle: 'Envie sua Mensagem', formSubtitle: 'Retornaremos com brevidade', submitText: 'Enviar Mensagem', height: 550, textColor: '#FAFAFA', showBadges: false }, styles: { padding: '0px' } },
          { id: 'cl-con-map', type: BlockType.MAP, order: 1, visible: true, config: { latitude: -23.5505, longitude: -46.6333, zoom: 14 }, styles: { padding: '0px', height: '400px' } },
          { id: 'cl-con-broker', type: BlockType.BROKER_CARD, order: 2, visible: true, config: { name: 'José Carlos Fontes', photoUrl: '', creci: '00001-J', specialty: 'Diretor Geral', phone: '(11) 3000-0000', email: 'jose@imobzy.com', description: 'Atendimento personalizado para cada cliente.' }, styles: { padding: '60px 20px' } },
          { id: 'cl-con-footer', type: BlockType.FOOTER, order: 3, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#1E3A5F' } },
        ],
      },
    ],
  },
  {
    id: 'tech-glass',
    name: 'Tech Glass',
    description: 'Futurista com glass morphism e gradientes neon para imobiliárias tech',
    thumbnail: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=300&fit=crop',
    category: 'universal',
    globalTheme: makeTheme({
      primaryColor: '#8B5CF6',
      secondaryColor: '#06B6D4',
      backgroundColor: '#0F0F23',
      textColor: '#E0E0FF',
      fontFamily: 'Space Grotesk, sans-serif',
      headingFontFamily: 'Space Grotesk, sans-serif',
      borderRadius: '1rem',
    }),
    menuConfig: [
      { id: 'tg-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'tg-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'tg-m3', label: 'Inovação', type: 'page', pageId: 'inovacao', order: 2 },
      { id: 'tg-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'tg-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'O Futuro da Imobiliária é Agora', subtitle: 'Tecnologia e inovação a serviço do seu novo lar', backgroundImage: IMG.tech, overlayOpacity: 0.6, formTitle: 'Busca Inteligente', formSubtitle: 'IA encontra o imóvel ideal para você', submitText: 'Buscar com IA', height: 650, textColor: '#E0E0FF', showBadges: true, badges: [{ icon: 'zap', title: 'Busca por IA', description: 'Algoritmo inteligente' }, { icon: 'shield', title: 'Dados Seguros', description: 'Criptografia avançada' }, { icon: 'star', title: 'Top Tech', description: 'Plataforma inovadora' }] }, styles: { padding: '0px' } },
          { id: 'tg-features', type: BlockType.FEATURES, order: 1, visible: true, config: { features: [{ title: 'IA de Busca', description: 'Algoritmo que aprende suas preferências', icon: '🤖' }, { title: 'Tour Virtual 360°', description: 'Veja cada cômodo em realidade virtual', icon: '🌐' }, { title: 'Simulador', description: 'Cálculo de financiamento instantâneo', icon: '📊' }, { title: 'Contrato Digital', description: 'Assine eletronicamente com segurança', icon: '📝' }], columns: 4 }, styles: { padding: '60px 20px', backgroundColor: '#0F0F23' } },
          { id: 'tg-grid', type: BlockType.PROPERTY_GRID, order: 2, visible: true, config: { columns: 3, gap: 24, showFilters: false, maxItems: 6, sortBy: 'date', cardStyle: 'modern' }, styles: { padding: '0px 20px 60px' } },
          { id: 'tg-carousel', type: BlockType.PROPERTY_CAROUSEL, order: 3, visible: true, config: { autoplay: true, interval: 4000, showArrows: true, showDots: true, itemsPerView: 3 }, styles: { padding: '0px 20px 60px' } },
          { id: 'tg-stats', type: BlockType.STATS, order: 4, visible: true, config: { stats: [{ value: '800+', label: 'Imóveis', icon: '🏡' }, { value: '50k+', label: 'Usuários', icon: '👥' }, { value: '99.9%', label: 'Uptime', icon: '⚡' }, { value: '4.9★', label: 'Rating', icon: '⭐' }], columns: 4, animated: true }, styles: { padding: '60px 20px', background: 'linear-gradient(135deg, #8B5CF6, #06B6D4)' } },
          { id: 'tg-video', type: BlockType.VIDEO, order: 5, visible: true, config: { url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', autoplay: false, loop: false, muted: true, controls: true }, styles: { padding: '60px 20px' } },
          { id: 'tg-testimonials', type: BlockType.TESTIMONIALS, order: 6, visible: true, config: { testimonials: [{ name: 'Startup Imob', rating: 5, text: 'A plataforma mais inovadora que já usamos. Revolucionária!' }, { name: 'Tech Properties', rating: 5, text: 'IA realmente funciona. Encontramos imóveis em segundos.' }], layout: 'grid', showRating: true }, styles: { padding: '60px 20px', backgroundColor: '#0F0F23' } },
          { id: 'tg-cta', type: BlockType.CTA, order: 7, visible: true, config: { title: 'Experimente a Diferença', description: 'Cadastre-se e descubra o futuro dos imóveis', buttonText: 'Começar Agora', buttonLink: '#contato', backgroundColor: '#8B5CF6', textColor: '#ffffff' }, styles: { padding: '80px 20px' } },
          { id: 'tg-footer', type: BlockType.FOOTER, order: 8, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0F0F23' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'tg-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Busca Inteligente', subtitle: 'Deixe a IA encontrar o imóvel perfeito', backgroundImage: IMG.tech2, overlayOpacity: 0.6, height: 350, alignment: 'center', textColor: '#E0E0FF' }, styles: { padding: '0px' } },
          { id: 'tg-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 30, sortBy: 'date', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'tg-imp-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0F0F23' } },
        ],
      },
      {
        title: 'Inovação',
        slug: 'inovacao',
        isHome: false,
        blocks: [
          { id: 'tg-inov-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Tecnologia a Serviço', subtitle: 'Conheça nossas inovações', backgroundImage: IMG.tech, overlayOpacity: 0.6, height: 400, alignment: 'center', textColor: '#E0E0FF' }, styles: { padding: '0px' } },
          { id: 'tg-inov-features', type: BlockType.FEATURES, order: 1, visible: true, config: { features: [{ title: 'Machine Learning', description: 'Previsão de preços e tendências', icon: '🧠' }, { title: 'Blockchain', description: 'Transações seguras e transparentes', icon: '🔗' }, { title: 'IoT', description: 'Casas inteligentes conectadas', icon: '📡' }, { title: 'Realidade Aumentada', description: 'Visualize móveis no imóvel', icon: '👓' }, { title: 'Chat 24/7', description: 'Atendimento por IA a qualquer hora', icon: '💬' }, { title: 'Analytics', description: 'Insights de mercado em tempo real', icon: '📈' }], columns: 3 }, styles: { padding: '60px 20px' } },
          { id: 'tg-inov-video', type: BlockType.VIDEO, order: 2, visible: true, config: { url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', autoplay: false, loop: false, muted: true, controls: true }, styles: { padding: '60px 20px', backgroundColor: '#0F0F23' } },
          { id: 'tg-inov-timeline', type: BlockType.TIMELINE, order: 3, visible: true, config: { title: 'Evolução Tecnológica', items: [{ title: '2020', description: 'Plataforma web lançada' }, { title: '2022', description: 'IA de busca implementada' }, { title: '2024', description: 'Tour virtual 360°' }, { title: '2025', description: 'Integração blockchain' }] }, styles: { padding: '60px 20px' } },
          { id: 'tg-inov-footer', type: BlockType.FOOTER, order: 4, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0F0F23' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'tg-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Experimente a Diferença', subtitle: 'Fale com nossa equipe tech', backgroundImage: IMG.tech2, overlayOpacity: 0.6, formTitle: 'Contato', formSubtitle: 'Responderemos em minutos', submitText: 'Enviar', height: 550, textColor: '#E0E0FF', showBadges: false }, styles: { padding: '0px' } },
          { id: 'tg-con-footer', type: BlockType.FOOTER, order: 1, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0F0F23' } },
        ],
      },
    ],
  },
  {
    id: 'costa-mar',
    name: 'Costa & Mar',
    description: 'Template litorâneo para imobiliárias de imóveis de praia e frente marítima',
    thumbnail: 'https://images.unsplash.com/photo-1499793983394-2d6e66b9b832?w=400&h=300&fit=crop',
    category: 'universal',
    globalTheme: makeTheme({
      primaryColor: '#0077B6',
      secondaryColor: '#F4A261',
      backgroundColor: '#F0F7FA',
      textColor: '#1B4965',
      fontFamily: 'Nunito, sans-serif',
      headingFontFamily: 'Quicksand, sans-serif',
      borderRadius: '1.25rem',
    }),
    menuConfig: [
      { id: 'cm-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'cm-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'cm-m3', label: 'Praias', type: 'page', pageId: 'praias', order: 2 },
      { id: 'cm-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'cm-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Viva à Beira do Mar', subtitle: 'Imóveis de frente marítima para sua nova vida', backgroundImage: IMG.beach, overlayOpacity: 0.4, ctaText: 'Ver Imóveis', ctaLink: '#imoveis', height: 650, alignment: 'center', textColor: '#F0F7FA' }, styles: { padding: '0px' } },
          { id: 'cm-stats', type: BlockType.STATS, order: 1, visible: true, config: { stats: [{ value: '300+', label: 'Imóveis à Beira-Mar', icon: '🏖️' }, { value: '15', label: 'Praias', icon: '🌊' }, { value: '95%', label: 'Satisfação', icon: '⭐' }, { value: '+R$500M', label: 'Em Vendas', icon: '💰' }], columns: 4, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#0077B6' } },
          { id: 'cm-text', type: BlockType.TEXT, order: 2, visible: true, config: { content: '<h2 style="text-align:center;color:#0077B6">Onde cada dia é férias</h2><p style="text-align:center;color:#1B4965">Imagine acordar com o som das ondas e a vista do mar. Na Costa & Mar, tornamos esse sonho realidade.</p>', fontSize: 17, fontWeight: 400, color: '#1B4965', alignment: 'center' }, styles: { padding: '40px 20px 60px' } },
          { id: 'cm-grid', type: BlockType.PROPERTY_GRID, order: 3, visible: true, config: { columns: 3, gap: 24, showFilters: false, maxItems: 6, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '0px 20px 60px' } },
          { id: 'cm-carousel', type: BlockType.PROPERTY_CAROUSEL, order: 4, visible: true, config: { autoplay: true, interval: 5000, showArrows: true, showDots: true, itemsPerView: 3 }, styles: { padding: '0px 20px 60px' } },
          { id: 'cm-gallery', type: BlockType.GALLERY, order: 5, visible: true, config: { images: [{ src: IMG.beach, alt: 'Praia' }, { src: IMG.beach2, alt: 'Areia' }, { src: IMG.urban, alt: 'Piscina' }, { src: IMG.luxury, alt: 'Vista mar' }], columns: 2, gap: 16, lightbox: true }, styles: { padding: '60px 20px' } },
          { id: 'cm-features', type: BlockType.FEATURES, order: 6, visible: true, config: { features: [{ title: 'Praia Próxima', description: 'A poucos metros da areia', icon: '🏖️' }, { title: 'Vista para o Mar', description: 'Contemple o oceano todos os dias', icon: '🌊' }, { title: 'Área de Lazer', description: 'Piscina, churrasqueia e mais', icon: '🏊' }, { title: 'Segurança', description: '24h monitorado', icon: '🛡️' }], columns: 4 }, styles: { padding: '60px 20px', backgroundColor: '#F0F7FA' } },
          { id: 'cm-testimonials', type: BlockType.TESTIMONIALS, order: 7, visible: true, config: { testimonials: [{ name: 'Amanda Silva', rating: 5, text: 'Finalmente realizei o sonho de viver à beira-mar. Perfeito!' }, { name: 'Pedro Lima', rating: 5, text: 'Investimento retorno garantido. Localização irrepreensível.' }], layout: 'grid', showRating: true }, styles: { padding: '60px 20px' } },
          { id: 'cm-cta', type: BlockType.CTA, order: 8, visible: true, config: { title: 'Encontre seu Pedacinho do Paraíso', description: 'Imóveis exclusivos na beira-mar', buttonText: 'Ver Oportunidades', buttonLink: '#imoveis', backgroundColor: '#0077B6', textColor: '#ffffff' }, styles: { padding: '80px 20px' } },
          { id: 'cm-map', type: BlockType.MAP, order: 9, visible: true, config: { latitude: -22.9068, longitude: -43.1729, zoom: 11 }, styles: { padding: '0px', height: '400px' } },
          { id: 'cm-footer', type: BlockType.FOOTER, order: 10, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0077B6' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'cm-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Imóveis à Beira-Mar', subtitle: 'Casas, apartamentos e flats com vista para o mar', backgroundImage: IMG.beach2, overlayOpacity: 0.4, height: 400, alignment: 'center', textColor: '#F0F7FA' }, styles: { padding: '0px' } },
          { id: 'cm-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 30, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'cm-imp-map', type: BlockType.MAP, order: 2, visible: true, config: { latitude: -22.9068, longitude: -43.1729, zoom: 10 }, styles: { padding: '0px', height: '400px' } },
          { id: 'cm-imp-footer', type: BlockType.FOOTER, order: 3, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0077B6' } },
        ],
      },
      {
        title: 'Praias',
        slug: 'praias',
        isHome: false,
        blocks: [
          { id: 'cm-prai-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Nossas Praias', subtitle: 'Conheça as praias com imóveis disponíveis', backgroundImage: IMG.beach, overlayOpacity: 0.4, height: 400, alignment: 'center', textColor: '#F0F7FA' }, styles: { padding: '0px' } },
          { id: 'cm-prai-gallery', type: BlockType.GALLERY, order: 1, visible: true, config: { images: [{ src: IMG.beach, alt: 'Praia 1', caption: 'Praia do Sol' }, { src: IMG.beach2, alt: 'Praia 2', caption: 'Praia da Lua' }, { src: IMG.urban, alt: 'Praia 3', caption: 'Praia dos Sonhos' }], columns: 3, gap: 16, lightbox: true }, styles: { padding: '60px 20px' } },
          { id: 'cm-prai-text', type: BlockType.TEXT, order: 2, visible: true, config: { content: '<h2 style="color:#0077B6">Escolha sua Praia</h2><p>Cada praia tem sua personalidade. Encontre aquela que combina com seu estilo de vida e descubra os melhores imóveis da região.</p>', fontSize: 17, fontWeight: 400, color: '#1B4965', alignment: 'left' }, styles: { padding: '40px 20px 60px' } },
          { id: 'cm-prai-map', type: BlockType.MAP, order: 3, visible: true, config: { latitude: -22.9068, longitude: -43.1729, zoom: 9 }, styles: { padding: '0px', height: '400px' } },
          { id: 'cm-prai-footer', type: BlockType.FOOTER, order: 4, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0077B6' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'cm-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Planeje sua Vida na Costa', subtitle: 'Fale com nossos especialistas em imóveis de praia', backgroundImage: IMG.beach2, overlayOpacity: 0.4, formTitle: 'Solicite Informações', formSubtitle: 'Preencha e descubra as opções', submitText: 'Enviar', height: 550, textColor: '#F0F7FA', showBadges: true, badges: [{ icon: 'waves', title: 'Beira-Mar', description: 'Frente marítima' }, { icon: 'shield', title: 'Documentação', description: '100% regularizado' }, { icon: 'star', title: 'Seleção', description: 'Imóveis verificados' }] }, styles: { padding: '0px' } },
          { id: 'cm-con-footer', type: BlockType.FOOTER, order: 1, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#0077B6' } },
        ],
      },
    ],
  },
  {
    id: 'comercial-pro',
    name: 'Comercial Pro',
    description: 'Template corporativo para imobiliárias de imóveis comerciais e salas',
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&h=300&fit=crop',
    category: 'universal',
    globalTheme: makeTheme({
      primaryColor: '#1D4ED8',
      secondaryColor: '#475569',
      backgroundColor: '#F8FAFC',
      textColor: '#1E293B',
      fontFamily: 'IBM Plex Sans, sans-serif',
      headingFontFamily: 'IBM Plex Sans, sans-serif',
      borderRadius: '0.375rem',
    }),
    menuConfig: [
      { id: 'cp-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'cp-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'cp-m3', label: 'Soluções', type: 'page', pageId: 'solucoes', order: 2 },
      { id: 'cp-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'cp-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'O Espaço Certo para o Seu Negócio', subtitle: 'Imóveis comerciais e salas nas melhores regiões', backgroundImage: IMG.commercial, overlayOpacity: 0.6, formTitle: 'Busca Comercial', formSubtitle: 'Tipo, região e tamanho', submitText: 'Buscar', height: 600, textColor: '#ffffff', showBadges: false }, styles: { padding: '0px' } },
          { id: 'cp-features', type: BlockType.FEATURES, order: 1, visible: true, config: { features: [{ title: 'Áreas Comerciais', description: 'Lojas, salas e escritórios', icon: '🏢' }, { title: 'Galpões', description: 'Industriais e logísticos', icon: '🏭' }, { title: 'Salas de Reunião', description: 'Ambientes profissionais', icon: '🤝' }, { title: 'Lojas e Varejo', description: 'Pontos comerciais', icon: '🛍️' }], columns: 4 }, styles: { padding: '60px 20px', backgroundColor: '#F8FAFC' } },
          { id: 'cp-grid', type: BlockType.PROPERTY_GRID, order: 2, visible: true, config: { columns: 3, gap: 24, showFilters: false, maxItems: 6, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '0px 20px 60px' } },
          { id: 'cp-carousel', type: BlockType.PROPERTY_CAROUSEL, order: 3, visible: true, config: { autoplay: true, interval: 5000, showArrows: true, showDots: true, itemsPerView: 3 }, styles: { padding: '0px 20px 60px' } },
          { id: 'cp-stats', type: BlockType.STATS, order: 4, visible: true, config: { stats: [{ value: '400+', label: 'Imóveis Comerciais', icon: '🏢' }, { value: '200+', label: 'Empresas', icon: '👥' }, { value: 'R$1B+', label: 'Em Transações', icon: '💰' }, { value: '15', label: 'Anos', icon: '⭐' }], columns: 4, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#1D4ED8' } },
          { id: 'cp-timeline', type: BlockType.TIMELINE, order: 5, visible: true, config: { title: 'Mercado Comercial', items: [{ title: 'Expansão', description: 'Crescimento do setor', time: '2020' }, { title: 'Digitalização', description: 'Negócios online', time: '2022' }, { title: 'Híbrido', description: 'Novos formatos de espaço', time: '2024' }] }, styles: { padding: '60px 20px', backgroundColor: '#F8FAFC' } },
          { id: 'cp-testimonials', type: BlockType.TESTIMONIALS, order: 6, visible: true, config: { testimonials: [{ name: 'Empresa XYZ', rating: 5, text: 'Encontramos o escritório perfeito. Processo ágil e profissional.' }, { name: 'Loja ABC', rating: 5, text: 'Excelente localização e preço justo.' }], layout: 'grid', showRating: true }, styles: { padding: '60px 20px' } },
          { id: 'cp-cta', type: BlockType.CTA, order: 7, visible: true, config: { title: 'Consultoria Gratuita', description: 'Fale com um especialista em imóveis comerciais', buttonText: 'Agendar Consulta', buttonLink: '#contato', backgroundColor: '#1D4ED8', textColor: '#ffffff' }, styles: { padding: '80px 20px' } },
          { id: 'cp-map', type: BlockType.MAP, order: 8, visible: true, config: { latitude: -23.5505, longitude: -46.6333, zoom: 13 }, styles: { padding: '0px', height: '400px' } },
          { id: 'cp-footer', type: BlockType.FOOTER, order: 9, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#1E293B' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'cp-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Portfólio Comercial', subtitle: 'Imóveis para sua empresa', backgroundImage: IMG.commercial2, overlayOpacity: 0.5, height: 400, alignment: 'center', textColor: '#ffffff' }, styles: { padding: '0px' } },
          { id: 'cp-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 30, sortBy: 'price', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'cp-imp-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#1E293B' } },
        ],
      },
      {
        title: 'Soluções',
        slug: 'solucoes',
        isHome: false,
        blocks: [
          { id: 'cp-sol-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Soluções para sua Empresa', subtitle: 'Consultoria especializada em imóveis comerciais', backgroundImage: IMG.commercial, overlayOpacity: 0.5, height: 400, alignment: 'center', textColor: '#ffffff' }, styles: { padding: '0px' } },
          { id: 'cp-sol-features', type: BlockType.FEATURES, order: 1, visible: true, config: { features: [{ title: 'Locação', description: 'Encontre o ponto ideal para alugar', icon: '📋' }, { title: 'Compra', description: 'Invista em imóveis comerciais', icon: '💰' }, { title: 'Avaliação', description: 'Análise de mercado precisa', icon: '📊' }, { title: 'Due Diligence', description: 'Verificação documental completa', icon: '🔍' }, { title: 'Financiamento', description: 'Crédito empresarial', icon: '🏦' }, { title: 'Gestão', description: 'Administração do patrimônio', icon: '⚙️' }], columns: 3 }, styles: { padding: '60px 20px' } },
          { id: 'cp-sol-timeline', type: BlockType.TIMELINE, order: 2, visible: true, config: { title: 'Processo', items: [{ title: '1. Diagnóstico', description: 'Análise das necessidades' }, { title: '2. Busca', description: 'Seleção de opções' }, { title: '3. Negociação', description: 'Melhores condições' }, { title: '4. Fechamento', description: 'Contrato e entrega' }] }, styles: { padding: '60px 20px', backgroundColor: '#F8FAFC' } },
          { id: 'cp-sol-form', type: BlockType.FORM, order: 3, visible: true, config: { title: 'Solicite uma Consultoria', fields: [{ name: 'name', type: 'text', label: 'Nome', required: true, placeholder: 'Seu nome' }, { name: 'email', type: 'email', label: 'E-mail', required: true, placeholder: 'empresa@email.com' }, { name: 'phone', type: 'tel', label: 'Telefone', required: true, placeholder: '(00) 00000-0000' }, { name: 'interest', type: 'select', label: 'Tipo', required: true, options: ['Locação', 'Compra', 'Avaliação', 'Consultoria'] }], submitText: 'Solicitar Consultoria', successMessage: 'Recebemos sua solicitação! Entraremos em contato.' }, styles: { padding: '60px 20px' } },
          { id: 'cp-sol-stats', type: BlockType.STATS, order: 4, visible: true, config: { stats: [{ value: '400+', label: 'Imóveis', icon: '🏢' }, { value: '98%', label: 'Satisfação', icon: '⭐' }], columns: 2, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#1D4ED8' } },
          { id: 'cp-sol-footer', type: BlockType.FOOTER, order: 5, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#1E293B' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'cp-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Fale com um Consultor', subtitle: 'Atendimento especializado em imóveis comerciais', backgroundImage: IMG.commercial2, overlayOpacity: 0.5, formTitle: 'Entre em Contato', formSubtitle: 'Consultoria gratuita', submitText: 'Enviar', height: 550, textColor: '#ffffff', showBadges: false }, styles: { padding: '0px' } },
          { id: 'cp-con-broker', type: BlockType.BROKER_CARD, order: 1, visible: true, config: { name: 'Fernando Barbosa', photoUrl: '', creci: '22222-J', specialty: 'Imóveis Comerciais', phone: '(11) 96666-0000', email: 'fernando@imobzy.com', description: 'Especialista em soluções comerciais e investimentos empresariais.' }, styles: { padding: '60px 20px', backgroundColor: '#F8FAFC' } },
          { id: 'cp-con-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#1E293B' } },
        ],
      },
    ],
  },
  {
    id: 'eco-sustentavel',
    name: 'Eco Sustentável',
    description: 'Template sustentável para imobiliárias de imóveis verdes e ecológicos',
    thumbnail: 'https://images.unsplash.com/photo-1518005068251-37900150dfca?w=400&h=300&fit=crop',
    category: 'universal',
    globalTheme: makeTheme({
      primaryColor: '#4A7C59',
      secondaryColor: '#A0522D',
      backgroundColor: '#F5F7F0',
      textColor: '#2D3B2D',
      fontFamily: 'DM Sans, sans-serif',
      headingFontFamily: 'Playfair Display, serif',
    }),
    menuConfig: [
      { id: 'eco-m1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'eco-m2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'eco-m3', label: 'Sustentabilidade', type: 'page', pageId: 'sustentabilidade', order: 2 },
      { id: 'eco-m4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          { id: 'eco-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Viver Bem, Viver Verde', subtitle: 'Imóveis que respeitam o planeta e sua qualidade de vida', backgroundImage: IMG.eco, overlayOpacity: 0.3, ctaText: 'Ver Imóveis Verdes', ctaLink: '#imoveis', height: 650, alignment: 'center', textColor: '#F5F7F0' }, styles: { padding: '0px' } },
          { id: 'eco-features', type: BlockType.FEATURES, order: 1, visible: true, config: { features: [{ title: 'Energia Solar', description: 'Painéis fotovoltaicos integrados', icon: '☀️' }, { title: 'Água de Chuva', description: 'Sistema de captação e reuso', icon: '💧' }, { title: 'Materiais Verdes', description: 'Construção sustentável', icon: '🌱' }, { title: 'Áreas Verdes', description: 'Jardins e hortas comunitárias', icon: '🌳' }], columns: 4 }, styles: { padding: '60px 20px', backgroundColor: '#F5F7F0' } },
          { id: 'eco-text', type: BlockType.TEXT, order: 2, visible: true, config: { content: '<h2 style="text-align:center;color:#4A7C59">Sustentabilidade não é tendência, é necessidade</h2><p style="text-align:center;color:#2D3B2D">Cada imóvel em nossa seleção é projetado com responsabilidade ambiental, oferecendo conforto sem comprometer o futuro.</p>', fontSize: 17, fontWeight: 400, color: '#2D3B2D', alignment: 'center' }, styles: { padding: '40px 20px 60px' } },
          { id: 'eco-grid', type: BlockType.PROPERTY_GRID, order: 3, visible: true, config: { columns: 3, gap: 24, showFilters: false, maxItems: 6, sortBy: 'date', cardStyle: 'modern' }, styles: { padding: '0px 20px 60px' } },
          { id: 'eco-carousel', type: BlockType.PROPERTY_CAROUSEL, order: 4, visible: true, config: { autoplay: true, interval: 5000, showArrows: true, showDots: true, itemsPerView: 3 }, styles: { padding: '0px 20px 60px' } },
          { id: 'eco-stats', type: BlockType.STATS, order: 5, visible: true, config: { stats: [{ value: '150+', label: 'Imóveis Sustentáveis', icon: '🏡' }, { value: '-40%', label: 'CO₂', icon: '🌍' }, { value: '+200', label: 'Árvores Plantadas', icon: '🌳' }, { value: '100%', label: 'Energia Renovável', icon: '☀️' }], columns: 4, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#4A7C59' } },
          { id: 'eco-timeline', type: BlockType.TIMELINE, order: 6, visible: true, config: { title: 'Jornada Sustentável', items: [{ title: '2018', description: 'Primeiro imóvel verde' }, { title: '2020', description: 'Certificação ambiental' }, { title: '2022', description: '100 imóveis solares' }, { title: '2024', description: 'Meta: carbono neutro' }] }, styles: { padding: '60px 20px', backgroundColor: '#F5F7F0' } },
          { id: 'eco-testimonials', type: BlockType.TESTIMONIALS, order: 7, visible: true, config: { testimonials: [{ name: 'Ana Verde', rating: 5, text: 'Finalmente um imóvel que combina com meus valores. Sustentável e confortável.' }, { name: 'Lucas Eco', rating: 5, text: 'Economia na conta de luz e consciência tranquila. Recomendo!' }], layout: 'grid', showRating: true }, styles: { padding: '60px 20px' } },
          { id: 'eco-cta', type: BlockType.CTA, order: 8, visible: true, config: { title: 'Faça Parte da Mudança', description: 'Escolha um imóvel que cuida do planeta', buttonText: 'Começar Agora', buttonLink: '#contato', backgroundColor: '#4A7C59', textColor: '#ffffff' }, styles: { padding: '80px 20px' } },
          { id: 'eco-broker', type: BlockType.BROKER_CARD, order: 9, visible: true, config: { name: 'Isabela Campos', photoUrl: '', creci: '33333-J', specialty: 'Imóveis Sustentáveis', phone: '(11) 95555-0000', email: 'isabela@imobzy.com', description: 'Especialista em construções sustentáveis e certificações ambientais.' }, styles: { padding: '60px 20px', backgroundColor: '#F5F7F0' } },
          { id: 'eco-footer', type: BlockType.FOOTER, order: 10, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#4A7C59' } },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          { id: 'eco-imp-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Imóveis Sustentáveis', subtitle: 'Construções que respeitam o meio ambiente', backgroundImage: IMG.eco2, overlayOpacity: 0.3, height: 400, alignment: 'center', textColor: '#F5F7F0' }, styles: { padding: '0px' } },
          { id: 'eco-imp-grid', type: BlockType.PROPERTY_GRID, order: 1, visible: true, config: { columns: 3, gap: 24, showFilters: true, maxItems: 30, sortBy: 'date', cardStyle: 'modern' }, styles: { padding: '60px 20px' } },
          { id: 'eco-imp-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#4A7C59' } },
        ],
      },
      {
        title: 'Sustentabilidade',
        slug: 'sustentabilidade',
        isHome: false,
        blocks: [
          { id: 'eco-sus-hero', type: BlockType.HERO, order: 0, visible: true, config: { title: 'Nosso Compromisso Verde', subtitle: 'Construindo o futuro com responsabilidade', backgroundImage: IMG.eco, overlayOpacity: 0.3, height: 400, alignment: 'center', textColor: '#F5F7F0' }, styles: { padding: '0px' } },
          { id: 'eco-sus-features', type: BlockType.FEATURES, order: 1, visible: true, config: { features: [{ title: 'Certificação LEED', description: 'Padrão internacional de sustentabilidade', icon: '🏅' }, { title: 'Eficiência Energética', description: 'A+ em classificação energética', icon: '⚡' }, { title: 'Gestão de Resíduos', description: 'Reciclagem e reuso no canteiro', icon: '♻️' }, { title: 'Biodiversidade', description: 'Preservação da fauna e flora', icon: '🦋' }, { title: 'Água', description: 'Redução de 60% no consumo', icon: '💧' }, { title: 'Certificação Solar', description: 'Todos com energia solar', icon: '☀️' }], columns: 3 }, styles: { padding: '60px 20px' } },
          { id: 'eco-sus-timeline', type: BlockType.TIMELINE, order: 2, visible: true, config: { title: 'Nossos Marcos Verdes', items: [{ title: '2018', description: 'Primeiro imóvel sustentável' }, { title: '2020', description: 'Certificação ambiental' }, { title: '2022', description: '100 imóveis solares' }, { title: '2024', description: 'Meta carbono neutro' }] }, styles: { padding: '60px 20px', backgroundColor: '#F5F7F0' } },
          { id: 'eco-sus-stats', type: BlockType.STATS, order: 3, visible: true, config: { stats: [{ value: '-40%', label: 'Emissão CO₂', icon: '🌍' }, { value: '60%', label: 'Economia Água', icon: '💧' }, { value: '100%', label: 'Solar', icon: '☀️' }, { value: '+200', label: 'Árvores', icon: '🌳' }], columns: 4, animated: true }, styles: { padding: '60px 20px', backgroundColor: '#4A7C59' } },
          { id: 'eco-sus-gallery', type: BlockType.GALLERY, order: 4, visible: true, config: { images: [{ src: IMG.eco, alt: 'Área verde' }, { src: IMG.eco2, alt: 'Painéis solares' }, { src: IMG.rural, alt: 'Paisagem' }], columns: 3, gap: 16, lightbox: true }, styles: { padding: '60px 20px' } },
          { id: 'eco-sus-footer', type: BlockType.FOOTER, order: 5, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#4A7C59' } },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          { id: 'eco-con-hero', type: BlockType.HERO_WITH_FORM, order: 0, visible: true, config: { title: 'Construa o Futuro Sustentável', subtitle: 'Fale com nossos especialistas em imóveis verdes', backgroundImage: IMG.eco2, overlayOpacity: 0.3, formTitle: 'Entre em Contato', formSubtitle: 'Comece sua jornada verde', submitText: 'Enviar', height: 550, textColor: '#F5F7F0', showBadges: true, badges: [{ icon: 'leaf', title: 'Sustentável', description: 'Imóveis certificados' }, { icon: 'shield', title: 'Garantia', description: 'Qualidade assegurada' }, { icon: 'star', title: 'Especialista', description: 'Consultoria verde' }] }, styles: { padding: '0px' } },
          { id: 'eco-con-broker', type: BlockType.BROKER_CARD, order: 1, visible: true, config: { name: 'Isabela Campos', photoUrl: '', creci: '33333-J', specialty: 'Imóveis Sustentáveis', phone: '(11) 95555-0000', email: 'isabela@imobzy.com', description: 'Especialista em construções sustentáveis.' }, styles: { padding: '60px 20px', backgroundColor: '#F5F7F0' } },
          { id: 'eco-con-footer', type: BlockType.FOOTER, order: 2, visible: true, config: {}, styles: { padding: '40px 20px', backgroundColor: '#4A7C59' } },
        ],
      },
    ],
  },
];

export const getSiteTemplateById = (id: string): SiteTemplate | undefined => {
  return SITE_TEMPLATES.find((t) => t.id === id);
};

export const applySiteTemplate = (template: SiteTemplate, orgName: string) => {
  const theme = {
    ...template.globalTheme,
  };

  const pages = template.pages.map((page, pIdx) => ({
    title: page.title,
    slug: page.slug,
    sortOrder: pIdx,
    blocks: page.blocks.map((block, bIdx) => ({
      ...block,
      id: `${page.slug}-${block.type}-${bIdx}-${Date.now()}`,
      order: bIdx,
    })),
    themeOverrides: {},
    status: 'published' as const,
    isHome: page.isHome,
    metaTitle: `${page.title} | ${orgName}`,
  }));

  return {
    name: `Site - ${orgName}`,
    globalTheme: theme,
    menuConfig: template.menuConfig,
    pages,
  };
};
