import { BlockType, LandingPageStatus } from '../types/landingPage';
import { SiteTemplate } from '../types/site';

const defaultTheme = {
  primaryColor: '#1e40af',
  secondaryColor: '#0d9488',
  backgroundColor: '#ffffff',
  textColor: '#1e293b',
  fontFamily: 'Inter, sans-serif',
  headingFontFamily: 'Inter, sans-serif',
  fontSize: { base: '1rem', heading1: '3rem', heading2: '2rem', heading3: '1.5rem' },
  borderRadius: '0.75rem',
  spacing: { xs: '0.5rem', sm: '1rem', md: '1.5rem', lg: '2rem', xl: '4rem' },
};

export const SITE_TEMPLATES: SiteTemplate[] = [
  {
    id: 'site-moderno-imobiliario',
    name: 'Imobiliária Moderna',
    description: 'Template clean e moderno para imobiliárias com destaque para propriedades',
    thumbnail: '/templates/site-moderno.png',
    category: 'universal',
    globalTheme: {
      ...defaultTheme,
      primaryColor: '#2563eb',
      secondaryColor: '#059669',
    },
    menuConfig: [
      { id: 'm1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'm2', label: 'Imóveis', type: 'page', pageId: 'imoveis', order: 1 },
      { id: 'm3', label: 'Sobre', type: 'page', pageId: 'sobre', order: 2 },
      { id: 'm4', label: 'Serviços', type: 'page', pageId: 'servicos', order: 3 },
      { id: 'm5', label: 'Contato', type: 'page', pageId: 'contato', order: 4 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          {
            id: 'home-hero',
            type: BlockType.HERO,
            order: 0,
            visible: true,
            config: {
              title: 'Encontre o Imóvel dos Seus Sonhos',
              subtitle: 'Soluções completas em compra, venda e aluguel de imóveis rurais e urbanos',
              backgroundImage: '',
              overlayOpacity: 0.4,
              ctaText: 'Ver Imóveis Disponíveis',
              ctaLink: '#imoveis',
              height: 600,
              alignment: 'center',
              textColor: '#ffffff',
            },
            styles: { padding: '0px' },
          },
          {
            id: 'home-stats',
            type: BlockType.STATS,
            order: 1,
            visible: true,
            config: {
              stats: [
                { value: '500+', label: 'Imóveis Comercializados', icon: '🏡' },
                { value: '300+', label: 'Clientes Satisfeitos', icon: '👥' },
                { value: '15', label: 'Anos de Experiência', icon: '⭐' },
                { value: '50+', label: 'Parceiros', icon: '🤝' },
              ],
              columns: 4,
              animated: true,
            },
            styles: { padding: '60px 20px', backgroundColor: '#f8fafc' },
          },
          {
            id: 'home-featured',
            type: BlockType.PROPERTY_GRID,
            order: 2,
            visible: true,
            config: {
              columns: 3,
              gap: 24,
              showFilters: false,
              maxItems: 6,
              sortBy: 'date',
              cardStyle: 'modern',
            },
            styles: { padding: '80px 20px' },
          },
          {
            id: 'home-cta',
            type: BlockType.CTA,
            order: 3,
            visible: true,
            config: {
              title: 'Pronto para Encontrar seu Imóvel Ideal?',
              description: 'Nossa equipe está preparada para te ajudar em cada etapa do processo',
              buttonText: 'Fale Conosco',
              buttonLink: '#contato',
              backgroundColor: '#2563eb',
              textColor: '#ffffff',
            },
            styles: { padding: '80px 20px' },
          },
        ],
      },
      {
        title: 'Imóveis',
        slug: 'imoveis',
        isHome: false,
        blocks: [
          {
            id: 'prop-hero',
            type: BlockType.PROPERTY_SEARCH,
            order: 0,
            visible: true,
            config: {
              showFilters: true,
              resultsPerPage: 12,
            } as any,
            styles: { padding: '40px 20px' },
          },
          {
            id: 'prop-grid',
            type: BlockType.PROPERTY_GRID,
            order: 1,
            visible: true,
            config: {
              columns: 3,
              gap: 24,
              showFilters: true,
              maxItems: 24,
              sortBy: 'price',
              cardStyle: 'modern',
            },
            styles: { padding: '40px 20px' },
          },
        ],
      },
      {
        title: 'Sobre',
        slug: 'sobre',
        isHome: false,
        blocks: [
          {
            id: 'about-hero',
            type: BlockType.HERO,
            order: 0,
            visible: true,
            config: {
              title: 'Nossa História',
              subtitle: 'Há mais de 15 anos transformando sonhos em realidade no mercado imobiliário',
              backgroundImage: '',
              overlayOpacity: 0.4,
              ctaText: 'Conheça Nossa Equipe',
              height: 450,
              alignment: 'center',
              textColor: '#ffffff',
            },
            styles: { padding: '0px' },
          },
          {
            id: 'about-text',
            type: BlockType.TEXT,
            order: 1,
            visible: true,
            config: {
              content: '<h2>Quem Somos</h2><p>Somos uma imobiliária com vasta experiência no mercado, especializada em imóveis rurais e urbanos. Nosso compromisso é oferecer o melhor atendimento, transparência e segurança em cada negociação.</p><p>Contamos com uma equipe altamente capacitada e utilizamos tecnologia de ponta para proporcionar a melhor experiência aos nossos clientes.</p>',
              fontSize: 16,
              fontWeight: 400,
              color: '#1e293b',
              alignment: 'left',
            },
            styles: { padding: '60px 20px' },
          },
          {
            id: 'about-testimonials',
            type: BlockType.TESTIMONIALS,
            order: 2,
            visible: true,
            config: {
              testimonials: [
                { name: 'João Silva', photo: '', rating: 5, text: 'Excelente atendimento! Encontrei a fazenda perfeita para minha família.' },
                { name: 'Maria Santos', photo: '', rating: 5, text: 'Profissionais sérios e comprometidos. Recomendo de olhos fechados.' },
                { name: 'Pedro Oliveira', photo: '', rating: 5, text: 'Agilidade e transparência em todo o processo. Muito satisfeito!' },
              ],
              layout: 'carousel',
              showRating: true,
            },
            styles: { padding: '60px 20px', backgroundColor: '#f8fafc' },
          },
        ],
      },
      {
        title: 'Serviços',
        slug: 'servicos',
        isHome: false,
        blocks: [
          {
            id: 'serv-hero',
            type: BlockType.HERO,
            order: 0,
            visible: true,
            config: {
              title: 'Nossos Serviços',
              subtitle: 'Soluções completas para quem busca o melhor em negócios imobiliários',
              backgroundImage: '',
              overlayOpacity: 0.4,
              height: 400,
              alignment: 'center',
              textColor: '#ffffff',
            },
            styles: { padding: '0px' },
          },
          {
            id: 'serv-features',
            type: BlockType.FEATURES,
            order: 1,
            visible: true,
            config: {
              features: [
                { title: 'Compra e Venda', description: 'Assessoria completa na compra e venda de imóveis rurais e urbanos', icon: '🤝' },
                { title: 'Avaliação Técnica', description: 'Avaliação detalhada com análise de mercado e potencial do imóvel', icon: '📋' },
                { title: 'Due Diligence', description: 'Análise jurídica e documental completa para sua segurança', icon: '🔍' },
                { title: 'Financiamento', description: 'Suporte na obtenção de crédito e financiamento imobiliário', icon: '💰' },
                { title: 'Regularização', description: 'Assessoria na regularização ambiental e documental de imóveis', icon: '📄' },
                { title: 'Consultoria', description: 'Consultoria especializada para investimentos imobiliários', icon: '📊' },
              ],
              columns: 3,
            },
            styles: { padding: '80px 20px' },
          },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          {
            id: 'cont-hero',
            type: BlockType.HERO,
            order: 0,
            visible: true,
            config: {
              title: 'Entre em Contato',
              subtitle: 'Estamos prontos para atender você',
              backgroundImage: '',
              overlayOpacity: 0.4,
              height: 350,
              alignment: 'center',
              textColor: '#ffffff',
            },
            styles: { padding: '0px' },
          },
          {
            id: 'cont-form',
            type: BlockType.FORM,
            order: 1,
            visible: true,
            config: {
              title: 'Envie sua Mensagem',
              fields: [
                { name: 'name', type: 'text', label: 'Nome', required: true, placeholder: 'Seu nome' },
                { name: 'email', type: 'email', label: 'E-mail', required: true, placeholder: 'seu@email.com' },
                { name: 'phone', type: 'tel', label: 'Telefone', required: true, placeholder: '(00) 00000-0000' },
                { name: 'message', type: 'textarea', label: 'Mensagem', required: false, placeholder: 'Sua mensagem' },
              ],
              submitText: 'Enviar Mensagem',
              successMessage: 'Mensagem enviada com sucesso! Entraremos em contato.',
            },
            styles: { padding: '60px 20px' },
          },
          {
            id: 'cont-map',
            type: BlockType.MAP,
            order: 2,
            visible: true,
            config: {
              latitude: -23.5505,
              longitude: -46.6333,
              zoom: 14,
              markers: [],
            },
            styles: { padding: '0px', height: '400px' },
          },
        ],
      },
    ],
  },
  {
    id: 'site-rural-negocios',
    name: 'Agronegócio & Fazendas',
    description: 'Template especializado para imobiliárias rurais com foco em fazendas e investimento',
    thumbnail: '/templates/site-rural.png',
    category: 'rural',
    globalTheme: {
      ...defaultTheme,
      primaryColor: '#05542C',
      secondaryColor: '#d4af37',
    },
    menuConfig: [
      { id: 'r1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'r2', label: 'Fazendas', type: 'page', pageId: 'fazendas', order: 1 },
      { id: 'r3', label: 'Sobre', type: 'page', pageId: 'sobre', order: 2 },
      { id: 'r4', label: 'Contato', type: 'page', pageId: 'contato', order: 3 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          {
            id: 'rural-hero',
            type: BlockType.HERO_WITH_FORM,
            order: 0,
            visible: true,
            config: {
              title: 'Oportunidades em Imóveis Rurais',
              subtitle: 'Fazendas, sítios e áreas de investimento com alto potencial de valorização',
              backgroundImage: '',
              overlayOpacity: 0.3,
              formTitle: 'Receba Ofertas Exclusivas',
              formSubtitle: 'Cadastre-se para receber as melhores oportunidades',
              submitText: 'Quero Receber',
              height: 650,
              textColor: '#ffffff',
              showBadges: true,
              badges: [
                { icon: 'shield', title: 'Documentação 100%', description: 'Imóveis com documentação regularizada' },
                { icon: 'star', title: 'Ofertas Exclusivas', description: 'Propriedades selecionadas' },
                { icon: 'clock', title: 'Primeiro a Saber', description: 'Novidades antes de todos' },
              ],
            },
            styles: { padding: '0px' },
          },
          {
            id: 'rural-grid',
            type: BlockType.PROPERTY_GRID,
            order: 1,
            visible: true,
            config: {
              columns: 3,
              gap: 24,
              showFilters: true,
              maxItems: 9,
              sortBy: 'price',
              cardStyle: 'modern',
            },
            styles: { padding: '80px 20px' },
          },
        ],
      },
      {
        title: 'Fazendas',
        slug: 'fazendas',
        isHome: false,
        blocks: [
          {
            id: 'faz-hero',
            type: BlockType.HERO,
            order: 0,
            visible: true,
            config: {
              title: 'Fazendas à Venda',
              subtitle: 'As melhores propriedades rurais do Brasil',
              backgroundImage: '',
              overlayOpacity: 0.4,
              ctaText: 'Filtrar por Região',
              height: 400,
              alignment: 'center',
              textColor: '#ffffff',
            },
            styles: { padding: '0px' },
          },
          {
            id: 'faz-grid',
            type: BlockType.PROPERTY_GRID,
            order: 1,
            visible: true,
            config: {
              columns: 3,
              gap: 24,
              showFilters: true,
              maxItems: 30,
              sortBy: 'price',
              cardStyle: 'modern',
            },
            styles: { padding: '60px 20px' },
          },
          {
            id: 'faz-cta',
            type: BlockType.CTA,
            order: 2,
            visible: true,
            config: {
              title: 'Quer Anunciar sua Propriedade?',
              description: 'Temos a melhor plataforma para divulgar seu imóvel rural',
              buttonText: 'Anunciar Agora',
              buttonLink: '#contato',
              backgroundColor: '#05542C',
              textColor: '#ffffff',
            },
            styles: { padding: '60px 20px' },
          },
        ],
      },
      {
        title: 'Sobre',
        slug: 'sobre',
        isHome: false,
        blocks: [
          {
            id: 'rural-about-hero',
            type: BlockType.HERO,
            order: 0,
            visible: true,
            config: {
              title: 'Especialistas em Agronegócio',
              subtitle: 'Conhecimento profundo do mercado rural brasileiro',
              backgroundImage: '',
              overlayOpacity: 0.4,
              height: 400,
              alignment: 'center',
              textColor: '#ffffff',
            },
            styles: { padding: '0px' },
          },
          {
            id: 'rural-about-text',
            type: BlockType.TEXT,
            order: 1,
            visible: true,
            config: {
              content: '<h2>Por que escolher a gente?</h2><p>Somos referência no mercado de imóveis rurais, com profundo conhecimento das regiões agrícolas do Brasil. Nossa equipe é formada por especialistas em agronegócio, direito ambiental e avaliação de propriedades rurais.</p><p>Utilizamos tecnologia de ponta, incluindo imagens de satélite e análises geoespaciais, para oferecer as melhores oportunidades do mercado.</p>',
              fontSize: 16,
              fontWeight: 400,
              color: '#1e293b',
              alignment: 'left',
            },
            styles: { padding: '60px 20px' },
          },
          {
            id: 'rural-about-stats',
            type: BlockType.STATS,
            order: 2,
            visible: true,
            config: {
              stats: [
                { value: '200+', label: 'Fazendas Vendidas', icon: '🏡' },
                { value: '50k+', label: 'Hectares Comercializados', icon: '🌳' },
                { value: '12', label: 'Anos de Mercado', icon: '⭐' },
                { value: '20', label: 'Estados Atendidos', icon: '🗺️' },
              ],
              columns: 4,
              animated: true,
            },
            styles: { padding: '60px 20px', backgroundColor: '#f0fdf4' },
          },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          {
            id: 'rural-contato-form',
            type: BlockType.FORM,
            order: 0,
            visible: true,
            config: {
              title: 'Fale com um Especialista',
              fields: [
                { name: 'name', type: 'text', label: 'Nome', required: true, placeholder: 'Seu nome' },
                { name: 'email', type: 'email', label: 'E-mail', required: true, placeholder: 'seu@email.com' },
                { name: 'phone', type: 'tel', label: 'WhatsApp', required: true, placeholder: '(00) 00000-0000' },
                { name: 'interest', type: 'select', label: 'Tipo de Imóvel', required: true, placeholder: '', options: ['Fazenda', 'Sítio', 'Chácara', 'Área Rural', 'Investimento'] },
                { name: 'message', type: 'textarea', label: 'Mensagem', required: false, placeholder: 'Conte-nos sobre o que procura...' },
              ],
              submitText: 'Enviar Mensagem',
              successMessage: 'Recebemos sua mensagem! Entraremos em contato em breve.',
            },
            styles: { padding: '80px 20px' },
          },
        ],
      },
    ],
  },
  {
    id: 'site-minimal-urbano',
    name: 'Urbano Minimalista',
    description: 'Design limpo e minimalista focado em imóveis urbanos e apartamentos',
    thumbnail: '/templates/site-urbano.png',
    category: 'urban',
    globalTheme: {
      ...defaultTheme,
      primaryColor: '#1e293b',
      secondaryColor: '#6366f1',
    },
    menuConfig: [
      { id: 'u1', label: 'Início', type: 'page', pageId: 'home', order: 0 },
      { id: 'u2', label: 'Lançamentos', type: 'page', pageId: 'lancamentos', order: 1 },
      { id: 'u3', label: 'Contato', type: 'page', pageId: 'contato', order: 2 },
    ],
    pages: [
      {
        title: 'Início',
        slug: 'home',
        isHome: true,
        blocks: [
          {
            id: 'urb-hero',
            type: BlockType.HERO,
            order: 0,
            visible: true,
            config: {
              title: 'Seu Novo Lar Começa Aqui',
              subtitle: 'Apartamentos, casas e imóveis comerciais nas melhores regiões da cidade',
              backgroundImage: '',
              overlayOpacity: 0.35,
              ctaText: 'Explorar Imóveis',
              ctaLink: '#imoveis',
              height: 550,
              alignment: 'center',
              textColor: '#ffffff',
            },
            styles: { padding: '0px' },
          },
          {
            id: 'urb-grid',
            type: BlockType.PROPERTY_CAROUSEL,
            order: 1,
            visible: true,
            config: {
              columns: 3,
              gap: 16,
              showFilters: false,
              maxItems: 10,
              sortBy: 'date',
              cardStyle: 'modern',
              autoplay: true,
              interval: 4000,
            },
            styles: { padding: '80px 20px' },
          },
          {
            id: 'urb-features',
            type: BlockType.FEATURES,
            order: 2,
            visible: true,
            config: {
              features: [
                { title: 'Imóveis Verificados', description: 'Todos os imóveis passam por rigorosa verificação', icon: '✅' },
                { title: 'Melhores Preços', description: 'Garantimos as melhores condições do mercado', icon: '💰' },
                { title: 'Assessoria Completa', description: 'Acompanhamento em todas as etapas', icon: '🤝' },
              ],
              columns: 3,
            },
            styles: { padding: '60px 20px', backgroundColor: '#f8fafc' },
          },
        ],
      },
      {
        title: 'Lançamentos',
        slug: 'lancamentos',
        isHome: false,
        blocks: [
          {
            id: 'lanc-hero',
            type: BlockType.HERO,
            order: 0,
            visible: true,
            config: {
              title: 'Lançamentos Exclusivos',
              subtitle: 'Conheça os empreendimentos mais recentes do mercado',
              backgroundImage: '',
              overlayOpacity: 0.4,
              height: 350,
              alignment: 'center',
              textColor: '#ffffff',
            },
            styles: { padding: '0px' },
          },
          {
            id: 'lanc-grid',
            type: BlockType.PROPERTY_GRID,
            order: 1,
            visible: true,
            config: {
              columns: 2,
              gap: 24,
              showFilters: true,
              maxItems: 8,
              sortBy: 'date',
              cardStyle: 'modern',
            },
            styles: { padding: '60px 20px' },
          },
        ],
      },
      {
        title: 'Contato',
        slug: 'contato',
        isHome: false,
        blocks: [
          {
            id: 'urb-contato',
            type: BlockType.FORM,
            order: 0,
            visible: true,
            config: {
              title: 'Agende uma Visita',
              fields: [
                { name: 'name', type: 'text', label: 'Nome', required: true, placeholder: 'Seu nome' },
                { name: 'email', type: 'email', label: 'E-mail', required: true, placeholder: 'seu@email.com' },
                { name: 'phone', type: 'tel', label: 'Telefone', required: true, placeholder: '(00) 00000-0000' },
                { name: 'message', type: 'textarea', label: 'Mensagem', required: false, placeholder: 'Qual imóvel te interessou?' },
              ],
              submitText: 'Agendar Visita',
              successMessage: 'Recebemos seu pedido! Entraremos em contato para agendar.',
            },
            styles: { padding: '80px 20px' },
          },
        ],
      },
    ],
  },
];

export const getSiteTemplateById = (id: string): SiteTemplate | undefined => {
  return SITE_TEMPLATES.find((t) => t.id === id);
};

export const applySiteTemplate = (template: SiteTemplate, orgName: string) => {
  const theme = {
    ...template.globalTheme,
  };

  const pages = template.pages.map((page, pIdx) => ({
    title: page.title,
    slug: page.slug,
    sortOrder: pIdx,
    blocks: page.blocks.map((block, bIdx) => ({
      ...block,
      id: `${page.slug}-${block.type}-${bIdx}-${Date.now()}`,
      order: bIdx,
    })),
    themeOverrides: {},
    status: 'published' as const,
    isHome: page.isHome,
    metaTitle: `${page.title} | ${orgName}`,
  }));

  return {
    name: `Site - ${orgName}`,
    globalTheme: theme,
    menuConfig: template.menuConfig,
    pages,
  };
};
