ALTER TABLE public.properties
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS neighborhood TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS purpose TEXT DEFAULT 'Venda',
  ADD COLUMN IF NOT EXISTS property_type TEXT DEFAULT 'Casa',
  ADD COLUMN IF NOT EXISTS niche TEXT DEFAULT 'urbano',
  ADD COLUMN IF NOT EXISTS features JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS images TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS highlighted BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS owner_info JSONB,
  ADD COLUMN IF NOT EXISTS total_area_ha NUMERIC(15,2),
  ADD COLUMN IF NOT EXISTS useful_area_ha NUMERIC(15,2),
  ADD COLUMN IF NOT EXISTS price_per_ha NUMERIC(20,2),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

NOTIFY pgrst, 'reload schema';
