import {
  LandingPageTemplate,
  buildDesignedTemplate,
  landingImage,
  designedSections,
} from './shared';
export const DESIGNED_SHOWCASE_TEMPLATES: LandingPageTemplate[] = [
  buildDesignedTemplate({
    id: 'showcase-corretor-premium',
    name: 'Corretor Premium Imobiliario',
    description:
      'Modelo institucional como site de corretor premium, com autoridade, imoveis em destaque, avaliacao e captacao.',
    thumbnail: landingImage.mansion,
    group: 'Institucional',
    category: 'Corretor premium',
    objective: 'Falar com corretor',
    style: 'Luxo',
    resources: [
      'WhatsApp',
      'Avaliacao',
      'Imoveis em destaque',
      'Instagram',
      'Formulario',
      'CRM',
    ],
    pipeline: 'Pipeline Venda Urbana',
    crmTags: ['Lead Institucional', 'Avaliacao de Imovel'],
    conversionEvent: 'lead_corretor_premium',
    palette: {
      primary: '#06382f',
      secondary: '#0b241f',
      accent: '#c9a24f',
      background: '#fffaf2',
      text: '#182129',
      footer: '#071819',
    },
    logo: 'Seu Nome Imoveis',
    nav: ['Inicio', 'Sobre', 'Imoveis', 'Servicos', 'Depoimentos', 'Contato'],
    badge: 'Confianca. Experiencia. Resultados.',
    headline: 'Realizo o seu melhor negocio',
    highlight: 'imobiliario.',
    subtitle:
      'Especialista em conectar pessoas a imoveis e oportunidades que valorizam patrimonio e realizam sonhos.',
    price: '+300 imoveis negociados',
    location: 'Sao Jose dos Campos - SP',
    primaryCta: 'Ver imoveis a venda',
    secondaryCta: 'Avaliacao gratuita',
    heroImage: landingImage.mansion,
    stats: [
      { label: 'Anos de experiencia', value: '+8', icon: '­ƒÅå' },
      { label: 'Imoveis negociados', value: '+300', icon: '­ƒÅí' },
      { label: 'Atendimento humanizado', value: '100%', icon: '­ƒñØ' },
      { label: 'Negociacao segura', value: 'CRECI', icon: '­ƒöæ' },
    ],
    features: [
      {
        title: 'Residenciais',
        text: 'Casas, apartamentos e condominios para morar com conforto.',
        icon: '­ƒÅá',
      },
      {
        title: 'Comerciais',
        text: 'Salas, lojas e galpoes para negocios crescerem.',
        icon: '­ƒÅó',
      },
      {
        title: 'Terrenos e lotes',
        text: 'Oportunidades para investir e construir.',
        icon: '­ƒù║´©Å',
      },
      {
        title: 'Investimentos',
        text: 'Imoveis com alto potencial de renda.',
        icon: '­ƒôê',
      },
      {
        title: 'Aluguel',
        text: 'Opcoes selecionadas para locacao.',
        icon: '­ƒöæ',
      },
    ],
    cards: [
      {
        title: 'Casa em Condominio',
        meta: '4 suites ÔÇó Alphaville',
        price: 'R$ 1.580.000',
        image: landingImage.mansion,
      },
      {
        title: 'Apartamento Alto Padrao',
        meta: '3 quartos ÔÇó Vila Ema',
        price: 'R$ 950.000',
        image: landingImage.interior,
      },
      {
        title: 'Sala Comercial',
        meta: '45 m2 ÔÇó Jardim Aquarius',
        price: 'R$ 420.000',
        image: landingImage.warehouse,
      },
      {
        title: 'Terreno em Condominio',
        meta: '450 m2 ÔÇó Urbanova',
        price: 'R$ 680.000',
        image: landingImage.lots,
      },
    ],
    sections: designedSections,
    formTitle: 'Fale comigo',
    formSubtitle: 'Preencha o formulario que retorno rapidinho.',
    faq: [
      'Como funciona a avaliacao do meu imovel?',
      'Quais documentos sao necessarios?',
      'Voc├¬s atendem outras regioes?',
      'Como e feita a divulgacao?',
    ],
  }),
  buildDesignedTemplate({
    id: 'showcase-galpao-logistico',
    name: 'Galpao Logistico Premium',
    description:
      'Modelo corporativo para galpao, docas, patio, pe-direito, mapa logistico e visita tecnica.',
    thumbnail: landingImage.warehouse,
    group: 'Urbana',
    category: 'Galpao',
    objective: 'Alugar imovel',
    style: 'Corporativo',
    resources: [
      'Ficha tecnica',
      'Mapa logistico',
      'Agenda tecnica',
      'Formulario empresarial',
      'WhatsApp',
      'CRM',
    ],
    pipeline: 'Pipeline Aluguel',
    crmTags: ['Lead Comercial', 'Galpao'],
    conversionEvent: 'lead_galpao_logistico',
    palette: {
      primary: '#06152b',
      secondary: '#0d2340',
      accent: '#ff6b00',
      background: '#f7f9fc',
      text: '#101827',
      footer: '#06152b',
    },
    logo: 'Nova Corporativos',
    nav: ['Imoveis', 'Solucoes', 'Sobre nos', 'Clientes', 'Contato'],
    badge: 'Imovel comercial / Galpao',
    headline: 'Galpao Logistico Premium em',
    highlight: 'Localizacao Estrategica',
    subtitle:
      'Estrutura moderna, seguranca e eficiencia para impulsionar a sua operacao.',
    price: 'R$ 168.000 /mes',
    location: 'Rodovia Anhanguera, km 72 - Cajamar/SP',
    primaryCta: 'Agendar visita',
    secondaryCta: 'Fale com especialista',
    heroImage: landingImage.warehouse,
    stats: [
      { label: 'Area construida', value: '12.500 m2', icon: '­ƒÅ¡' },
      { label: 'Area de terreno', value: '20.000 m2', icon: '­ƒôì' },
      { label: 'Pe-direito livre', value: '12 m', icon: 'Ôåò´©Å' },
      { label: 'Docas elevadas', value: '16', icon: '­ƒÜÜ' },
      { label: 'Piso industrial', value: '6 t/m2', icon: '­ƒôª' },
      { label: 'Energia trifasica', value: '750 KVA', icon: 'ÔÜí' },
    ],
    features: [
      {
        title: 'Acesso rapido',
        text: 'Conexao direta com as principais rodovias.',
        icon: '­ƒÜø',
      },
      {
        title: 'Mao de obra',
        text: 'Regiao com oferta de profissionais.',
        icon: '­ƒôì',
      },
      { title: 'Seguranca', text: 'Portaria e controle 24h.', icon: '­ƒøí´©Å' },
      {
        title: 'Infraestrutura',
        text: 'Servicos essenciais proximos.',
        icon: '­ƒÅù´©Å',
      },
      {
        title: 'Expansao',
        text: 'Layout preparado para crescer.',
        icon: '­ƒôê',
      },
    ],
    cards: [
      {
        title: 'Area interna',
        meta: 'Piso industrial e iluminacao LED',
        image: landingImage.warehouseInside,
      },
      {
        title: 'Docas elevadas',
        meta: 'Operacao logistica eficiente',
        image: landingImage.warehouse,
      },
      {
        title: 'Patio de manobra',
        meta: 'Amplo acesso para caminhoes',
        image: landingImage.lots,
      },
      {
        title: 'Equipe tecnica',
        meta: 'Visita acompanhada por especialista',
        image: landingImage.broker,
      },
    ],
    sections: designedSections,
    formTitle: 'Receba mais informacoes',
    formSubtitle: 'Informe sua empresa e nossa equipe entra em contato.',
    faq: [
      'O imovel esta disponivel para venda ou locacao?',
      'Qual o prazo minimo de locacao?',
      'O condominio esta incluso?',
      'Pode adaptar o layout?',
    ],
  }),
  buildDesignedTemplate({
    id: 'showcase-casa-aluguel-tour',
    name: 'Casa para Aluguel com Tour 360',
    description:
      'Modelo de aluguel com tour virtual, garantias aceitas, pet friendly, agenda e contato do corretor.',
    thumbnail: landingImage.house,
    group: 'Aluguel',
    category: 'Casa para aluguel',
    objective: 'Agendar visita',
    style: 'Moderno',
    resources: [
      'Tour 360',
      'Agenda presencial',
      'Agenda por video',
      'Garantias',
      'WhatsApp',
      'CRM',
    ],
    pipeline: 'Pipeline Aluguel',
    crmTags: ['Lead Aluguel', 'Abriu Tour Virtual'],
    conversionEvent: 'lead_aluguel_tour',
    palette: {
      primary: '#06152b',
      secondary: '#f8f5ee',
      accent: '#c6923e',
      background: '#ffffff',
      text: '#111827',
      footer: '#07152b',
    },
    logo: 'Villaggio Imoveis',
    nav: ['Inicio', 'Imovel', 'Fotos', 'Localizacao', 'Condicoes', 'Contato'],
    badge: 'Para alugar',
    headline: 'Casa Terrea Moderna',
    highlight: 'para Aluguel',
    subtitle:
      'Tour 360, fotos completas, regras de locacao e visita agendada para conhecer seu proximo lar.',
    price: 'R$ 3.750 /mes',
    location: 'Jardim das Flores, Campinas - SP',
    primaryCta: 'Agendar visita',
    secondaryCta: 'Falar no WhatsApp',
    heroImage: landingImage.house,
    stats: [
      { label: 'Quartos', value: '3', icon: '­ƒøÅ´©Å' },
      { label: 'Banheiros', value: '2', icon: '­ƒøü' },
      { label: 'Area construida', value: '120 m2', icon: '­ƒôÉ' },
      { label: 'Vagas cobertas', value: '2', icon: '­ƒÜù' },
    ],
    features: [
      {
        title: 'Tour virtual',
        text: 'Explore cada ambiente sem sair de casa.',
        icon: '360',
      },
      {
        title: 'Pet friendly',
        text: 'Aceita animais de pequeno e medio porte.',
        icon: '­ƒÉ¥',
      },
      {
        title: 'Garantias',
        text: 'Fianca, fiador e capitalizacao.',
        icon: 'Ô£à',
      },
      {
        title: 'Agenda online',
        text: 'Escolha dia, horario e tipo de visita.',
        icon: '­ƒôà',
      },
      {
        title: 'Corretor direto',
        text: 'Atendimento rapido no WhatsApp.',
        icon: '­ƒô×',
      },
    ],
    cards: [
      {
        title: 'Sala de estar',
        meta: 'Ambiente integrado e iluminado',
        image: landingImage.interior,
      },
      {
        title: 'Cozinha',
        meta: 'Planejada e funcional',
        image: landingImage.condo,
      },
      {
        title: 'Area gourmet',
        meta: 'Churrasqueira e quintal',
        image: landingImage.house,
      },
      {
        title: 'Quintal',
        meta: 'Espaco pet friendly',
        image: landingImage.mansion,
      },
    ],
    sections: designedSections,
    formTitle: 'Agendar visita',
    formSubtitle: 'Escolha a melhor forma de conhecer seu proximo lar.',
    faq: [
      'O imovel aceita criancas?',
      'Quais garantias sao aceitas?',
      'Qual o prazo minimo?',
      'Como funciona a visita por video?',
    ],
  }),
  buildDesignedTemplate({
    id: 'showcase-fazenda-produtiva',
    name: 'Fazenda Produtiva a Venda',
    description:
      'Modelo rural de alto impacto com area total, documentacao, recursos hidricos, drone e material completo.',
    thumbnail: landingImage.farm,
    group: 'Rural',
    category: 'Fazenda produtiva',
    objective: 'Receber material',
    style: 'Rural premium',
    resources: [
      'Dossie tecnico',
      'Drone',
      'CAR/CCIR/SIGEF',
      'Mapa rural',
      'Formulario qualificado',
      'CRM',
    ],
    pipeline: 'Pipeline Rural',
    crmTags: ['Lead Rural', 'Fazenda'],
    conversionEvent: 'lead_fazenda_produtiva',
    palette: {
      primary: '#183c24',
      secondary: '#efe8d5',
      accent: '#d7ae58',
      background: '#fbf7ee',
      text: '#1b241c',
      footer: '#112719',
    },
    logo: 'Imobiliaria Rural',
    nav: [
      'A Fazenda',
      'Estrutura',
      'Recurso Hidrico',
      'Documentacao',
      'Localizacao',
      'FAQ',
    ],
    badge: 'Oportunidade exclusiva',
    headline: 'Fazenda Produtiva',
    highlight: 'a Venda',
    subtitle:
      'Area consolidada, documentacao em dia, recursos hidricos e estrutura pronta para operar.',
    price: 'R$ 68.000.000,00',
    location: 'Municipio de Campo Verde - MT',
    primaryCta: 'Receber material completo',
    secondaryCta: 'Falar no WhatsApp',
    heroImage: landingImage.farm,
    stats: [
      { label: 'Area total', value: '2.350 ha', icon: '­ƒî¥' },
      { label: 'Area aberta', value: '1.880 ha', icon: '­ƒÜ£' },
      { label: 'Area de plantio', value: '1.720 ha', icon: '­ƒî▒' },
      { label: 'Pluviosidade media', value: '600-900 mm', icon: '­ƒîº´©Å' },
      { label: 'Altitude', value: '380-520 m', icon: 'Ôø░´©Å' },
      { label: 'Topografia', value: 'Suave', icon: '­ƒº¡' },
    ],
    features: [
      {
        title: 'Produtividade',
        text: 'Historico de altas safras.',
        icon: '­ƒî¥',
      },
      {
        title: 'Logistica',
        text: 'Acesso facil ao asfalto e armazens.',
        icon: '­ƒøú´©Å',
      },
      {
        title: 'Recursos hidricos',
        text: 'Rios, represas e nascentes.',
        icon: '­ƒÆº',
      },
      {
        title: 'Estrutura completa',
        text: 'Benfeitorias modernas.',
        icon: '­ƒÅí',
      },
      {
        title: 'Documentacao',
        text: 'CAR, CCIR, SIGEF e matricula.',
        icon: '­ƒôä',
      },
    ],
    cards: [
      {
        title: 'Area agricola',
        meta: 'Lavoura consolidada',
        image: landingImage.crops,
      },
      {
        title: 'Casa sede',
        meta: 'Estrutura completa',
        image: landingImage.house,
      },
      {
        title: 'Recursos hidricos',
        meta: 'Represas e nascentes',
        image: landingImage.farm,
      },
      {
        title: 'Documentacao rural',
        meta: 'Pronta para transferencia',
        image: landingImage.broker,
      },
    ],
    sections: designedSections,
    formTitle: 'Receba o material completo',
    formSubtitle: 'Preencha seus dados e receba o dossie da fazenda.',
    faq: [
      'A fazenda esta arrendada?',
      'Qual a forma de pagamento?',
      'Aceita permuta?',
      'A documentacao esta em dia?',
    ],
  }),
  buildDesignedTemplate({
    id: 'showcase-captacao-rural',
    name: 'Captacao Rural Leads de Fazendas',
    description:
      'Modelo para captar compradores e vendedores rurais com formulario duplo, cobertura nacional e prova social.',
    thumbnail: landingImage.crops,
    group: 'Captacao',
    category: 'Leads rurais',
    objective: 'Captar comprador rural',
    style: 'Rural conversao',
    resources: [
      'Formulario comprador/vendedor',
      'Cobertura nacional',
      'WhatsApp',
      'Prova social',
      'CRM',
    ],
    pipeline: 'Pipeline Rural',
    crmTags: ['Lead Rural', 'Comprador Rural', 'Vendedor Rural'],
    conversionEvent: 'lead_captacao_rural',
    palette: {
      primary: '#075e2b',
      secondary: '#edf8e8',
      accent: '#caa23a',
      background: '#ffffff',
      text: '#1f2937',
      footer: '#08351d',
    },
    logo: 'Captacao Rural',
    nav: [
      'Como Funciona',
      'Vantagens',
      'Depoimentos',
      'Cobertura',
      'FAQ',
      'Sobre Nos',
    ],
    badge: 'Leads qualificados e verificados',
    headline: 'Quer comprar ou vender',
    highlight: 'fazenda?',
    subtitle:
      'A gente conecta voce as melhores oportunidades com informacoes reais, verificadas e seguras.',
    location: 'Cobertura em todo o Brasil',
    primaryCta: 'Quero comprar fazenda',
    secondaryCta: 'Quero vender minha fazenda',
    heroImage: landingImage.crops,
    stats: [
      { label: 'Clientes atendidos', value: '+2.500', icon: '­ƒæÑ' },
      { label: 'Leads qualificados', value: '+7.800', icon: 'Ô£à' },
      { label: 'Satisfacao', value: '+98%', icon: 'Ô¡É' },
      { label: 'Cobertura', value: 'Brasil', icon: '­ƒù║´©Å' },
    ],
    features: [
      {
        title: 'Leads qualificados',
        text: 'Selecionamos compradores e vendedores reais.',
        icon: '­ƒÄ»',
      },
      {
        title: 'Dados reais',
        text: 'Informacoes checadas e atualizadas.',
        icon: '­ƒøí´©Å',
      },
      { title: 'Agilidade', text: 'Conectamos voce rapidamente.', icon: 'ÔÜí' },
      { title: 'Sigilo total', text: 'Negociacoes protegidas.', icon: '­ƒöÆ' },
      {
        title: 'Cobertura nacional',
        text: 'Principais regioes agricolas.',
        icon: '­ƒôì',
      },
    ],
    cards: [
      {
        title: 'Comprador de pecuaria',
        meta: 'MT ÔÇó ate 3.000 ha',
        image: landingImage.farm,
      },
      {
        title: 'Investidor agricola',
        meta: 'GO ÔÇó soja e milho',
        image: landingImage.crops,
      },
      {
        title: 'Proprietario vendedor',
        meta: 'PR ÔÇó atendimento sigiloso',
        image: landingImage.broker,
      },
      {
        title: 'Area de expansao',
        meta: 'MS ÔÇó oportunidade verificada',
        image: landingImage.lots,
      },
    ],
    sections: designedSections,
    formTitle: 'Receba oportunidades que combinam com voce',
    formSubtitle: 'Preencha rapidinho e comece a receber leads qualificados.',
    faq: [
      'Os leads sao realmente qualificados?',
      'Meus dados ficam seguros?',
      'Como recebo os leads?',
      'Voc├¬s atuam em todo o Brasil?',
    ],
  }),
  buildDesignedTemplate({
    id: 'showcase-casa-urbana-venda',
    name: 'Casa Urbana a Venda Premium',
    description:
      'Modelo de casa urbana como pagina de venda completa, com galeria, destaques, localizacao, FAQ e formulario.',
    thumbnail: landingImage.house,
    group: 'Urbana',
    category: 'Casa a venda',
    objective: 'Vender imovel',
    style: 'Premium claro',
    resources: [
      'Galeria',
      'Localizacao',
      'Destaques',
      'Formulario',
      'Agenda',
      'CRM',
    ],
    pipeline: 'Pipeline Venda Urbana',
    crmTags: ['Lead Urbano', 'Casa a Venda'],
    conversionEvent: 'lead_casa_urbana',
    palette: {
      primary: '#071b2e',
      secondary: '#f9fafb',
      accent: '#c5923f',
      background: '#ffffff',
      text: '#172033',
      footer: '#06172b',
    },
    logo: 'Urbana Imoveis',
    nav: [
      'Inicio',
      'Detalhes',
      'Fotos',
      'Localizacao',
      'Diferenciais',
      'Contato',
    ],
    badge: 'Casa a venda',
    headline: 'Sua nova historia',
    highlight: 'comeca aqui.',
    subtitle:
      'Conforto, design e localizacao privilegiada em uma casa pronta para morar.',
    price: 'R$ 1.290.000',
    location: 'Jardim das Flores, Campinas/SP',
    primaryCta: 'Falar no WhatsApp',
    secondaryCta: 'Agendar visita',
    heroImage: landingImage.house,
    stats: [
      { label: 'Quartos', value: '4', icon: '­ƒøÅ´©Å' },
      { label: 'Suites', value: '2', icon: '­ƒøü' },
      { label: 'Banheiros', value: '4', icon: '­ƒÜ┐' },
      { label: 'Vagas', value: '2', icon: '­ƒÜù' },
      { label: 'Area construida', value: '180 m2', icon: '­ƒôÉ' },
      { label: 'Terreno', value: '250 m2', icon: '­ƒôÅ' },
    ],
    features: [
      {
        title: 'Projeto moderno',
        text: 'Ambientes amplos e integrados.',
        icon: 'Ô£¿',
      },
      {
        title: 'Area gourmet',
        text: 'Churrasqueira e conforto.',
        icon: '­ƒì¢´©Å',
      },
      {
        title: 'Piscina aquecida',
        text: 'Lazer com privacidade.',
        icon: '­ƒÅè',
      },
      { title: 'Acabamentos', text: 'Materiais premium.', icon: '­ƒÅø´©Å' },
      { title: 'Seguranca', text: 'Monitoramento e cerca.', icon: '­ƒøí´©Å' },
    ],
    cards: [
      {
        title: 'Sala integrada',
        meta: 'Iluminacao natural',
        image: landingImage.interior,
      },
      {
        title: 'Cozinha gourmet',
        meta: 'Marcenaria planejada',
        image: landingImage.condo,
      },
      {
        title: 'Suite master',
        meta: 'Conforto e privacidade',
        image: landingImage.mansion,
      },
      {
        title: 'Area externa',
        meta: 'Piscina e jardim',
        image: landingImage.house,
      },
    ],
    sections: designedSections,
    formTitle: 'Interessado neste imovel?',
    formSubtitle:
      'Receba informacoes completas ou agende uma visita sem compromisso.',
    faq: [
      'O imovel aceita financiamento?',
      'Qual e o valor do IPTU?',
      'O imovel esta averbado?',
      'E possivel comprar com FGTS?',
    ],
  }),
  buildDesignedTemplate({
    id: 'showcase-lancamento-luxo-dark',
    name: 'Lancamento Luxo Dark Editorial',
    description:
      'Modelo dark de alto padrao para empreendimento, plantas, rooftop, galeria editorial e visita privada.',
    thumbnail: landingImage.luxuryApt,
    group: 'Lancamentos',
    category: 'Lancamento de luxo',
    objective: 'Captar lead qualificado',
    style: 'Luxo dark',
    resources: [
      'Galeria premium',
      'Plantas',
      'Rooftop',
      'Agenda privada',
      'Formulario qualificado',
      'CRM',
    ],
    pipeline: 'Pipeline Lancamentos',
    crmTags: ['Lead Alto Padrao', 'Lancamento Luxo'],
    conversionEvent: 'lead_lancamento_luxo_dark',
    palette: {
      primary: '#111111',
      secondary: '#1a1713',
      accent: '#d5a954',
      background: '#111111',
      text: '#efe8dd',
      footer: '#080808',
    },
    logo: 'Maison Vertice',
    nav: [
      'O Empreendimento',
      'Plantas',
      'Lazer',
      'Localizacao',
      'Diferenciais',
      'Contato',
    ],
    badge: 'Lancamento exclusivo',
    headline: 'Apartamentos de Alto Padrao que',
    highlight: 'Elevam seu Estilo de Viver.',
    subtitle:
      'Sofisticacao, conforto e localizacao privilegiada no coracao do bairro mais desejado.',
    price: 'A partir de R$ 2.950.000',
    location: 'Vila Nova Conceicao, Sao Paulo - SP',
    primaryCta: 'Agendar visita privativa',
    secondaryCta: 'Fale com consultor',
    heroImage: landingImage.luxuryApt,
    stats: [
      { label: 'Area privativa', value: '143 a 198 m2', icon: '­ƒøÅ´©Å' },
      { label: 'Suites', value: '3 a 4', icon: '­ƒøü' },
      { label: 'Vagas', value: '2 a 3', icon: '­ƒÜù' },
      { label: 'Torre', value: '1', icon: '­ƒÅó' },
      { label: 'Elevadores', value: '2+1', icon: 'Ôåò´©Å' },
    ],
    features: [
      {
        title: 'Piscina com raia',
        text: 'Climatizada e exclusiva.',
        icon: '­ƒÅè',
      },
      { title: 'Academia', text: 'Equipamentos premium.', icon: '­ƒÅï´©Å' },
      { title: 'Spa e sauna', text: 'Bem-estar completo.', icon: '­ƒºû' },
      { title: 'Salao gourmet', text: 'Receba com elegancia.', icon: '­ƒìÀ' },
      { title: 'Coworking', text: 'Produtividade com conforto.', icon: '­ƒÆ╝' },
    ],
    cards: [
      {
        title: 'Living panoramico',
        meta: 'Vista e design',
        image: landingImage.luxuryApt,
      },
      {
        title: 'Suite master',
        meta: 'Amplitude e conforto',
        image: landingImage.interior,
      },
      {
        title: 'Planta inteligente',
        meta: 'Espacos flexiveis',
        image: landingImage.condo,
      },
      {
        title: 'Rooftop',
        meta: 'Cidade aos seus pes',
        image: landingImage.launch,
      },
    ],
    sections: designedSections,
    formTitle: 'Receba mais informacoes',
    formSubtitle: 'Atendimento exclusivo com especialistas em alto padrao.',
    faq: [
      'Qual o prazo de entrega?',
      'Como funciona a personalizacao?',
      'Quais sao as formas de pagamento?',
      'Ha unidades decoradas?',
    ],
  }),
  buildDesignedTemplate({
    id: 'showcase-lista-vip-lancamento',
    name: 'Lista VIP de Lancamento',
    description:
      'Modelo residencial para pre-lancamento com formulario VIP, plantas, localizacao, countdown e beneficios.',
    thumbnail: landingImage.launch,
    group: 'Lancamentos',
    category: 'Pre-lancamento',
    objective: 'Entrar em lista VIP',
    style: 'Residencial premium',
    resources: [
      'Lista VIP',
      'Countdown',
      'Plantas',
      'Formulario',
      'WhatsApp',
      'CRM',
    ],
    pipeline: 'Pipeline Lancamentos',
    crmTags: ['Lista VIP', 'Lead Lancamento'],
    conversionEvent: 'lead_lista_vip_showcase',
    palette: {
      primary: '#0b4a38',
      secondary: '#f6f1e8',
      accent: '#d7b56d',
      background: '#fffaf2',
      text: '#10231d',
      footer: '#0b3a2d',
    },
    logo: 'Vista do Vale',
    nav: [
      'O Empreendimento',
      'Localizacao',
      'Plantas',
      'Diferenciais',
      'Lazer',
      'Contato',
    ],
    badge: 'Lancamento exclusivo',
    headline: 'O novo endereco dos seus',
    highlight: 'melhores dias.',
    subtitle:
      'Apartamentos modernos em uma localizacao privilegiada, cercados de natureza e conveniencia.',
    location: 'Bairro planejado em crescimento',
    primaryCta: 'Entrar para a lista VIP',
    secondaryCta: 'Fale com especialista',
    heroImage: landingImage.launch,
    stats: [
      { label: 'Preco exclusivo', value: 'VIP', icon: '­ƒÅÀ´©Å' },
      { label: 'Prioridade', value: 'Escolha', icon: '­ƒææ' },
      { label: 'Condicoes', value: 'Especiais', icon: '­ƒñØ' },
      { label: 'Acompanhamento', value: 'Personalizado', icon: '­ƒô×' },
    ],
    features: [
      {
        title: 'Unidades prioridade',
        text: 'Escolha antes da abertura.',
        icon: '­ƒÅó',
      },
      {
        title: 'Preco especial',
        text: 'Condicoes de lancamento.',
        icon: '­ƒÅÀ´©Å',
      },
      {
        title: 'Pagamento exclusivo',
        text: 'Negociacao antecipada.',
        icon: '­ƒÆ│',
      },
      {
        title: 'Eventos',
        text: 'Visitas e apresentacoes privadas.',
        icon: '­ƒÄƒ´©Å',
      },
      {
        title: 'Obra transparente',
        text: 'Acompanhamento por etapas.',
        icon: '­ƒôå',
      },
    ],
    cards: [
      {
        title: '2 dorms. com suite',
        meta: '61 a 72 m2',
        image: landingImage.interior,
      },
      {
        title: '3 dorms. com suite',
        meta: '81 a 97 m2',
        image: landingImage.condo,
      },
      {
        title: 'Lazer completo',
        meta: 'Piscina, gourmet e academia',
        image: landingImage.launch,
      },
      {
        title: 'Localizacao',
        meta: 'Conectado ao essencial',
        image: landingImage.map,
      },
    ],
    sections: designedSections,
    formTitle: 'Entre para a lista VIP',
    formSubtitle:
      'Seja o primeiro a receber condicoes e novidades do lancamento.',
    faq: [
      'Quando comecam as vendas?',
      'Como funciona a lista VIP?',
      'Quais sao as formas de pagamento?',
      'E possivel financiar?',
    ],
  }),
  buildDesignedTemplate({
    id: 'showcase-minha-casa-minha-vida',
    name: 'Minha Casa Minha Vida Familia',
    description:
      'Modelo claro e acessivel para MCMV com simulacao, beneficios, elegibilidade, plantas e visita.',
    thumbnail: landingImage.family,
    group: 'Lancamentos',
    category: 'Minha Casa Minha Vida',
    objective: 'Simular financiamento',
    style: 'Popular confiavel',
    resources: [
      'Simulador',
      'Renda familiar',
      'FGTS',
      'Agenda',
      'WhatsApp',
      'CRM',
    ],
    pipeline: 'Pipeline Minha Casa Minha Vida',
    crmTags: ['Lead Minha Casa Minha Vida'],
    conversionEvent: 'lead_mcmv_showcase',
    palette: {
      primary: '#1768c7',
      secondary: '#eaf5ff',
      accent: '#22c55e',
      background: '#ffffff',
      text: '#18345e',
      footer: '#f9fafb',
    },
    logo: 'Residencial Bom Viver',
    nav: [
      'O Empreendimento',
      'Plantas',
      'Localizacao',
      'Beneficios',
      'Diferenciais',
      'FAQ',
    ],
    badge: 'Lancamento Minha Casa Minha Vida',
    headline: 'Seu novo lar cabe no seu sonho',
    highlight: 'e no seu orcamento.',
    subtitle:
      'Apartamentos modernos, lazer completo e condicoes facilitadas para sua familia.',
    location: 'Jardim Esperanca - Sao Paulo/SP',
    primaryCta: 'Simular financiamento',
    secondaryCta: 'Falar no WhatsApp',
    heroImage: landingImage.family,
    stats: [
      { label: 'Quartos', value: '2', icon: '­ƒÅá' },
      { label: 'Lazer completo', value: 'Sim', icon: '­ƒÄá' },
      { label: 'Seguranca', value: '24h', icon: '­ƒöÆ' },
      { label: 'FGTS', value: 'Use', icon: '­ƒÆ│' },
    ],
    features: [
      {
        title: 'Subsidio',
        text: 'Desconto que pode chegar alto.',
        icon: '­ƒÆÁ',
      },
      {
        title: 'Use seu FGTS',
        text: 'Entrada ou parte do financiamento.',
        icon: '­ƒÆ│',
      },
      {
        title: 'Entrada facilitada',
        text: 'Conquiste seu apartamento.',
        icon: '­ƒöæ',
      },
      {
        title: 'Parcelas acessiveis',
        text: 'Cabem no bolso da familia.',
        icon: '­ƒôä',
      },
      {
        title: 'Elegibilidade',
        text: 'Criterios claros para aprovar.',
        icon: 'Ô£à',
      },
    ],
    cards: [
      {
        title: 'Planta 2 dormitorios',
        meta: '40,33 m2',
        image: landingImage.interior,
      },
      {
        title: 'Planta com varanda',
        meta: '42,39 m2',
        image: landingImage.condo,
      },
      {
        title: 'Decorado',
        meta: 'Pronto para visita',
        image: landingImage.family,
      },
      {
        title: 'Lazer',
        meta: 'Espaco para toda familia',
        image: landingImage.launch,
      },
    ],
    sections: designedSections,
    formTitle: 'Simule seu financiamento',
    formSubtitle: 'E rapido, gratuito e sem compromisso.',
    faq: [
      'Quem pode participar?',
      'Qual valor do subsidio?',
      'Posso usar meu FGTS?',
      'Em quanto tempo posso mudar?',
    ],
  }),
  buildDesignedTemplate({
    id: 'showcase-loteamento-masterplan',
    name: 'Loteamento Masterplan',
    description:
      'Modelo de venda de lotes com mapa masterplan, infraestrutura, condicoes, agenda e formulario.',
    thumbnail: landingImage.lots,
    group: 'Lotes',
    category: 'Loteamento',
    objective: 'Vender lote',
    style: 'Natural premium',
    resources: [
      'Masterplan',
      'Mapa de lotes',
      'Infraestrutura',
      'Agenda',
      'Formulario',
      'CRM',
    ],
    pipeline: 'Pipeline Lancamentos',
    crmTags: ['Lead Lote', 'Loteamento'],
    conversionEvent: 'lead_loteamento_showcase',
    palette: {
      primary: '#394727',
      secondary: '#f5f1e6',
      accent: '#c8a95a',
      background: '#fbf8ef',
      text: '#25251e',
      footer: '#292820',
    },
    logo: 'Vale do Sol',
    nav: [
      'O Loteamento',
      'Localizacao',
      'Lotes',
      'Infraestrutura',
      'Condicoes',
      'Galeria',
      'FAQ',
    ],
    badge: 'Lotes em condominio ou loteamento aberto',
    headline: 'O lugar certo para construir seus',
    highlight: 'melhores planos.',
    subtitle:
      'Lotes residenciais em uma regiao de valorizacao constante e facil acesso.',
    price: 'A partir de R$ 89.900',
    location: 'Regiao em crescimento',
    primaryCta: 'Escolher meu lote',
    secondaryCta: 'Fale com consultor',
    heroImage: landingImage.lots,
    stats: [
      { label: 'Metragem', value: '250 m2+', icon: '­ƒôÉ' },
      { label: 'Entrada', value: 'Facilitada', icon: '­ƒÆ│' },
      { label: 'Parcelamento', value: '120x', icon: '­ƒôå' },
      { label: 'Documentacao', value: 'Regularizada', icon: '­ƒôä' },
    ],
    features: [
      { title: 'Agua', text: 'Rede de abastecimento.', icon: '­ƒÆº' },
      { title: 'Luz', text: 'Iluminacao LED.', icon: 'ÔÜí' },
      { title: 'Pavimentacao', text: 'Vias sinalizadas.', icon: '­ƒøú´©Å' },
      { title: 'Drenagem', text: 'Sistema eficiente.', icon: '­ƒîº´©Å' },
      { title: 'Area verde', text: 'Mais natureza para viver.', icon: '­ƒî┐' },
    ],
    cards: [
      {
        title: 'Quadra A',
        meta: 'Lotes disponiveis',
        image: landingImage.lots,
      },
      {
        title: 'Playground',
        meta: 'Lazer para familia',
        image: landingImage.launch,
      },
      {
        title: 'Portaria',
        meta: 'Controle de acesso',
        image: landingImage.house,
      },
      {
        title: 'Mapa geral',
        meta: 'Masterplan inteligente',
        image: landingImage.map,
      },
    ],
    sections: designedSections,
    formTitle: 'Fale com um consultor',
    formSubtitle: 'Receba tabela completa, disponibilidade e condicoes.',
    faq: [
      'Quais sao os tamanhos dos lotes?',
      'A documentacao esta regularizada?',
      'Posso construir imediatamente?',
      'Quais formas de pagamento?',
    ],
  }),
];
