import {
  LandingPageTemplate,
  buildElementorReferenceTemplate,
  landingImage,
  refThumb,
} from './shared';
export const ELEMENTOR_REFERENCE_TEMPLATES: LandingPageTemplate[] = [
  buildElementorReferenceTemplate({
    id: 'elementor-urban-living-rental',
    name: 'Urban Living Locacao 360',
    description:
      'Pagina de aluguel residencial com tour 360, galeria, agenda, condicoes e WhatsApp.',
    thumbnail: refThumb('urban-living-rental.png'),
    group: 'Aluguel',
    category: 'Apartamento mobiliado',
    objective: 'Agendar visita',
    style: 'Clean premium',
    palette: {
      primary: '#0b1f55',
      secondary: '#0f8ca0',
      accent: '#20c66b',
      background: '#ffffff',
      text: '#102047',
      footer: '#071b44',
    },
    logo: 'URBAN LIVING',
    badge: 'Em destaque',
    headline: 'Apartamento moderno para aluguel',
    highlight: 'pronto para morar.',
    subtitle:
      'Conforto, elegancia e localizacao privilegiada em uma pagina completa para locacao.',
    price: 'R$ 6.900 /mes',
    location: 'Vila Nova Conceicao, Sao Paulo - SP',
    primaryCta: 'Falar no WhatsApp',
    secondaryCta: 'Ver fotos',
    heroImage: landingImage.interior,
    stats: [
      { label: 'Dormitorios', value: '2', icon: 'B' },
      { label: 'Suite', value: '1', icon: 'S' },
      { label: 'Area util', value: '78 m2', icon: 'M' },
      { label: 'Mobiliado', value: 'Sim', icon: 'K' },
    ],
    features: [
      {
        title: 'Tour 360',
        text: 'Experiencia guiada para o lead conhecer tudo antes da visita.',
        icon: '360',
      },
      {
        title: 'Agenda',
        text: 'Horarios claros e chamada direta para conversao.',
        icon: 'CAL',
      },
      {
        title: 'Garantias',
        text: 'Condicoes de locacao apresentadas sem friccao.',
        icon: 'OK',
      },
      {
        title: 'Proximidades',
        text: 'Pontos de interesse organizados para decisao rapida.',
        icon: 'PIN',
      },
      {
        title: 'Corretor',
        text: 'Responsavel visivel com contato imediato.',
        icon: 'CRM',
      },
    ],
    cards: [
      {
        title: 'Sala integrada',
        meta: 'Ambientes mobiliados e varanda gourmet.',
        image: landingImage.interior,
        price: 'Tour virtual',
      },
      {
        title: 'Cozinha planejada',
        meta: 'Layout funcional para morar bem.',
        image: landingImage.house,
      },
      {
        title: 'Localizacao nobre',
        meta: 'Mapa, rotas e conveniencias proximas.',
        image: landingImage.map,
      },
      {
        title: 'Agenda de visita',
        meta: 'Fluxo simples para confirmar horario.',
        image: landingImage.condo,
      },
    ],
    formTitle: 'Agende sua visita',
    formSubtitle:
      'Escolha o melhor horario e receba confirmacao pelo WhatsApp.',
    faq: [
      'O apartamento sera alugado mobiliado?',
      'Qual o prazo minimo de locacao?',
      'Aceita pet?',
      'Como funciona a visita?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-maison-dor-penthouse',
    name: 'Maison DOr Cobertura Luxo',
    description:
      'Tema escuro editorial para cobertura duplex, alto padrao, plantas, concierge e visita privativa.',
    thumbnail: refThumb('maison-dor-penthouse.png'),
    group: 'Alto Padrao',
    category: 'Cobertura duplex',
    objective: 'Visita privativa',
    style: 'Luxo escuro',
    palette: {
      primary: '#070707',
      secondary: '#15110d',
      accent: '#d6a35d',
      background: '#080808',
      text: '#f8f0e4',
      footer: '#030303',
    },
    logo: 'MAISON DOR',
    badge: 'Cobertura duplex',
    headline: 'O topo de Sao Paulo',
    highlight: 'e todo seu.',
    subtitle:
      'Luxo, privacidade e vistas incomparaveis para compradores de altissimo padrao.',
    price: 'R$ 22.800.000',
    location: 'Itaim Bibi, Sao Paulo - SP',
    primaryCta: 'Agendar visita privativa',
    secondaryCta: 'Ver galeria',
    heroImage: landingImage.luxuryApt,
    stats: [
      { label: 'Suites', value: '4', icon: 'S' },
      { label: 'Vagas', value: '6', icon: 'V' },
      { label: 'Privativos', value: '620 m2', icon: 'M' },
      { label: 'Concierge', value: '24h', icon: 'C' },
    ],
    features: [
      {
        title: 'Hall privativo',
        text: 'Chegada exclusiva com percepcao imediata de valor.',
        icon: '01',
      },
      {
        title: 'Rooftop',
        text: 'Piscina, solarium e vista panoramica.',
        icon: '02',
      },
      {
        title: 'Plantas',
        text: 'Apresentacao visual de pavimentos e possibilidades.',
        icon: '03',
      },
      {
        title: 'Concierge',
        text: 'Servicos que antecipam desejos.',
        icon: '04',
      },
      {
        title: 'Exclusividade',
        text: 'Copy e visual para leads qualificados.',
        icon: '05',
      },
    ],
    cards: [
      {
        title: 'Terraco skyline',
        meta: 'Cenarios que inspiram.',
        image: landingImage.luxuryApt,
      },
      {
        title: 'Living duplex',
        meta: 'Integracao perfeita.',
        image: landingImage.interior,
      },
      {
        title: 'Suite master',
        meta: 'Privacidade absoluta.',
        image: landingImage.house,
      },
      {
        title: 'Planta completa',
        meta: 'Dois pavimentos inteligentes.',
        image: landingImage.condo,
      },
    ],
    formTitle: 'Agende sua visita privativa',
    formSubtitle: 'Atendimento exclusivo, reservado e sem atrito.',
    faq: [
      'Qual o valor do condominio?',
      'A cobertura sera entregue mobiliada?',
      'E possivel personalizar acabamentos?',
      'Como funciona a visita privativa?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-nova-casa-portal',
    name: 'Nova Casa Portal Imobiliario',
    description:
      'Home completa para imobiliaria com busca, bairros, imoveis, corretores, blog e captacao.',
    thumbnail: refThumb('nova-casa-portal.png'),
    group: 'Institucional',
    category: 'Imobiliaria urbana',
    objective: 'Buscar imoveis',
    style: 'Portal moderno',
    palette: {
      primary: '#26323a',
      secondary: '#f7f3ed',
      accent: '#c95f3e',
      background: '#ffffff',
      text: '#202020',
      footer: '#1f2b32',
    },
    logo: 'NOVA CASA',
    badge: 'Imobiliaria',
    headline: 'Viva o melhor de Sao Paulo',
    subtitle: 'Encontre o imovel ideal com quem entende seu estilo de vida.',
    location: 'Sao Paulo - SP',
    primaryCta: 'Buscar imoveis',
    secondaryCta: 'Anunciar imovel',
    heroImage: landingImage.condo,
    stats: [
      { label: 'Anos de mercado', value: '12+', icon: 'A' },
      { label: 'Imoveis vendidos', value: '5.200+', icon: 'I' },
      { label: 'Clientes', value: '8.900+', icon: 'C' },
      { label: 'Satisfacao', value: '98%', icon: 'S' },
    ],
    features: [
      { title: 'Comprar', text: 'Imoveis para morar ou investir.', icon: 'H' },
      { title: 'Alugar', text: 'Opcoes completas para locacao.', icon: 'A' },
      { title: 'Lancamentos', text: 'Empreendimentos em destaque.', icon: 'L' },
      {
        title: 'Anunciar',
        text: 'Captacao profissional de proprietarios.',
        icon: 'V',
      },
      {
        title: 'Corretores',
        text: 'Equipe com atendimento humanizado.',
        icon: 'C',
      },
    ],
    cards: [
      {
        title: 'Apartamento em Moema',
        meta: '2 dorms, 1 suite, 87 m2.',
        image: landingImage.interior,
        price: 'R$ 1.250.000',
      },
      {
        title: 'Cobertura em Pinheiros',
        meta: '3 suites, vista aberta.',
        image: landingImage.luxuryApt,
        price: 'R$ 2.980.000',
      },
      {
        title: 'Apartamento no Itaim',
        meta: 'Pronto para alugar.',
        image: landingImage.house,
        price: 'R$ 4.800 /mes',
      },
      {
        title: 'Edificio Horizonte',
        meta: 'Lancamento exclusivo.',
        image: landingImage.launch,
        price: 'Ver condicoes',
      },
    ],
    formTitle: 'Fale com a gente',
    formSubtitle: 'Receba atendimento para comprar, alugar ou anunciar.',
    faq: [
      'Como anunciar meu imovel?',
      'Voc├¬s atendem locacao?',
      'Posso falar com um corretor?',
      'Como recebo novidades?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-nova-corporativo',
    name: 'Nova Properties Corporativo',
    description:
      'Landing para laje corporativa, galpao ou sala comercial com ficha tecnica e formulario B2B.',
    thumbnail: refThumb('nova-corporativo.png'),
    group: 'Comercial',
    category: 'Laje corporativa',
    objective: 'Falar com especialista',
    style: 'Corporativo clean',
    palette: {
      primary: '#0b3558',
      secondary: '#eef6ff',
      accent: '#f97316',
      background: '#ffffff',
      text: '#0f2f55',
      footer: '#082b46',
    },
    logo: 'NOVA PROPERTIES',
    badge: 'Para locacao',
    headline: 'Laje corporativa premium',
    highlight: 'no centro financeiro.',
    subtitle: 'Espaco, tecnologia e imagem para impulsionar sua empresa.',
    price: 'R$ 98.500 /mes',
    location: 'Itaim Bibi, Sao Paulo - SP',
    primaryCta: 'Agendar visita',
    secondaryCta: 'Falar com consultor',
    heroImage: landingImage.warehouse,
    stats: [
      { label: 'Area privativa', value: '1.284 m2', icon: 'M' },
      { label: 'Andar', value: '12 andar', icon: 'A' },
      { label: 'Vagas', value: '28', icon: 'V' },
      { label: 'Pe-direito', value: '2,80 m', icon: 'P' },
    ],
    features: [
      {
        title: 'Produtividade',
        text: 'Ambiente moderno para performance.',
        icon: 'PR',
      },
      {
        title: 'Flexibilidade',
        text: 'Layout adaptavel por equipe.',
        icon: 'FX',
      },
      { title: 'Certificacao', text: 'Imagem corporativa e ESG.', icon: 'ESG' },
      {
        title: 'Localizacao',
        text: 'Acesso rapido a pontos estrategicos.',
        icon: 'LOC',
      },
      {
        title: 'B2B',
        text: 'Formulario qualificado para empresas.',
        icon: 'B2B',
      },
    ],
    cards: [
      {
        title: 'Open space',
        meta: 'Planta livre adaptavel.',
        image: landingImage.warehouseInside,
      },
      {
        title: 'Recepcao premium',
        meta: 'Imagem e seguranca.',
        image: landingImage.interior,
      },
      {
        title: 'Vista corporativa',
        meta: 'Endereco de prestigio.',
        image: landingImage.warehouse,
      },
      {
        title: 'Layout tecnico',
        meta: 'Memorial e plantas.',
        image: landingImage.map,
      },
    ],
    formTitle: 'Fale com um especialista',
    formSubtitle:
      'Preencha os dados e receba mais informacoes sobre este imovel.',
    faq: [
      'Esta disponivel para ocupacao imediata?',
      'Ha possibilidade de customizacao?',
      'O condominio possui gerador?',
      'Quantas vagas estao inclusas?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-fazendas-valor',
    name: 'Fazendas de Valor Pecuaria',
    description:
      'Tema rural escuro para fazenda completa, pecuaria, documentacao, drone e material completo.',
    thumbnail: refThumb('fazendas-valor.png'),
    group: 'Rural',
    category: 'Fazenda pecuaria',
    objective: 'Receber material',
    style: 'Rural premium',
    palette: {
      primary: '#042b1d',
      secondary: '#061f17',
      accent: '#c4974b',
      background: '#06261a',
      text: '#f8f0db',
      footer: '#041912',
    },
    logo: 'FAZENDAS DE VALOR',
    badge: 'Oportunidade exclusiva',
    headline: 'Fazenda completa para pecuaria',
    subtitle:
      'Propriedade pronta para operacao com estrutura, logistica e documentacao.',
    price: 'R$ 24.500.000',
    location: 'Sao Felix do Araguaia - MT',
    primaryCta: 'Falar no WhatsApp',
    secondaryCta: 'Baixar material',
    heroImage: landingImage.farm,
    stats: [
      { label: 'Area total', value: '1.284 ha', icon: 'HA' },
      { label: 'Area aberta', value: '980 ha', icon: 'AB' },
      { label: 'Divisoes', value: '28', icon: 'D' },
      { label: 'Capacidade', value: '2.000 cabecas', icon: 'G' },
    ],
    features: [
      {
        title: 'Documentacao OK',
        text: 'CAR, CCIR, ITR e matricula organizados.',
        icon: 'DOC',
      },
      {
        title: 'Recursos hidricos',
        text: 'Represas, rio e nascentes.',
        icon: 'AG',
      },
      {
        title: 'Benfeitorias',
        text: 'Sede, curral, energia e cercas.',
        icon: 'SE',
      },
      {
        title: 'Logistica',
        text: 'Acesso claro para compradores.',
        icon: 'RO',
      },
      {
        title: 'Investimento',
        text: 'Argumentos fortes de liquidez.',
        icon: 'R$',
      },
    ],
    cards: [
      {
        title: 'A fazenda',
        meta: 'Apresentacao completa da propriedade.',
        image: landingImage.farm,
      },
      {
        title: 'Galeria tecnica',
        meta: 'Pastos, curral e recursos.',
        image: landingImage.crops,
      },
      {
        title: 'Video aereo',
        meta: 'Drone para gerar confianca.',
        image: landingImage.lots,
      },
      {
        title: 'Documentacao',
        meta: 'Tudo preparado para due diligence.',
        image: landingImage.map,
      },
    ],
    formTitle: 'Receba o material completo',
    formSubtitle: 'Preencha os dados e receba todas as informacoes da fazenda.',
    faq: [
      'A fazenda esta pronta para producao?',
      'Qual a capacidade de lotacao?',
      'A documentacao esta regularizada?',
      'A fazenda pode ser visitada?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-captacao-rural',
    name: 'Captacao Rural Leads de Fazendas',
    description:
      'Landing de captacao para comprar ou vender fazenda, com funil duplo e prova social.',
    thumbnail: refThumb('captacao-rural.png'),
    group: 'Captacao',
    category: 'Leads rurais',
    objective: 'Captar comprador/vendedor',
    style: 'Conversao rural',
    palette: {
      primary: '#064e2b',
      secondary: '#eff7ec',
      accent: '#d6a733',
      background: '#ffffff',
      text: '#17231b',
      footer: '#071a12',
    },
    logo: 'CAPTACAO RURAL',
    badge: 'Leads de fazendas',
    headline: 'Quer comprar ou vender fazenda?',
    highlight: 'A gente conecta voce.',
    subtitle:
      'Leads qualificados, informacoes reais e verificadas para decisoes mais rapidas.',
    location: 'Atuacao nacional',
    primaryCta: 'Quero comprar fazenda',
    secondaryCta: 'Quero vender minha fazenda',
    heroImage: landingImage.crops,
    stats: [
      { label: 'Clientes atendidos', value: '+2.500', icon: 'CL' },
      { label: 'Leads qualificados', value: '+7.800', icon: 'LD' },
      { label: 'Satisfacao', value: '+98%', icon: 'OK' },
      { label: 'Cobertura', value: 'Brasil', icon: 'BR' },
    ],
    features: [
      {
        title: 'Leads qualificados',
        text: 'Perfis selecionados para compra ou venda.',
        icon: 'AL',
      },
      {
        title: 'Dados reais',
        text: 'Informacoes completas e conferidas.',
        icon: 'DT',
      },
      {
        title: 'Agilidade',
        text: 'Conexao rapida com oportunidades.',
        icon: 'RA',
      },
      {
        title: 'Sigilo',
        text: 'Processo discreto e profissional.',
        icon: 'SG',
      },
      { title: 'Cobertura', text: 'Regioes agricolas do Brasil.', icon: 'BR' },
    ],
    cards: [
      {
        title: 'Quero comprar',
        meta: 'Receba oportunidades compativeis.',
        image: landingImage.farm,
      },
      {
        title: 'Quero vender',
        meta: 'Capte compradores qualificados.',
        image: landingImage.crops,
      },
      {
        title: 'Cobertura nacional',
        meta: 'Mapa de atuacao por regiao.',
        image: landingImage.map,
      },
      {
        title: 'Depoimentos',
        meta: 'Prova social para conversao.',
        image: landingImage.broker,
      },
    ],
    formTitle: 'Receba oportunidades',
    formSubtitle: 'Preencha rapidinho e comece a receber leads qualificados.',
    faq: [
      'Os leads sao qualificados?',
      'Meus dados ficam seguros?',
      'Atendem todo o Brasil?',
      'Em quanto tempo recebo oportunidades?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-nexo-studios',
    name: 'Nexo Studios Investimento',
    description:
      'Pre-lancamento para studios compactos com foco em rentabilidade, demanda e lista VIP.',
    thumbnail: refThumb('nexo-studios.png'),
    group: 'Lancamentos',
    category: 'Studios para investimento',
    objective: 'Lista VIP',
    style: 'Tech neon',
    palette: {
      primary: '#07111a',
      secondary: '#101820',
      accent: '#c7ff17',
      background: '#07111a',
      text: '#f8fafc',
      footer: '#050b10',
    },
    logo: 'NEXO STUDIOS',
    badge: 'Lancamento exclusivo',
    headline: 'Studios inteligentes.',
    highlight: 'Rentabilidade real.',
    subtitle:
      'Studios compactos e completos para investir com seguranca e lucrar com locacao.',
    location: 'Centro financeiro',
    primaryCta: 'Quero receber a tabela',
    secondaryCta: 'Ver plantas',
    heroImage: landingImage.launch,
    stats: [
      { label: 'Rentabilidade ao mes', value: '0,8% a 1,2%', icon: 'R' },
      { label: 'Ao ano estimado', value: '10% a 14%', icon: 'A' },
      { label: 'Locacao', value: 'Alta demanda', icon: 'D' },
      { label: 'Metro', value: '350 m', icon: 'M' },
    ],
    features: [
      {
        title: 'Gestao facil',
        text: 'Locacao sem complicacao para investidores.',
        icon: 'APP',
      },
      {
        title: 'Alta demanda',
        text: 'Regiao preparada para short stay.',
        icon: 'UP',
      },
      {
        title: 'Plantas compactas',
        text: 'Studios S, M e L apresentados visualmente.',
        icon: 'PL',
      },
      {
        title: 'Amenidades',
        text: 'Rooftop, coworking e lavanderia.',
        icon: 'AM',
      },
      {
        title: 'Lista VIP',
        text: 'Captura para condicoes antecipadas.',
        icon: 'VIP',
      },
    ],
    cards: [
      {
        title: 'Studio S',
        meta: '21 m2, ideal para locacao solo.',
        image: landingImage.interior,
      },
      {
        title: 'Studio M',
        meta: '27 m2, maior procura.',
        image: landingImage.house,
      },
      {
        title: 'Studio L',
        meta: '33 m2, ticket medio alto.',
        image: landingImage.condo,
      },
      {
        title: 'App de gestao',
        meta: 'Performance para o investidor.',
        image: landingImage.map,
      },
    ],
    formTitle: 'Entre para a lista VIP',
    formSubtitle: 'Receba tabela, preco, plantas e condicoes de lancamento.',
    faq: [
      'Qual o retorno esperado?',
      'Qual o modelo de gestao?',
      'Posso financiar?',
      'Quando fica pronto?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-vale-do-sol-loteamento',
    name: 'Vale do Sol Loteamento',
    description:
      'Tema para loteamento com masterplan, infraestrutura, lotes, mapa e agenda de visita.',
    thumbnail: refThumb('vale-do-sol-loteamento.png'),
    group: 'Loteamentos',
    category: 'Lotes residenciais',
    objective: 'Escolher lote',
    style: 'Natural sofisticado',
    palette: {
      primary: '#354322',
      secondary: '#f2eee4',
      accent: '#c4a45e',
      background: '#fbf8ef',
      text: '#1e2417',
      footer: '#25271e',
    },
    logo: 'VALE DO SOL',
    badge: 'Lotes em condominio',
    headline: 'O lugar certo para construir',
    highlight: 'seus melhores planos.',
    subtitle:
      'Lotes residenciais em regiao de valorizacao com infraestrutura completa.',
    price: 'A partir de R$ 89.900',
    location: 'Regiao em crescimento',
    primaryCta: 'Escolher meu lote',
    secondaryCta: 'Ver masterplan',
    heroImage: landingImage.lots,
    stats: [
      { label: 'Lotes', value: '250 m2+', icon: 'LT' },
      { label: 'Entrada', value: 'Facilitada', icon: 'EF' },
      { label: 'Parcelas', value: '120x', icon: '120' },
      { label: 'Documentacao', value: '100%', icon: 'OK' },
    ],
    features: [
      {
        title: 'Masterplan',
        text: 'Quadras, lotes e status de disponibilidade.',
        icon: 'MP',
      },
      {
        title: 'Infraestrutura',
        text: 'Agua, luz, drenagem e pavimentacao.',
        icon: 'IF',
      },
      {
        title: 'Localizacao',
        text: 'Mapa estrategico e pontos proximos.',
        icon: 'LC',
      },
      {
        title: 'Condicoes',
        text: 'Pagamento facilitado e simulacao.',
        icon: 'R$',
      },
      { title: 'Agenda', text: 'Visita guiada com consultor.', icon: 'AG' },
    ],
    cards: [
      {
        title: 'Masterplan',
        meta: 'Mapa visual dos lotes.',
        image: landingImage.lots,
      },
      {
        title: 'Infraestrutura',
        meta: 'Tudo que sua familia merece.',
        image: landingImage.farm,
      },
      {
        title: 'Galeria',
        meta: 'Visualize o futuro aqui.',
        image: landingImage.crops,
      },
      { title: 'Localizacao', meta: 'Perto de tudo.', image: landingImage.map },
    ],
    formTitle: 'Fale com um consultor',
    formSubtitle: 'Receba tabela completa, disponibilidade e condicoes.',
    faq: [
      'Quais sao os tamanhos dos lotes?',
      'A documentacao esta regularizada?',
      'Posso construir imediatamente?',
      'Como faco para reservar um lote?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-reserva-dos-ipes',
    name: 'Reserva dos Ipes Condominio',
    description:
      'Lancamento de condominio horizontal com cadastro VIP, casas, lazer, countdown e material completo.',
    thumbnail: refThumb('reserva-dos-ipes.png'),
    group: 'Lancamentos',
    category: 'Condominio horizontal',
    objective: 'Cadastro VIP',
    style: 'Natureza luxo',
    palette: {
      primary: '#18371f',
      secondary: '#f5efe3',
      accent: '#b8733f',
      background: '#fbf6ee',
      text: '#26301f',
      footer: '#142817',
    },
    logo: 'RESERVA DOS IPES',
    badge: 'Lancamento exclusivo',
    headline: 'Viva o privilegio',
    highlight: 'de pertencer.',
    subtitle:
      'Um condominio horizontal cercado pela natureza, com seguranca total e lazer de clube.',
    location: 'Condominio horizontal exclusivo',
    primaryCta: 'Quero ser VIP',
    secondaryCta: 'Ver masterplan',
    heroImage: landingImage.farm,
    stats: [
      { label: 'Area total', value: '310.000 m2', icon: 'AT' },
      { label: 'Lotes', value: '120', icon: 'LT' },
      { label: 'Area verde', value: '+70.000 m2', icon: 'AV' },
      { label: 'Entrega', value: 'Dez/2027', icon: 'EN' },
    ],
    features: [
      {
        title: 'Casas autorais',
        text: 'Plantas de alto padrao para familias exigentes.',
        icon: 'CA',
      },
      {
        title: 'Clube exclusivo',
        text: 'Piscina, spa, quadras e salao.',
        icon: 'CL',
      },
      {
        title: 'Seguranca',
        text: 'Portaria blindada e monitoramento.',
        icon: 'SG',
      },
      {
        title: 'Natureza',
        text: 'Paisagismo e areas preservadas.',
        icon: 'NA',
      },
      {
        title: 'Lista VIP',
        text: 'Condicoes antecipadas de lancamento.',
        icon: 'VIP',
      },
    ],
    cards: [
      {
        title: 'Masterplan',
        meta: 'Projeto feito para pertencimento.',
        image: landingImage.lots,
      },
      {
        title: 'Casa Ipe Amarelo',
        meta: '250 m2 e terreno amplo.',
        image: landingImage.house,
      },
      {
        title: 'Casa Ipe Branco',
        meta: '320 m2 com lazer privativo.',
        image: landingImage.condo,
      },
      {
        title: 'Lazer completo',
        meta: 'Para todas as idades.',
        image: landingImage.farm,
      },
    ],
    formTitle: 'Fale com um especialista',
    formSubtitle: 'Receba tabela, plantas e condicoes de lancamento.',
    faq: [
      'Qual o valor medio das casas?',
      'Quais sao as formas de pagamento?',
      'Qual a previsao de entrega?',
      'O condominio permite animais?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-avaliacao-gratuita',
    name: 'Avaliacao Gratuita de Imovel',
    description:
      'Landing agressiva de captacao de proprietarios com avaliacao gratuita, comparativo e WhatsApp.',
    thumbnail: refThumb('avaliacao-gratuita.png'),
    group: 'Captacao',
    category: 'Avaliacao de imovel',
    objective: 'Avaliar imovel',
    style: 'Conversao alta',
    palette: {
      primary: '#06472d',
      secondary: '#f7f2e6',
      accent: '#e0a622',
      background: '#ffffff',
      text: '#122019',
      footer: '#092018',
    },
    logo: 'NOVA CASA',
    badge: 'Quero vender meu imovel',
    headline: 'Avaliacao',
    highlight: 'gratuita.',
    subtitle: 'Venda com seguranca, rapidez e pelo melhor preco de mercado.',
    location: 'Campinas e regiao',
    primaryCta: 'Quero minha avaliacao gratuita',
    secondaryCta: 'Chamar no WhatsApp',
    heroImage: landingImage.condo,
    stats: [
      { label: 'Imoveis vendidos', value: '+1.200', icon: 'V' },
      { label: 'Avaliacao', value: '4,9/5', icon: 'ST' },
      { label: 'Taxa de sucesso', value: '98%', icon: 'OK' },
      { label: 'Media para vender', value: '23 dias', icon: 'DI' },
    ],
    features: [
      {
        title: 'Avaliacao precisa',
        text: 'Estudo completo de mercado.',
        icon: 'AV',
      },
      {
        title: 'Divulgacao maxima',
        text: 'Portais e redes sociais.',
        icon: 'MK',
      },
      {
        title: 'Atendimento premium',
        text: 'Acompanhamento proximo.',
        icon: 'AT',
      },
      {
        title: 'Venda rapida',
        text: 'Estrategia para reduzir burocracia.',
        icon: 'VR',
      },
      {
        title: 'Seguranca total',
        text: 'Documentacao e negociacao segura.',
        icon: 'SG',
      },
    ],
    cards: [
      {
        title: 'Formulario de avaliacao',
        meta: 'Dados essenciais para precificar.',
        image: landingImage.house,
      },
      {
        title: 'Comparativo',
        meta: 'Nova Casa vs venda por conta propria.',
        image: landingImage.map,
      },
      {
        title: 'Prova social',
        meta: 'Quem vendeu recomenda.',
        image: landingImage.broker,
      },
      {
        title: 'WhatsApp CTA',
        meta: 'Conversao rapida no rodape.',
        image: landingImage.interior,
      },
    ],
    formTitle: 'Receba agora sua avaliacao gratuita',
    formSubtitle: 'Sem compromisso e 100% online.',
    faq: [
      'A avaliacao realmente e gratuita?',
      'Preciso assinar contrato?',
      'Em quanto tempo recebo?',
      'Como e feita a divulgacao?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-refugio-serra',
    name: 'Refugio da Serra Sitio',
    description:
      'Tema emocional para sitio, chacara ou lazer rural com fotos, video drone, mapa e agendamento.',
    thumbnail: refThumb('refugio-serra.png'),
    group: 'Rural',
    category: 'Sitio e lazer',
    objective: 'Agendar visita',
    style: 'Editorial natural',
    palette: {
      primary: '#5c6f52',
      secondary: '#fbf4e8',
      accent: '#b96546',
      background: '#fffaf1',
      text: '#33402f',
      footer: '#5f7058',
    },
    logo: 'REFUGIO DA SERRA',
    badge: 'Seu lugar para viver bem',
    headline: 'Mais natureza. Mais tempo.',
    highlight: 'Mais vida.',
    subtitle:
      'Um sitio completo para lazer, descanso e qualidade de vida para toda a familia.',
    price: 'R$ 1.250.000',
    location: 'Aguas de Santa Barbara - SP',
    primaryCta: 'Falar no WhatsApp',
    secondaryCta: 'Receber mais fotos',
    heroImage: landingImage.farm,
    stats: [
      { label: 'Documentacao', value: 'Em dia', icon: 'DOC' },
      { label: 'Regiao', value: '2h de SP', icon: 'SP' },
      { label: 'Lazer', value: 'Completo', icon: 'LZ' },
      { label: 'Visita', value: 'Agendada', icon: 'AG' },
    ],
    features: [
      {
        title: 'Lago privativo',
        text: 'Natureza presente todos os dias.',
        icon: 'LA',
      },
      { title: 'Piscina', text: 'Lazer para familia e amigos.', icon: 'PI' },
      { title: 'Pomar', text: 'Vida no campo com conforto.', icon: 'PO' },
      {
        title: 'Casa sede',
        text: 'Ambiente acolhedor e funcional.',
        icon: 'CS',
      },
      {
        title: 'Internet',
        text: 'Conexao para morar ou descansar.',
        icon: 'WI',
      },
    ],
    cards: [
      {
        title: 'Conheca cada detalhe',
        meta: 'Galeria emocional.',
        image: landingImage.farm,
      },
      {
        title: 'Veja de cima',
        meta: 'Video com drone.',
        image: landingImage.crops,
      },
      {
        title: 'Localizacao',
        meta: 'Equilibrio entre tranquilidade e acesso.',
        image: landingImage.map,
      },
      {
        title: 'Viva o campo',
        meta: 'Momentos para ficar na memoria.',
        image: landingImage.house,
      },
    ],
    formTitle: 'Fale com a gente',
    formSubtitle: 'Respostas rapidas pelo WhatsApp.',
    faq: [
      'A propriedade possui documentacao?',
      'Qual o tamanho total do terreno?',
      'A casa e mobiliada?',
      'E possivel financiamento?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-campocerto-plantio',
    name: 'CampoCerto Fazenda Plantio',
    description:
      'Landing clara para fazenda agricola com produtividade, solo, mapa, documentacao e investimento.',
    thumbnail: refThumb('campocerto-plantio.png'),
    group: 'Rural',
    category: 'Plantio',
    objective: 'Solicitar informacoes',
    style: 'Agro clean',
    palette: {
      primary: '#075d2c',
      secondary: '#f7f9f0',
      accent: '#f4c430',
      background: '#ffffff',
      text: '#0d2417',
      footer: '#04451f',
    },
    logo: 'CAMPOCERTO',
    badge: 'Fazenda para plantio',
    headline: 'Fazenda para Plantio',
    subtitle: 'Alta produtividade, solo de qualidade e logistica estrategica.',
    price: 'R$ 38.500.000',
    location: 'Santa Helena do Oeste - PR',
    primaryCta: 'Quero mais informacoes',
    secondaryCta: 'Agendar visita',
    heroImage: landingImage.crops,
    stats: [
      { label: 'Area total', value: '1.240 ha', icon: 'HA' },
      { label: 'Agricultavel', value: '1.028 ha', icon: 'AG' },
      { label: 'Solo', value: 'Latossolo', icon: 'SO' },
      { label: 'Logistica', value: 'Ate 75 km', icon: 'LO' },
    ],
    features: [
      {
        title: 'Solo fertil',
        text: 'Alta aptidao para graos e fibras.',
        icon: 'SO',
      },
      { title: 'Relevo suave', text: 'Facilidade de mecanizacao.', icon: 'RL' },
      { title: 'Pluviometria', text: 'Indice bem distribuido.', icon: 'CH' },
      { title: 'Documentacao', text: '100% regularizada.', icon: 'DOC' },
      {
        title: 'Tese de investimento',
        text: 'Argumentos para decisao.',
        icon: 'TI',
      },
    ],
    cards: [
      {
        title: 'Galeria agricola',
        meta: 'Talhoes e lavouras.',
        image: landingImage.crops,
      },
      {
        title: 'Mapa da propriedade',
        meta: 'Poligono e distancias.',
        image: landingImage.map,
      },
      {
        title: 'Potencial produtivo',
        meta: 'Safras e medias.',
        image: landingImage.farm,
      },
      {
        title: 'Infraestrutura',
        meta: 'Energia, agua e benfeitorias.',
        image: landingImage.lots,
      },
    ],
    formTitle: 'Receba informacoes completas',
    formSubtitle: 'Preencha o formulario e fale com um especialista.',
    faq: [
      'Qual e a porcentagem de reserva legal?',
      'Ha passivos ambientais?',
      'E possivel financiamento?',
      'Ha arrendamento vigente?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-corretor-pessoal',
    name: 'Corretor Pessoal Alto Padrao',
    description:
      'Site institucional de corretor com autoridade, imoveis selecionados, avaliacao e contato.',
    thumbnail: refThumb('corretor-pessoal.png'),
    group: 'Institucional',
    category: 'Corretor premium',
    objective: 'Falar no WhatsApp',
    style: 'Autoridade premium',
    palette: {
      primary: '#07382c',
      secondary: '#fff8ec',
      accent: '#c99b45',
      background: '#ffffff',
      text: '#1c221e',
      footer: '#061d1c',
    },
    logo: 'SEU NOME',
    badge: 'Confianca. Experiencia. Resultados.',
    headline: 'Realizo o seu melhor negocio imobiliario.',
    subtitle:
      'Especialista em conectar pessoas a imoveis e oportunidades que valorizam patrimonio e realizam sonhos.',
    location: 'Sao Jose dos Campos - SP',
    primaryCta: 'Ver imoveis a venda',
    secondaryCta: 'Avaliacao gratuita',
    heroImage: landingImage.mansion,
    stats: [
      { label: 'Anos de experiencia', value: '+8', icon: 'EX' },
      { label: 'Imoveis negociados', value: '+300', icon: 'IM' },
      { label: 'Atendimento', value: 'Humanizado', icon: 'AT' },
      { label: 'Negociacao', value: 'Segura', icon: 'NG' },
    ],
    features: [
      {
        title: 'Residenciais',
        text: 'Casas e apartamentos para morar.',
        icon: 'RE',
      },
      {
        title: 'Comerciais',
        text: 'Salas, lojas e espacos comerciais.',
        icon: 'CO',
      },
      { title: 'Terrenos', text: 'Oportunidades para investir.', icon: 'TE' },
      {
        title: 'Investimentos',
        text: 'Renda e valorizacao segura.',
        icon: 'IN',
      },
      { title: 'Aluguel', text: 'Opcoes selecionadas.', icon: 'AL' },
    ],
    cards: [
      {
        title: 'Casa em condominio',
        meta: '3 suites, 4 banheiros.',
        image: landingImage.mansion,
        price: 'R$ 1.580.000',
      },
      {
        title: 'Apartamento alto padrao',
        meta: '3 quartos e vista.',
        image: landingImage.interior,
        price: 'R$ 950.000',
      },
      {
        title: 'Sala comercial',
        meta: 'Jardim Aquarius.',
        image: landingImage.warehouse,
        price: 'R$ 420.000',
      },
      {
        title: 'Terreno em condominio',
        meta: 'Urbanova.',
        image: landingImage.lots,
        price: 'R$ 680.000',
      },
    ],
    formTitle: 'Fale comigo',
    formSubtitle: 'Preencha o formulario que retorno rapidinho.',
    faq: [
      'Como funciona a avaliacao?',
      'Quais documentos sao necessarios?',
      'Voc├¬s atendem outras regioes?',
      'Como e feita a divulgacao?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-galpao-logistico',
    name: 'Galpao Logistico Premium',
    description:
      'Landing comercial para galpao logistico com ficha tecnica, localizacao, vantagens e visita tecnica.',
    thumbnail: refThumb('galpao-logistico.png'),
    group: 'Comercial',
    category: 'Galpao logistico',
    objective: 'Agendar visita tecnica',
    style: 'Industrial premium',
    palette: {
      primary: '#061b35',
      secondary: '#f8fbff',
      accent: '#ff6b1a',
      background: '#ffffff',
      text: '#0b1d35',
      footer: '#05182f',
    },
    logo: 'NOVA IMOVEIS CORPORATIVOS',
    badge: 'Imovel comercial / galpao',
    headline: 'Galpao logistico premium',
    highlight: 'em localizacao estrategica.',
    subtitle:
      'Estrutura moderna, seguranca e eficiencia para impulsionar sua operacao.',
    price: 'R$ 168.000 /mes',
    location: 'Cajamar - SP',
    primaryCta: 'Agendar visita',
    secondaryCta: 'Fale com especialista',
    heroImage: landingImage.warehouse,
    stats: [
      { label: 'Area construida', value: '12.500 m2', icon: 'AC' },
      { label: 'Terreno', value: '20.000 m2', icon: 'AT' },
      { label: 'Docas', value: '16', icon: 'DC' },
      { label: 'Energia', value: '750 KVA', icon: 'EN' },
    ],
    features: [
      {
        title: 'Acesso rapido',
        text: 'Conexao com principais rodovias.',
        icon: 'AR',
      },
      {
        title: 'Mao de obra',
        text: 'Regiao com oferta profissional.',
        icon: 'MO',
      },
      { title: 'Seguranca', text: 'Controle 24h e portaria.', icon: 'SG' },
      {
        title: 'Infraestrutura',
        text: 'Servicos essenciais proximos.',
        icon: 'IF',
      },
      {
        title: 'Escalabilidade',
        text: 'Estrutura pronta para crescer.',
        icon: 'ES',
      },
    ],
    cards: [
      {
        title: 'Interior amplo',
        meta: 'Piso industrial e pe-direito livre.',
        image: landingImage.warehouseInside,
      },
      {
        title: 'Docas elevadas',
        meta: 'Operacao eficiente.',
        image: landingImage.warehouse,
      },
      {
        title: 'Video aereo',
        meta: 'Visao completa do ativo.',
        image: landingImage.map,
      },
      {
        title: 'Equipe tecnica',
        meta: 'Visita consultiva.',
        image: landingImage.broker,
      },
    ],
    formTitle: 'Receba mais informacoes',
    formSubtitle: 'Nosso time entra em contato com dados tecnicos.',
    faq: [
      'Disponivel para venda ou locacao?',
      'Qual o prazo minimo?',
      'O condominio esta incluso?',
      'Ha possibilidade de expansao?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-casa-aluguel',
    name: 'Villaggio Casa para Aluguel',
    description:
      'Tema completo para casa terrea de aluguel com tour 360, pet friendly, garantias e agenda.',
    thumbnail: refThumb('casa-aluguel.png'),
    group: 'Aluguel',
    category: 'Casa terrea',
    objective: 'Agendar visita',
    style: 'Residencial clean',
    palette: {
      primary: '#071837',
      secondary: '#f7f7fb',
      accent: '#d09a34',
      background: '#ffffff',
      text: '#0e1a34',
      footer: '#061633',
    },
    logo: 'VILLAGGIO IMOVEIS',
    badge: 'Para alugar',
    headline: 'Casa terrea moderna',
    highlight: 'para aluguel.',
    subtitle:
      'Casa pronta para morar com fotos, tour, garantias e agendamento em poucos cliques.',
    price: 'R$ 3.750 /mes',
    location: 'Jardim das Flores, Campinas - SP',
    primaryCta: 'Agendar visita',
    secondaryCta: 'Falar no WhatsApp',
    heroImage: landingImage.house,
    stats: [
      { label: 'Quartos', value: '3', icon: 'Q' },
      { label: 'Banheiros', value: '2', icon: 'B' },
      { label: 'Area', value: '120 m2', icon: 'A' },
      { label: 'Vagas', value: '2', icon: 'V' },
    ],
    features: [
      {
        title: 'Tour virtual',
        text: 'Ambientes navegaveis por comodo.',
        icon: '360',
      },
      {
        title: 'Pet friendly',
        text: 'Espaco para animais de pequeno porte.',
        icon: 'PET',
      },
      {
        title: 'Garantias',
        text: 'Seguro fianca, fiador e titulo.',
        icon: 'OK',
      },
      { title: 'Agenda', text: 'Presencial ou por video.', icon: 'AG' },
      { title: 'Corretor', text: 'Responsavel claro e acessivel.', icon: 'CR' },
    ],
    cards: [
      {
        title: 'Fachada moderna',
        meta: 'Jardim e garagem coberta.',
        image: landingImage.house,
      },
      {
        title: 'Sala de estar',
        meta: 'Tour 360 por ambientes.',
        image: landingImage.interior,
      },
      {
        title: 'Area gourmet',
        meta: 'Espaco externo completo.',
        image: landingImage.condo,
      },
      {
        title: 'Agenda de visita',
        meta: 'Fluxo em 4 etapas.',
        image: landingImage.broker,
      },
    ],
    formTitle: 'Agendar visita',
    formSubtitle: 'Escolha a melhor forma de conhecer seu proximo lar.',
    faq: [
      'O imovel aceita criancas?',
      'Quais sao as garantias aceitas?',
      'Posso fazer alteracoes?',
      'Como funciona visita por video?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-fazenda-produtiva',
    name: 'Fazenda Produtiva Venda',
    description:
      'Tema rural elegante para fazenda produtiva, ativos, video drone, benfeitorias e material completo.',
    thumbnail: refThumb('fazenda-produtiva.png'),
    group: 'Rural',
    category: 'Fazenda produtiva',
    objective: 'Receber material',
    style: 'Rural classico',
    palette: {
      primary: '#17381d',
      secondary: '#f4f0e4',
      accent: '#d5b562',
      background: '#fbf8ee',
      text: '#1f281b',
      footer: '#102516',
    },
    logo: 'IMOBILIARIA RURAL',
    badge: 'Oportunidade exclusiva',
    headline: 'Fazenda produtiva',
    highlight: 'a venda.',
    subtitle:
      'Ativo rural com produtividade comprovada, estrutura completa e documentacao para transferencia.',
    price: 'R$ 68.000.000',
    location: 'Campo Verde - MT',
    primaryCta: 'Falar no WhatsApp',
    secondaryCta: 'Receber material',
    heroImage: landingImage.farm,
    stats: [
      { label: 'Area total', value: '2.350 ha', icon: 'HA' },
      { label: 'Area aberta', value: '1.880 ha', icon: 'AB' },
      { label: 'Plantio', value: '1.720 ha', icon: 'PL' },
      { label: 'Topografia', value: 'Plana', icon: 'TP' },
    ],
    features: [
      {
        title: 'Produtividade',
        text: 'Historico de safras fortes.',
        icon: 'PR',
      },
      { title: 'Logistica', text: 'Acesso facil a armazens.', icon: 'LO' },
      {
        title: 'Recursos hidricos',
        text: 'Rios, represas e nascentes.',
        icon: 'AG',
      },
      {
        title: 'Documentacao',
        text: 'CAR, CCIR, SIGEF e matricula.',
        icon: 'DOC',
      },
      {
        title: 'Investimento',
        text: 'Liquidez e seguranca patrimonial.',
        icon: 'IN',
      },
    ],
    cards: [
      {
        title: 'Galeria da fazenda',
        meta: 'Talhoes, sede e estruturas.',
        image: landingImage.farm,
      },
      {
        title: 'Video aereo',
        meta: 'Drone para inspecao visual.',
        image: landingImage.crops,
      },
      {
        title: 'Benfeitorias',
        meta: 'Casa sede, curral e energia.',
        image: landingImage.house,
      },
      {
        title: 'Localizacao',
        meta: 'Mapa de rota e logistica.',
        image: landingImage.map,
      },
    ],
    formTitle: 'Receba o material completo',
    formSubtitle: 'Preencha seus dados e receba o dossie completo da fazenda.',
    faq: [
      'A fazenda esta arrendada?',
      'Qual a forma de pagamento?',
      'Aceita permuta?',
      'A documentacao esta em dia?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-urbana-casa-venda',
    name: 'Urbana Casa Venda',
    description:
      'Landing residencial de venda com hero impactante, galeria, mapa, diferenciais, depoimento e formulario.',
    thumbnail: refThumb('urbana-casa-venda.png'),
    group: 'Venda',
    category: 'Casa alto padrao',
    objective: 'Agendar visita',
    style: 'Residencial premium',
    palette: {
      primary: '#061a32',
      secondary: '#f9fafb',
      accent: '#bd8b3b',
      background: '#ffffff',
      text: '#101827',
      footer: '#061a32',
    },
    logo: 'URBANA IMOVEIS',
    badge: 'Casa a venda',
    headline: 'Sua nova historia',
    highlight: 'comeca aqui.',
    subtitle:
      'Conforto, design e localizacao privilegiada em uma casa pronta para morar.',
    price: 'R$ 1.290.000',
    location: 'Jardim das Flores, Campinas - SP',
    primaryCta: 'Falar no WhatsApp',
    secondaryCta: 'Agendar visita',
    heroImage: landingImage.mansion,
    stats: [
      { label: 'Quartos', value: '4', icon: 'Q' },
      { label: 'Suites', value: '2', icon: 'S' },
      { label: 'Area construida', value: '180 m2', icon: 'AC' },
      { label: 'Terreno', value: '250 m2', icon: 'AT' },
    ],
    features: [
      {
        title: 'Projeto moderno',
        text: 'Ambientes amplos e integrados.',
        icon: 'PM',
      },
      { title: 'Area gourmet', text: 'Conforto para receber.', icon: 'AG' },
      { title: 'Piscina', text: 'Lazer privativo.', icon: 'PI' },
      { title: 'Acabamentos', text: 'Materiais de alto padrao.', icon: 'AP' },
      { title: 'Seguranca', text: 'Portao e monitoramento.', icon: 'SG' },
    ],
    cards: [
      {
        title: 'Galeria de fotos',
        meta: 'Ambientes selecionados.',
        image: landingImage.interior,
      },
      {
        title: 'Localizacao',
        meta: 'Tudo perto de voce.',
        image: landingImage.map,
      },
      {
        title: 'Depoimentos',
        meta: 'Confianca de quem comprou.',
        image: landingImage.house,
      },
      {
        title: 'Contato',
        meta: 'Formulario e WhatsApp.',
        image: landingImage.broker,
      },
    ],
    formTitle: 'Interessado neste imovel?',
    formSubtitle: 'Preencha o formulario e receba mais informacoes.',
    faq: [
      'Aceita financiamento?',
      'Qual o valor do IPTU?',
      'O imovel esta averbado?',
      'E possivel comprar com FGTS?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-maison-vertice',
    name: 'Maison Vertice Residences',
    description:
      'Tema escuro ultra premium para empreendimento vertical, plantas, lazer, rooftop e visita privativa.',
    thumbnail: refThumb('maison-vertice.png'),
    group: 'Alto Padrao',
    category: 'Empreendimento vertical',
    objective: 'Agendar visita',
    style: 'Luxo escuro',
    palette: {
      primary: '#080909',
      secondary: '#17110c',
      accent: '#c49345',
      background: '#090909',
      text: '#f7efe5',
      footer: '#050505',
    },
    logo: 'MAISON VERTICE',
    badge: 'Lancamento exclusivo',
    headline: 'Apartamentos de alto padrao que',
    highlight: 'elevam seu estilo de viver.',
    subtitle:
      'Sofisticacao, conforto e localizacao privilegiada no coracao do bairro mais desejado.',
    price: 'A partir de R$ 2.950.000',
    location: 'Vila Nova Conceicao, Sao Paulo - SP',
    primaryCta: 'Agendar visita privativa',
    secondaryCta: 'Fale com consultor',
    heroImage: landingImage.luxuryApt,
    stats: [
      { label: 'Area privativa', value: '143 a 198 m2', icon: 'AP' },
      { label: 'Suites', value: '3 a 4', icon: 'ST' },
      { label: 'Vagas', value: '2 a 3', icon: 'VG' },
      { label: 'Torre', value: '28 pavimentos', icon: 'TR' },
    ],
    features: [
      { title: 'Lazer completo', text: 'Piscina, academia e spa.', icon: 'LZ' },
      {
        title: 'Galeria editorial',
        text: 'Ambientes de alto impacto visual.',
        icon: 'GL',
      },
      {
        title: 'Plantas inteligentes',
        text: 'Espacos pensados para cada momento.',
        icon: 'PL',
      },
      { title: 'Rooftop', text: 'Vista panoramica da cidade.', icon: 'RF' },
      { title: 'Visita privativa', text: 'Atendimento reservado.', icon: 'VP' },
    ],
    cards: [
      {
        title: 'Living panoramico',
        meta: 'Ambientes que inspiram.',
        image: landingImage.luxuryApt,
      },
      {
        title: 'Plantas',
        meta: 'Layouts flexiveis.',
        image: landingImage.interior,
      },
      {
        title: 'Rooftop',
        meta: 'Piscina e lounge.',
        image: landingImage.condo,
      },
      {
        title: 'Localizacao',
        meta: 'Vila Nova Conceicao.',
        image: landingImage.map,
      },
    ],
    formTitle: 'Receba mais informacoes',
    formSubtitle: 'Saiba tudo sobre o Maison Vertice.',
    faq: [
      'Qual o prazo de entrega?',
      'Como funciona a personalizacao?',
      'Quais sao as formas de pagamento?',
      'Ha unidades decoradas?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-vista-do-vale',
    name: 'Vista do Vale Lista VIP',
    description:
      'Pre-lancamento residencial com lista VIP, localizacao, plantas, lazer, obra e countdown.',
    thumbnail: refThumb('vista-do-vale.png'),
    group: 'Lancamentos',
    category: 'Residencial vertical',
    objective: 'Lista VIP',
    style: 'Lancamento premium',
    palette: {
      primary: '#064334',
      secondary: '#f9f3e8',
      accent: '#d8b16c',
      background: '#ffffff',
      text: '#17231f',
      footer: '#063a31',
    },
    logo: 'VISTA DO VALE',
    badge: 'Lancamento exclusivo',
    headline: 'O novo endereco dos seus melhores dias.',
    subtitle:
      'Apartamentos modernos em localizacao privilegiada, cercados de natureza e conveniencia.',
    location: 'Bairro em crescimento',
    primaryCta: 'Entrar para a lista VIP',
    secondaryCta: 'Ver plantas',
    heroImage: landingImage.launch,
    stats: [
      { label: 'Unidades', value: '2 e 3 dorms', icon: 'UN' },
      { label: 'Prioridade', value: 'Lista VIP', icon: 'VIP' },
      { label: 'Condicoes', value: 'Exclusivas', icon: 'CE' },
      { label: 'Cadastro', value: 'Online', icon: 'ON' },
    ],
    features: [
      { title: 'Localizacao', text: 'Conectado ao que importa.', icon: 'LC' },
      {
        title: 'Plantas',
        text: 'Espacos para diferentes momentos.',
        icon: 'PL',
      },
      {
        title: 'Lazer',
        text: 'Piscina, gourmet, academia e playground.',
        icon: 'LZ',
      },
      {
        title: 'Diferenciais',
        text: 'Arquitetura moderna e tecnologia.',
        icon: 'DF',
      },
      { title: 'Obra', text: 'Transparencia em cada etapa.', icon: 'OB' },
    ],
    cards: [
      {
        title: '2 dorms com suite',
        meta: '61 a 72 m2.',
        image: landingImage.interior,
      },
      {
        title: '3 dorms com suite',
        meta: '81 a 97 m2.',
        image: landingImage.house,
      },
      {
        title: 'Lazer completo',
        meta: 'Para toda familia.',
        image: landingImage.condo,
      },
      {
        title: 'Cronograma',
        meta: 'Acompanhe a obra.',
        image: landingImage.launch,
      },
    ],
    formTitle: 'Nao perca esta oportunidade unica',
    formSubtitle: 'Cadastre-se agora e receba em primeira mao as informacoes.',
    faq: [
      'Quando comecam as vendas?',
      'Como funciona a lista VIP?',
      'Quais sao as formas de pagamento?',
      'E possivel financiar?',
    ],
  }),
  buildElementorReferenceTemplate({
    id: 'elementor-bom-viver-mcmv',
    name: 'Residencial Bom Viver MCMV',
    description:
      'Landing popular Minha Casa Minha Vida com simulador, subsidio, FGTS, elegibilidade e agenda.',
    thumbnail: refThumb('bom-viver-mcmv.png'),
    group: 'Lancamentos',
    category: 'Minha Casa Minha Vida',
    objective: 'Simular financiamento',
    style: 'Popular confiavel',
    palette: {
      primary: '#2168bd',
      secondary: '#eff8ff',
      accent: '#22c55e',
      background: '#ffffff',
      text: '#13315c',
      footer: '#f8fafc',
    },
    logo: 'RESIDENCIAL BOM VIVER',
    badge: 'Lancamento Minha Casa Minha Vida',
    headline: 'Seu novo lar cabe no seu sonho',
    highlight: 'e no seu or├ºamento.',
    subtitle:
      'Apartamentos modernos, lazer completo e condicoes facilitadas pelo Minha Casa Minha Vida.',
    location: 'Jardim Esperanca, Sao Paulo - SP',
    primaryCta: 'Simular financiamento',
    secondaryCta: 'Agendar visita',
    heroImage: landingImage.family,
    stats: [
      { label: 'Quartos', value: '2', icon: 'Q' },
      { label: 'Lazer', value: 'Completo', icon: 'LZ' },
      { label: 'Seguranca', value: 'Fechado', icon: 'SG' },
      { label: 'Subsidio', value: 'Governo', icon: 'SB' },
    ],
    features: [
      {
        title: 'Subsidio',
        text: 'Desconto do governo conforme renda.',
        icon: 'SB',
      },
      {
        title: 'Use FGTS',
        text: 'Entrada ou amortizacao facilitada.',
        icon: 'FG',
      },
      { title: 'Entrada facilitada', text: 'Condicoes especiais.', icon: 'EN' },
      {
        title: 'Parcelas acessiveis',
        text: 'Planejamento familiar.',
        icon: 'PA',
      },
      {
        title: 'Elegibilidade',
        text: 'Checklist simples para simular.',
        icon: 'OK',
      },
    ],
    cards: [
      {
        title: 'Localizacao',
        meta: 'Rotina mais facil.',
        image: landingImage.map,
      },
      {
        title: 'Plantas',
        meta: '2 dormitorios inteligentes.',
        image: landingImage.interior,
      },
      {
        title: 'Agende visita',
        meta: 'Decorado com hora marcada.',
        image: landingImage.house,
      },
      {
        title: 'WhatsApp',
        meta: 'Atendimento rapido.',
        image: landingImage.family,
      },
    ],
    formTitle: 'Simule seu financiamento',
    formSubtitle: 'Rapido, gratuito e sem compromisso.',
    faq: [
      'Quem pode participar?',
      'Qual o valor do subsidio?',
      'Posso usar FGTS?',
      'Em quanto tempo posso me mudar?',
    ],
  }),
];
