import { buildDesignedTemplate, landingImage, designedSections } from './shared';

export const LOTEADORA_TEMPLATES = [
  buildDesignedTemplate({
    id: 'loteadora-masterplan',
    name: 'Loteamento Masterplan (Bairro Planejado)',
    description: 'Foco em infraestrutura completa, masterplan, praças e valorização urbana.',
    thumbnail: 'https://images.unsplash.com/photo-1572205336214-5d51d234ce5a?q=80&w=1920&auto=format&fit=crop',
    group: 'Loteadora',
    category: 'Bairro Planejado',
    objective: 'Venda de Lotes',
    style: 'Moderno e Urbano',
    resources: ['Mapa do Loteamento', 'Tour Virtual', 'WhatsApp'],
    pipeline: 'CRM Loteamentos',
    crmTags: ['loteamento', 'bairroplanejado', 'terreno'],
    conversionEvent: 'Agendar Visita',
    palette: {
      primary: '#059669',
      secondary: '#047857',
      accent: '#10b981',
      background: '#ecfdf5',
      text: '#064e3b',
      footer: '#064e3b',
    },
    logo: 'Novo Bairro',
    nav: ['O Projeto', 'Infraestrutura', 'Lotes', 'Financiamento'],
    badge: 'Obras Aceleradas',
    headline: 'O Novo Bairro Inteligente da',
    highlight: 'Sua Cidade',
    subtitle: 'Infraestrutura completa, áreas verdes e planejamento urbano de primeiro mundo. Construa a casa dos seus sonhos.',
    price: 'Parcelas a partir de R$ 899',
    location: 'Vetor de Crescimento',
    primaryCta: 'Falar com Consultor',
    secondaryCta: 'Ver Masterplan',
    heroImage: 'https://images.unsplash.com/photo-1572205336214-5d51d234ce5a?q=80&w=1920&auto=format&fit=crop',
    stats: [
      { label: 'Lotes', value: '450', icon: '📍' },
      { label: 'Área Verde', value: '30.000m²', icon: '🌳' },
      { label: 'Praças', value: '3', icon: '⛲' },
      { label: 'Comércio', value: 'Integrado', icon: '🛍️' },
    ],
    features: [
      { title: 'Asfalto e Iluminação', text: 'Ruas largas e iluminação em LED.', icon: '🛣️' },
      { title: 'Rede de Água e Esgoto', text: 'Infraestrutura 100% concluída.', icon: '💧' },
      { title: 'Parque Linear', text: 'Ciclovia e pista de caminhada.', icon: '🚴' },
      { title: 'Comércio Local', text: 'Área destinada para serviços e lojas.', icon: '🏪' },
      { title: 'Valorização', text: 'Região de maior crescimento da cidade.', icon: '📈' },
    ],
    cards: [
      { title: 'Infraestrutura', meta: 'Asfalto, água e luz', image: 'https://images.unsplash.com/photo-1572205336214-5d51d234ce5a?q=80&w=600&auto=format&fit=crop' },
      { title: 'Áreas Verdes', meta: 'Parques e praças', image: landingImage.farm },
      { title: 'Ciclovia', meta: 'Mobilidade urbana', image: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?q=80&w=600&auto=format&fit=crop' },
      { title: 'Lotes Comerciais', meta: 'Invista no seu negócio', image: landingImage.warehouse },
    ],
    sections: designedSections,
    formTitle: 'Invista no futuro da sua família',
    formSubtitle: 'Financiamento direto com a loteadora, sem burocracia.',
    faq: [
      'Qual o tamanho padrão dos lotes?',
      'Quando posso começar a construir?',
      'Como funciona o financiamento direto?',
    ],
  }),
  buildDesignedTemplate({
    id: 'loteadora-condominio-premium',
    name: 'Condomínio Fechado Premium',
    description: 'Lotes de alto padrão com ênfase em segurança, clube de lazer e exclusividade.',
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1920&auto=format&fit=crop',
    group: 'Loteadora',
    category: 'Condomínio Fechado',
    objective: 'Venda Alto Padrão',
    style: 'Exclusivo e Seguro',
    resources: ['Fotos do Clube', 'Regras Construtivas', 'WhatsApp'],
    pipeline: 'CRM Loteamentos',
    crmTags: ['condominio', 'altopadrao', 'seguranca'],
    conversionEvent: 'Agendar Visita',
    palette: {
      primary: '#111827',
      secondary: '#1f2937',
      accent: '#c026d3',
      background: '#f8fafc',
      text: '#111827',
      footer: '#111827',
    },
    logo: 'Royal Park',
    nav: ['O Condomínio', 'Clube Exclusivo', 'Segurança', 'Contato'],
    badge: 'Últimos Lotes',
    headline: 'Exclusividade e Segurança para',
    highlight: 'Construir sua Vida',
    subtitle: 'Um condomínio fechado com clube resort e segurança armada 24h. Lotes a partir de 500m².',
    price: 'A partir de R$ 350.000',
    location: 'Região Nobre',
    primaryCta: 'Agendar Visita Guiada',
    secondaryCta: 'Ver Estrutura do Clube',
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1920&auto=format&fit=crop',
    stats: [
      { label: 'Tamanho', value: '500m²', icon: '📐' },
      { label: 'Clube', value: '2.000m²', icon: '🏊' },
      { label: 'Segurança', value: '24h', icon: '🛡️' },
      { label: 'Obras', value: 'Pronto', icon: '🏗️' },
    ],
    features: [
      { title: 'Portaria Blindada', text: 'Controle de acesso rigoroso e biometria.', icon: '👮' },
      { title: 'Clube Resort', text: 'Piscina aquecida, quadras de tênis e academia.', icon: '🎾' },
      { title: 'Fiação Subterrânea', text: 'Estética impecável, sem fios aparentes.', icon: '⚡' },
      { title: 'Padrão Construtivo', text: 'Regras que garantem a valorização do condomínio.', icon: '📐' },
      { title: 'Natureza', text: 'Bosque privativo e lagos.', icon: '🌲' },
    ],
    cards: [
      { title: 'Portaria', meta: 'Imponente e segura', image: landingImage.condo },
      { title: 'Clube', meta: 'Lazer completo', image: 'https://images.unsplash.com/photo-1582610116397-edb318620f90?q=80&w=600&auto=format&fit=crop' },
      { title: 'Lotes', meta: 'Topografia excelente', image: landingImage.farm },
      { title: 'Inspiração', meta: 'Casas de alto padrão', image: landingImage.mansion },
    ],
    sections: designedSections,
    formTitle: 'Agende uma visita exclusiva',
    formSubtitle: 'Conheça o local perfeito para construir a casa dos seus sonhos.',
    faq: [
      'Quais são as regras construtivas?',
      'Qual o valor estimado do condomínio?',
      'A infraestrutura já está pronta?',
    ],
  }),
  buildDesignedTemplate({
    id: 'loteadora-popular',
    name: 'Loteamento Popular (Sem Entrada)',
    description: 'Foco em parcelas que cabem no bolso, aprovação rápida e sem burocracia.',
    thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1920&auto=format&fit=crop',
    group: 'Loteadora',
    category: 'Lote Popular',
    objective: 'Venda em Massa',
    style: 'Acessível e Direto',
    resources: ['Formulário Curto', 'WhatsApp'],
    pipeline: 'CRM Vendas Rápidas',
    crmTags: ['popular', 'sementrada', 'parcelado'],
    conversionEvent: 'Falar no WhatsApp',
    palette: {
      primary: '#b45309',
      secondary: '#d97706',
      accent: '#f59e0b',
      background: '#fffbeb',
      text: '#451a03',
      footer: '#78350f',
    },
    logo: 'Lote Fácil',
    nav: ['Vantagens', 'Localização', 'Pagamento', 'Dúvidas'],
    badge: 'Sem Consulta ao SPC/Serasa',
    headline: 'Seu Terreno Próprio',
    highlight: 'Sem Entrada e Sem Burocracia',
    subtitle: 'Saia do aluguel hoje mesmo. Compre seu terreno parcelado direto conosco, com aprovação na hora.',
    price: 'Parcelas de R$ 399',
    location: 'Bairro Novo',
    primaryCta: 'Chamar no WhatsApp',
    secondaryCta: 'Ver Localização',
    heroImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1920&auto=format&fit=crop',
    stats: [
      { label: 'Entrada', value: 'R$ 0', icon: '❌' },
      { label: 'Parcela', value: 'Fixa', icon: '💰' },
      { label: 'Aprovação', value: 'Na hora', icon: '⏱️' },
      { label: 'Infra', value: 'Água e Luz', icon: '💡' },
    ],
    features: [
      { title: 'Financiamento Próprio', text: 'Não precisa de banco, tudo direto conosco.', icon: '🤝' },
      { title: 'Sem Burocracia', text: 'Aprovação facilitada para autônomos.', icon: '📝' },
      { title: 'Infraestrutura Básica', text: 'Entregue com água encanada e energia.', icon: '🚰' },
      { title: 'Localização Acessível', text: 'Perto de transporte público e escolas.', icon: '🚌' },
      { title: 'Posse Imediata', text: 'Assinou o contrato, já pode construir.', icon: '🧱' },
    ],
    cards: [
      { title: 'Os Lotes', meta: 'Prontos para construir', image: landingImage.farm },
      { title: 'Obras Avançadas', meta: 'Máquinas trabalhando', image: landingImage.crops },
      { title: 'Localização', meta: 'Fácil acesso', image: landingImage.map },
      { title: 'Pagamento', meta: 'Carnê direto', image: landingImage.interior },
    ],
    sections: designedSections,
    formTitle: 'Garante o seu antes que acabe',
    formSubtitle: 'Deixe seu WhatsApp ou clique no botão abaixo para falar agora com um corretor.',
    faq: [
      'Posso comprar se tiver nome sujo?',
      'O que preciso para fechar negócio hoje?',
      'Já posso começar a construir a minha casa?',
    ],
  }),
  buildDesignedTemplate({
    id: 'loteadora-comercial-industrial',
    name: 'Terrenos Comerciais e Industriais',
    description: 'Áreas na beira de rodovias, lotes focados em investidores B2B e galpões.',
    thumbnail: landingImage.warehouse,
    group: 'Loteadora',
    category: 'Comercial/Industrial',
    objective: 'Vendas B2B',
    style: 'Corporativo e Técnico',
    resources: ['Plano Diretor', 'Dados Logísticos', 'WhatsApp'],
    pipeline: 'CRM Corporativo',
    crmTags: ['comercial', 'industrial', 'b2b'],
    conversionEvent: 'Agendar Reunião',
    palette: {
      primary: '#1e3a8a',
      secondary: '#1d4ed8',
      accent: '#2563eb',
      background: '#eff6ff',
      text: '#172554',
      footer: '#1e3a8a',
    },
    logo: 'Polo Logístico',
    nav: ['O Polo', 'Logística', 'Lotes', 'Contato'],
    badge: 'Lotes Industriais',
    headline: 'O Novo Eixo Logístico para a',
    highlight: 'Sua Empresa',
    subtitle: 'Lotes industriais e comerciais a partir de 1.000m² com infraestrutura de alta capacidade. Ao lado das principais rodovias.',
    price: 'Consulte Tabela Comercial',
    location: 'Rodovia BR-153, Km 42',
    primaryCta: 'Agendar Reunião Comercial',
    secondaryCta: 'Baixar Masterplan',
    heroImage: landingImage.warehouse,
    stats: [
      { label: 'Área Total', value: '1M m²', icon: '📐' },
      { label: 'Energia', value: 'Alta Tensão', icon: '⚡' },
      { label: 'Rodovia', value: 'Acesso Direto', icon: '🛣️' },
      { label: 'Zoneamento', value: 'ZPI', icon: '🏭' },
    ],
    features: [
      { title: 'Logística Perfeita', text: 'Entroncamento das principais rodovias do país.', icon: '🚛' },
      { title: 'Infraestrutura Pesada', text: 'Ruas preparadas para bitrens e carretas.', icon: '🏗️' },
      { title: 'Segurança', text: 'Balança rodoviária e portaria blindada.', icon: '🔒' },
      { title: 'Incentivos', text: 'Apoio fiscal da prefeitura local.', icon: '📜' },
      { title: 'Flexibilidade', text: 'Permite unificação de lotes para grandes galpões.', icon: '🏭' },
    ],
    cards: [
      { title: 'Galpões', meta: 'Áreas para construção', image: landingImage.warehouse },
      { title: 'Rodovias', meta: 'Acesso direto', image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=600&auto=format&fit=crop' },
      { title: 'Infra', meta: 'Ruas largas', image: 'https://images.unsplash.com/photo-1584824388190-67c26abaf987?q=80&w=600&auto=format&fit=crop' },
      { title: 'Logística', meta: 'Eficiência', image: landingImage.warehouseInside },
    ],
    sections: designedSections,
    formTitle: 'Expanda o seu negócio',
    formSubtitle: 'Fale com nossa equipe focada em soluções corporativas B2B.',
    faq: [
      'Qual o zoneamento exato?',
      'Há limites de construção e altura?',
      'Quais os incentivos fiscais disponíveis?',
    ],
  }),
  buildDesignedTemplate({
    id: 'loteadora-chacaras-recreio',
    name: 'Lotes em Chácaras de Recreio',
    description: 'Loteamentos rurais focados em descanso, natureza e lazer aos finais de semana.',
    thumbnail: landingImage.farm,
    group: 'Loteadora',
    category: 'Chácaras',
    objective: 'Venda de Lotes Rurais',
    style: 'Natural e Aconchegante',
    resources: ['Fotos da Natureza', 'WhatsApp'],
    pipeline: 'CRM Loteamentos',
    crmTags: ['chacara', 'recreio', 'lazer'],
    conversionEvent: 'Agendar Visita',
    palette: {
      primary: '#3f6212',
      secondary: '#4d7c0f',
      accent: '#65a30d',
      background: '#f7fee7',
      text: '#14532d',
      footer: '#14532d',
    },
    logo: 'Vale Verde',
    nav: ['O Loteamento', 'Natureza', 'Lazer', 'Contato'],
    badge: 'Chácaras de Lazer',
    headline: 'Sua Chácara Própria Perto da',
    highlight: 'Natureza',
    subtitle: 'Lotes a partir de 1.000m² cercados de muito verde, ar puro e tranquilidade para sua família aos finais de semana.',
    price: 'Entrada de R$ 5.000',
    location: 'Interior, a 50km da Capital',
    primaryCta: 'Agendar Visita no Fim de Semana',
    secondaryCta: 'Falar com Corretor',
    heroImage: landingImage.farm,
    stats: [
      { label: 'Lotes', value: '1.000m²', icon: '📐' },
      { label: 'Natureza', value: 'Lago', icon: '🌊' },
      { label: 'Distância', value: '45 min', icon: '🚗' },
      { label: 'Portaria', value: 'Controlada', icon: '🏡' },
    ],
    features: [
      { title: 'Muito Espaço', text: 'Lotes grandes para casa, piscina e pomar.', icon: '🌳' },
      { title: 'Lago para Pesca', text: 'Área de lazer comum com lago preservado.', icon: '🎣' },
      { title: 'Ar Puro', text: 'Fuja do stress da cidade grande.', icon: '🍃' },
      { title: 'Facilidade', text: 'Financiamento direto em até 120 meses.', icon: '🗓️' },
      { title: 'Segurança', text: 'Condomínio de chácaras com acesso restrito.', icon: '🔒' },
    ],
    cards: [
      { title: 'As Chácaras', meta: 'Espaço e liberdade', image: landingImage.farm },
      { title: 'O Lago', meta: 'Lazer e pesca', image: 'https://images.unsplash.com/photo-1544320953-ebbd1bbbbbe8?q=80&w=600&auto=format&fit=crop' },
      { title: 'Estradas', meta: 'Acesso cascalhado', image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=600&auto=format&fit=crop' },
      { title: 'Paz', meta: 'Tranquilidade', image: landingImage.house },
    ],
    sections: designedSections,
    formTitle: 'Venha passar o dia conosco',
    formSubtitle: 'Agende uma visita com sua família e conheça o local da sua futura chácara.',
    faq: [
      'Pode criar animais?',
      'Tem energia elétrica no lote?',
      'O financiamento tem consulta SPC?',
    ],
  }),
];
