import { LandingPageTemplate, buildPremiumTemplate, premiumBaseSections } from './shared';
export const PREMIUM_LANDING_PAGE_TEMPLATES: LandingPageTemplate[] = [
  buildPremiumTemplate({
    id: 'premium-casa-venda-urbana',
    name: 'Casa a Venda Completa',
    description: 'Landing premium para vender uma casa especifica com galeria, agenda, formulario, WhatsApp e CRM.',
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1920&auto=format&fit=crop',
    group: 'Urbana',
    category: 'Casa a venda',
    objective: 'Vender imovel',
    style: 'Moderno',
    resources: ['Agenda', 'WhatsApp', 'Formulario', 'Galeria', 'Mapa', 'CRM'],
    tags: ['casa', 'urbano', 'visita', 'venda'],
    pipeline: 'Pipeline Venda Urbana',
    crmTags: ['Lead Urbano', 'Agendou Visita', 'Formulario Enviado'],
    conversionEvent: 'lead_casa_venda',
    theme: { primaryColor: '#0f172a', secondaryColor: '#4f46e5' },
    heroTitle: 'Casa pronta para morar em localizacao desejada',
    heroSubtitle: 'Fotos grandes, dados completos, visita agendada e atendimento imediato pelo WhatsApp.',
    ctaText: 'Agendar visita',
    location: 'Campinas, Sao Paulo',
    stats: [{ label: 'Quartos', value: '4' }, { label: 'Suites', value: '2' }, { label: 'Vagas', value: '3' }, { label: 'Area', value: '280 m2' }],
    sections: premiumBaseSections,
    highlights: ['Piscina e area gourmet', 'Escritorio privativo', 'Moveis planejados', 'Financiamento e proposta pelo CRM'],
    formTitle: 'Tenho interesse nesta casa',
    formSubmit: 'Enviar interesse'
  }),
  buildPremiumTemplate({
    id: 'premium-apartamento-venda',
    name: 'Apartamento a Venda com Planta',
    description: 'Template para apartamento com condominio, lazer, planta, financiamento, mapa e agenda de visita.',
    thumbnail: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1920&auto=format&fit=crop',
    group: 'Urbana',
    category: 'Apartamento a venda',
    objective: 'Vender imovel',
    style: 'Premium',
    resources: ['Planta', 'Agenda', 'WhatsApp', 'Financiamento', 'Mapa', 'CRM'],
    tags: ['apartamento', 'condominio', 'planta'],
    pipeline: 'Pipeline Venda Urbana',
    crmTags: ['Lead Urbano', 'Lead Apartamento'],
    conversionEvent: 'lead_apartamento_venda',
    theme: { primaryColor: '#1e293b', secondaryColor: '#2563eb' },
    heroTitle: 'Apartamento com lazer completo e visita facil',
    heroSubtitle: 'Mostre preco, condominio, IPTU, planta, financiamento e disponibilidade em uma pagina pronta para converter.',
    ctaText: 'Ver horarios disponiveis',
    location: 'Florianopolis, Santa Catarina',
    stats: [{ label: 'Area privativa', value: '96 m2' }, { label: 'Quartos', value: '3' }, { label: 'Vagas', value: '2' }, { label: 'Andar', value: '12o' }],
    sections: premiumBaseSections,
    highlights: ['Lazer do condominio', 'Planta do imovel', 'Sol da manha/tarde', 'Simulacao de financiamento'],
    formTitle: 'Quero conhecer este apartamento',
    formSubmit: 'Solicitar atendimento'
  }),
  buildPremiumTemplate({
    id: 'premium-casa-alto-padrao',
    name: 'Casa de Alto Padrao Editorial',
    description: 'Pagina sofisticada para imoveis premium, com layout editorial, video, prova de autoridade e qualificacao financeira.',
    thumbnail: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1920&auto=format&fit=crop',
    group: 'Urbana',
    category: 'Alto padrao',
    objective: 'Vender imovel',
    style: 'Luxo',
    resources: ['Video', 'Galeria', 'Agenda exclusiva', 'Formulario qualificado', 'CRM'],
    tags: ['luxo', 'alto padrao', 'condominio'],
    pipeline: 'Pipeline Venda Urbana',
    crmTags: ['Lead Alto Padrao', 'Lead Qualificado'],
    conversionEvent: 'lead_luxo',
    theme: { primaryColor: '#111111', secondaryColor: '#c8a45d', fontFamily: 'Playfair Display' },
    heroTitle: 'Residencia exclusiva para uma vida sem concessoes',
    heroSubtitle: 'Fotos editoriais, ambientes amplos, seguranca, arquitetura e atendimento consultivo para compradores premium.',
    ctaText: 'Agendar visita exclusiva',
    location: 'Jardins, Sao Paulo',
    stats: [{ label: 'Area construida', value: '620 m2' }, { label: 'Suites', value: '5' }, { label: 'Vagas', value: '6' }, { label: 'Condominio', value: 'Fechado' }],
    sections: premiumBaseSections,
    highlights: ['Video cinematografico', 'Arquitetura assinada', 'Formulario com qualificacao financeira', 'Prova de autoridade do corretor'],
    formTitle: 'Solicitar apresentacao privada',
    formSubmit: 'Enviar solicitacao'
  }),
  buildPremiumTemplate({
    id: 'premium-imovel-comercial',
    name: 'Imovel Comercial Tecnico',
    description: 'Landing para salas, lojas e pontos comerciais com dados de zoneamento, fluxo, mapa e formulario empresarial.',
    thumbnail: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1920&auto=format&fit=crop',
    group: 'Urbana',
    category: 'Comercial',
    objective: 'Vender ou alugar imovel',
    style: 'Corporativo',
    resources: ['Mapa', 'Formulario empresarial', 'Agenda', 'Dados tecnicos', 'CRM'],
    tags: ['comercial', 'empresa', 'investidor'],
    pipeline: 'Pipeline Venda Urbana',
    crmTags: ['Lead Comercial'],
    conversionEvent: 'lead_comercial',
    theme: { primaryColor: '#0f172a', secondaryColor: '#0ea5e9' },
    heroTitle: 'Endereco comercial pronto para sua operacao',
    heroSubtitle: 'Metragem, zoneamento, fluxo de pessoas, vagas e agenda de visita em uma pagina objetiva.',
    ctaText: 'Agendar visita tecnica',
    location: 'Belo Horizonte, Minas Gerais',
    stats: [{ label: 'Area total', value: '480 m2' }, { label: 'Vagas', value: '12' }, { label: 'Pe-direito', value: '4,5 m' }, { label: 'Zoneamento', value: 'ZC' }],
    sections: premiumBaseSections,
    highlights: ['Dados comerciais completos', 'Pontos estrategicos proximos', 'Formulario para CNPJ', 'CRM com pipeline comercial'],
    formTitle: 'Solicitar analise comercial',
    formSubmit: 'Enviar dados'
  }),
  buildPremiumTemplate({
    id: 'premium-galpao-logistico',
    name: 'Galpao Logistico Venda ou Locacao',
    description: 'Template para galpoes com pe-direito, docas, patio, energia, mapa logistico e formulario de empresa.',
    thumbnail: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1920&auto=format&fit=crop',
    group: 'Urbana',
    category: 'Galpao',
    objective: 'Alugar imovel',
    style: 'Corporativo',
    resources: ['Mapa logistico', 'Agenda', 'Formulario empresarial', 'Video', 'CRM'],
    tags: ['galpao', 'logistica', 'locacao'],
    pipeline: 'Pipeline Aluguel',
    crmTags: ['Lead Aluguel', 'Lead Comercial'],
    conversionEvent: 'lead_galpao',
    theme: { primaryColor: '#1f2937', secondaryColor: '#f59e0b' },
    heroTitle: 'Galpao com infraestrutura para alta operacao',
    heroSubtitle: 'Docas, patio, acesso para caminhoes, escritorios e dados tecnicos claros para decisao rapida.',
    ctaText: 'Falar com especialista',
    location: 'Contagem, Minas Gerais',
    stats: [{ label: 'Area construida', value: '4.800 m2' }, { label: 'Docas', value: '8' }, { label: 'Patio', value: '6.000 m2' }, { label: 'Energia', value: 'Trifasica' }],
    sections: premiumBaseSections,
    highlights: ['Acesso rodoviario', 'Mapa logistico', 'Pe-direito operacional', 'Formulario para demanda empresarial'],
    formTitle: 'Tenho interesse no galpao',
    formSubmit: 'Solicitar visita'
  }),
  buildPremiumTemplate({
    id: 'premium-lote-urbano',
    name: 'Lote Urbano com Mapa e Documentacao',
    description: 'Landing para lote ou terreno urbano com imagem aerea, zoneamento, potencial construtivo e documentacao.',
    thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1920&auto=format&fit=crop',
    group: 'Lotes',
    category: 'Lote urbano',
    objective: 'Vender lote',
    style: 'Moderno',
    resources: ['Mapa', 'Documentacao', 'WhatsApp', 'Agenda', 'CRM'],
    tags: ['lote', 'terreno', 'zoneamento'],
    pipeline: 'Pipeline Venda Urbana',
    crmTags: ['Lead Lote'],
    conversionEvent: 'lead_lote_urbano',
    theme: { primaryColor: '#065f46', secondaryColor: '#facc15' },
    heroTitle: 'Terreno urbano com potencial construtivo',
    heroSubtitle: 'Metragem, frente, fundos, zoneamento, mapa e contato direto para proposta.',
    ctaText: 'Escolher meu lote',
    location: 'Goiania, Goias',
    stats: [{ label: 'Metragem', value: '600 m2' }, { label: 'Frente', value: '15 m' }, { label: 'Zoneamento', value: 'Misto' }, { label: 'Documentacao', value: 'OK' }],
    sections: premiumBaseSections,
    highlights: ['Imagem aerea', 'Potencial construtivo', 'Proximidades', 'Documentacao em destaque'],
    formTitle: 'Quero detalhes deste lote',
    formSubmit: 'Receber informacoes'
  }),
  buildPremiumTemplate({
    id: 'premium-pre-lancamento-vip',
    name: 'Pre-Lancamento Lista VIP',
    description: 'Pagina para capturar interessados antes do lancamento oficial com beneficios, contador e lista VIP.',
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1920&auto=format&fit=crop',
    group: 'Lancamentos',
    category: 'Pre-lancamento',
    objective: 'Entrar em lista VIP',
    style: 'Premium',
    resources: ['Lista VIP', 'Formulario curto', 'WhatsApp', 'CRM', 'SEO'],
    tags: ['lancamento', 'lista vip', 'trafego pago'],
    pipeline: 'Pipeline Lancamentos',
    crmTags: ['Lead Lancamento', 'Lista VIP'],
    conversionEvent: 'lead_lista_vip',
    theme: { primaryColor: '#312e81', secondaryColor: '#a78bfa' },
    heroTitle: 'Entre primeiro na lista VIP do novo lancamento',
    heroSubtitle: 'Receba condicoes antecipadas, plantas e prioridade de escolha antes da abertura oficial.',
    ctaText: 'Entrar na Lista VIP',
    location: 'Balneario Camboriu, Santa Catarina',
    stats: [{ label: 'Prioridade', value: 'VIP' }, { label: 'Tipologias', value: '2 e 3 dorms' }, { label: 'Condicoes', value: 'Antecipadas' }, { label: 'Atendimento', value: 'Plantao' }],
    sections: premiumBaseSections,
    highlights: ['Formulario curto', 'Beneficios de entrar antes', 'Localizacao do empreendimento', 'CRM para campanha'],
    formTitle: 'Quero entrar na lista VIP',
    formSubmit: 'Garantir prioridade'
  }),
  buildPremiumTemplate({
    id: 'premium-lancamento-padrao',
    name: 'Lancamento Imobiliario Completo',
    description: 'Pagina de empreendimento com renders, plantas, tipologias, financiamento, agenda e tabela de unidades.',
    thumbnail: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1920&auto=format&fit=crop',
    group: 'Lancamentos',
    category: 'Lancamento',
    objective: 'Vender unidades',
    style: 'Moderno',
    resources: ['Plantas', 'Tabela de unidades', 'Agenda', 'Simulacao', 'CRM'],
    tags: ['empreendimento', 'construtora', 'unidades'],
    pipeline: 'Pipeline Lancamentos',
    crmTags: ['Lead Lancamento'],
    conversionEvent: 'lead_lancamento',
    theme: { primaryColor: '#0f172a', secondaryColor: '#22c55e' },
    heroTitle: 'Novo empreendimento com unidades selecionadas',
    heroSubtitle: 'Renders, plantas, diferenciais, localizacao e atendimento com consultor em uma landing completa.',
    ctaText: 'Conhecer unidades',
    location: 'Curitiba, Parana',
    stats: [{ label: 'Torres', value: '2' }, { label: 'Plantas', value: '6' }, { label: 'Entrega', value: '2028' }, { label: 'Unidades', value: 'Limitadas' }],
    sections: premiumBaseSections,
    highlights: ['Tipologias e plantas', 'Tabela de unidades', 'Simulacao de financiamento', 'Agenda com corretor'],
    formTitle: 'Quero conhecer o empreendimento',
    formSubmit: 'Receber plantas'
  }),
  buildPremiumTemplate({
    id: 'premium-lancamento-luxo',
    name: 'Lancamento de Luxo Editorial',
    description: 'Landing sofisticada para empreendimento premium com manifesto, arquitetura, servicos exclusivos e apresentacao privada.',
    thumbnail: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1920&auto=format&fit=crop',
    group: 'Lancamentos',
    category: 'Lancamento de luxo',
    objective: 'Captar lead qualificado',
    style: 'Luxo',
    resources: ['Video', 'Galeria premium', 'Formulario qualificado', 'Agenda privada', 'CRM'],
    tags: ['luxo', 'incorporadora', 'alto padrao'],
    pipeline: 'Pipeline Lancamentos',
    crmTags: ['Lead Alto Padrao', 'Lead Lancamento'],
    conversionEvent: 'lead_lancamento_luxo',
    theme: { primaryColor: '#0b0b0b', secondaryColor: '#b68d40', fontFamily: 'Playfair Display' },
    heroTitle: 'Um endereco para quem escolhe o extraordinario',
    heroSubtitle: 'Arquitetura assinada, servicos exclusivos, plantas amplas e atendimento reservado.',
    ctaText: 'Agendar apresentacao privada',
    location: 'Ipanema, Rio de Janeiro',
    stats: [{ label: 'Plantas', value: '280 m2+' }, { label: 'Suites', value: '4' }, { label: 'Rooftop', value: 'Exclusivo' }, { label: 'Entrega', value: '2027' }],
    sections: premiumBaseSections,
    highlights: ['Manifesto do empreendimento', 'Arquitetura assinada', 'Servicos exclusivos', 'Qualificacao financeira'],
    formTitle: 'Solicitar atendimento consultivo',
    formSubmit: 'Enviar solicitacao'
  }),
  buildPremiumTemplate({
    id: 'premium-minha-casa-minha-vida',
    name: 'Minha Casa Minha Vida Conversao',
    description: 'Pagina clara e direta para simular financiamento, captar renda familiar, FGTS e documentos necessarios.',
    thumbnail: 'https://images.unsplash.com/photo-1597047084897-51e81819a499?q=80&w=1920&auto=format&fit=crop',
    group: 'Lancamentos',
    category: 'Minha Casa Minha Vida',
    objective: 'Simular financiamento',
    style: 'Popular',
    resources: ['Simulacao', 'Formulario renda', 'WhatsApp', 'Agenda', 'CRM'],
    tags: ['mcmv', 'financiamento', 'fgts'],
    pipeline: 'Pipeline Minha Casa Minha Vida',
    crmTags: ['Lead Minha Casa Minha Vida'],
    conversionEvent: 'lead_mcmv',
    theme: { primaryColor: '#2563eb', secondaryColor: '#10b981' },
    heroTitle: 'Seu apartamento com entrada facilitada',
    heroSubtitle: 'Simule seu financiamento, veja beneficios, use FGTS e fale com um consultor.',
    ctaText: 'Simular meu financiamento',
    location: 'Sao Jose dos Pinhais, Parana',
    stats: [{ label: 'Entrada', value: 'Facilitada' }, { label: 'FGTS', value: 'Aceito' }, { label: 'Subsidio', value: 'Disponivel' }, { label: 'Parcelas', value: 'Acessiveis' }],
    sections: premiumBaseSections,
    highlights: ['Renda familiar', 'Documentos necessarios', 'Quem pode comprar', 'Agenda com consultor'],
    formTitle: 'Quero simular meu financiamento',
    formSubmit: 'Simular agora'
  }),
  buildPremiumTemplate({
    id: 'premium-venda-lotes',
    name: 'Venda de Lotes com Mapa',
    description: 'Template para loteamento com quadras, infraestrutura, condicoes, agenda de visita e CRM.',
    thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1920&auto=format&fit=crop',
    group: 'Lotes',
    category: 'Loteamento',
    objective: 'Vender lote',
    style: 'Rural',
    resources: ['Mapa do loteamento', 'Agenda', 'Formulario', 'WhatsApp', 'CRM'],
    tags: ['loteamento', 'quadras', 'infraestrutura'],
    pipeline: 'Pipeline Lancamentos',
    crmTags: ['Lead Lote'],
    conversionEvent: 'lead_loteamento',
    theme: { primaryColor: '#064e3b', secondaryColor: '#eab308' },
    heroTitle: 'Escolha seu lote em uma regiao em crescimento',
    heroSubtitle: 'Infraestrutura completa, mapa do loteamento, metragens e atendimento para escolher a melhor quadra.',
    ctaText: 'Escolher meu lote',
    location: 'Ribeirao Preto, Sao Paulo',
    stats: [{ label: 'Lotes', value: '360 m2+' }, { label: 'Infraestrutura', value: 'Completa' }, { label: 'Entrada', value: 'Facilitada' }, { label: 'Visita', value: 'No local' }],
    sections: premiumBaseSections,
    highlights: ['Quadras e lotes', 'Agua, luz e pavimentacao', 'Area verde', 'Condicoes de pagamento'],
    formTitle: 'Quero escolher um lote',
    formSubmit: 'Receber opcoes'
  }),
  buildPremiumTemplate({
    id: 'premium-casa-aluguel',
    name: 'Casa para Aluguel com Agenda',
    description: 'Landing de locacao com regras, garantias, tour virtual, agenda presencial/video e pre-analise.',
    thumbnail: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1920&auto=format&fit=crop',
    group: 'Aluguel',
    category: 'Casa para aluguel',
    objective: 'Alugar imovel',
    style: 'Moderno',
    resources: ['Tour virtual', 'Agenda', 'Formulario', 'WhatsApp', 'CRM'],
    tags: ['aluguel', 'casa', 'garantia'],
    pipeline: 'Pipeline Aluguel',
    crmTags: ['Lead Aluguel'],
    conversionEvent: 'lead_aluguel_casa',
    theme: { primaryColor: '#0f766e', secondaryColor: '#14b8a6' },
    heroTitle: 'Casa para alugar com visita sem friccao',
    heroSubtitle: 'Valor, regras, garantias aceitas, tour virtual e agendamento em poucos cliques.',
    ctaText: 'Agendar visita',
    location: 'Londrina, Parana',
    stats: [{ label: 'Aluguel', value: 'R$ 3.800' }, { label: 'Quartos', value: '3' }, { label: 'Pets', value: 'Aceita' }, { label: 'Visita', value: 'Online ou presencial' }],
    sections: premiumBaseSections,
    highlights: ['Garantias aceitas', 'Tour estilo Google', 'Pre-analise opcional', 'Agenda presencial ou video'],
    formTitle: 'Quero visitar este imovel',
    formSubmit: 'Agendar visita'
  }),
  buildPremiumTemplate({
    id: 'premium-apartamento-aluguel',
    name: 'Apartamento para Aluguel Completo',
    description: 'Template de locacao para apartamento com condominio, IPTU, lazer, regras e agenda.',
    thumbnail: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1920&auto=format&fit=crop',
    group: 'Aluguel',
    category: 'Apartamento para aluguel',
    objective: 'Alugar imovel',
    style: 'Premium',
    resources: ['Tour virtual', 'Agenda', 'Formulario', 'Mapa', 'CRM'],
    tags: ['aluguel', 'apartamento', 'condominio'],
    pipeline: 'Pipeline Aluguel',
    crmTags: ['Lead Aluguel'],
    conversionEvent: 'lead_aluguel_apartamento',
    theme: { primaryColor: '#334155', secondaryColor: '#38bdf8' },
    heroTitle: 'Apartamento para alugar com informacao completa',
    heroSubtitle: 'Condominio, IPTU, lazer, garantias, tour virtual e WhatsApp para atendimento imediato.',
    ctaText: 'Ver agenda de visita',
    location: 'Porto Alegre, Rio Grande do Sul',
    stats: [{ label: 'Aluguel', value: 'R$ 2.600' }, { label: 'Condominio', value: 'R$ 640' }, { label: 'Quartos', value: '2' }, { label: 'Vaga', value: '1' }],
    sections: premiumBaseSections,
    highlights: ['Lazer do condominio', 'Regras de locacao', 'Garantias aceitas', 'Formulario de interesse'],
    formTitle: 'Tenho interesse no aluguel',
    formSubmit: 'Solicitar visita'
  }),
  buildPremiumTemplate({
    id: 'premium-aluguel-tour-virtual',
    name: 'Aluguel com Tour Virtual 360',
    description: 'Pagina focada em tour 360 com ambientes, botoes de visita presencial/video e evento para CRM.',
    thumbnail: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=1920&auto=format&fit=crop',
    group: 'Aluguel',
    category: 'Tour virtual',
    objective: 'Agendar visita',
    style: 'Moderno',
    resources: ['Tour 360', 'Agenda video', 'WhatsApp', 'Formulario', 'CRM'],
    tags: ['tour 360', 'visita virtual', 'locacao'],
    pipeline: 'Pipeline Aluguel',
    crmTags: ['Abriu Tour Virtual', 'Lead Aluguel'],
    conversionEvent: 'lead_tour_virtual',
    theme: { primaryColor: '#155e75', secondaryColor: '#06b6d4' },
    heroTitle: 'Visite o imovel online antes de sair de casa',
    heroSubtitle: 'Tour por ambientes, fotos complementares, video curto e agendamento presencial ou por video.',
    ctaText: 'Abrir tour virtual',
    location: 'Santos, Sao Paulo',
    stats: [{ label: 'Ambientes', value: '5' }, { label: 'Tour', value: '360' }, { label: 'Video', value: 'Incluido' }, { label: 'Agenda', value: 'Online' }],
    sections: premiumBaseSections,
    highlights: ['Navegacao por comodos', 'Botao gostei deste imovel', 'Agendar visita por video', 'Registro de eventos no CRM'],
    formTitle: 'Gostei deste imovel',
    formSubmit: 'Falar com corretor'
  }),
  buildPremiumTemplate({
    id: 'premium-fazenda-venda',
    name: 'Fazenda a Venda Dossie Completo',
    description: 'Pagina rural completa com hectares, CAR, CCIR, SIGEF, benfeitorias, recursos hidricos, mapa e dossie.',
    thumbnail: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1920&auto=format&fit=crop',
    group: 'Rural',
    category: 'Fazenda a venda',
    objective: 'Receber material',
    style: 'Rural',
    resources: ['Dossie tecnico', 'Mapa rural', 'Drone', 'Agenda tecnica', 'CRM'],
    tags: ['fazenda', 'rural', 'dossie'],
    pipeline: 'Pipeline Rural',
    crmTags: ['Lead Rural', 'Lead Fazenda'],
    conversionEvent: 'lead_fazenda',
    theme: { primaryColor: '#064e3b', secondaryColor: '#d4af37' },
    heroTitle: 'Fazenda completa com informacoes tecnicas reais',
    heroSubtitle: 'Area total, documentacao, recursos hidricos, benfeitorias, logistica e visita tecnica.',
    ctaText: 'Receber dossie completo',
    location: 'Sorriso, Mato Grosso',
    stats: [{ label: 'Area total', value: '1.250 ha' }, { label: 'Area aberta', value: '820 ha' }, { label: 'CAR/CCIR', value: 'OK' }, { label: 'Agua', value: 'Nascentes' }],
    sections: premiumBaseSections,
    highlights: ['CAR, CCIR, SIGEF e matricula', 'Video com drone', 'Casa sede, curral e barracao', 'Logistica e documentacao'],
    formTitle: 'Quero receber o dossie da fazenda',
    formSubmit: 'Receber material'
  }),
  buildPremiumTemplate({
    id: 'premium-fazenda-pecuaria',
    name: 'Fazenda para Pecuaria',
    description: 'Landing rural para pecuaria com capacidade animal, pastos, curral, agua, cercas e visita tecnica.',
    thumbnail: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?q=80&w=1920&auto=format&fit=crop',
    group: 'Rural',
    category: 'Pecuaria',
    objective: 'Agendar visita tecnica',
    style: 'Rural',
    resources: ['Drone', 'Mapa rural', 'Formulario qualificado', 'Agenda tecnica', 'CRM'],
    tags: ['pecuaria', 'gado', 'pastagem'],
    pipeline: 'Pipeline Rural',
    crmTags: ['Lead Rural', 'Pecuaria'],
    conversionEvent: 'lead_pecuaria',
    theme: { primaryColor: '#365314', secondaryColor: '#84cc16' },
    heroTitle: 'Area formada para pecuaria com logistica forte',
    heroSubtitle: 'Capacidade animal, divisao de pastos, curral, agua, cercas e proximidade de frigorificos.',
    ctaText: 'Agendar visita tecnica',
    location: 'Rondonopolis, Mato Grosso',
    stats: [{ label: 'Lotacao', value: '1.800 cab.' }, { label: 'Pastos', value: '32' }, { label: 'Curral', value: 'Completo' }, { label: 'Agua', value: 'Perenne' }],
    sections: premiumBaseSections,
    highlights: ['Capacidade animal', 'Tipo de pastagem', 'Frigorificos proximos', 'Formulario para comprador rural'],
    formTitle: 'Quero avaliar esta fazenda',
    formSubmit: 'Solicitar visita'
  }),
  buildPremiumTemplate({
    id: 'premium-fazenda-plantio',
    name: 'Fazenda para Plantio',
    description: 'Template para areas de soja, milho e graos com solo, relevo, altitude, pluviometria e cooperativas proximas.',
    thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1920&auto=format&fit=crop',
    group: 'Rural',
    category: 'Plantio',
    objective: 'Receber dossie tecnico',
    style: 'Rural',
    resources: ['Dossie tecnico', 'Mapa', 'Drone', 'Formulario', 'CRM'],
    tags: ['plantio', 'soja', 'milho'],
    pipeline: 'Pipeline Rural',
    crmTags: ['Lead Rural', 'Plantio'],
    conversionEvent: 'lead_plantio',
    theme: { primaryColor: '#166534', secondaryColor: '#f59e0b' },
    heroTitle: 'Area agricultavel com dados para decisao tecnica',
    heroSubtitle: 'Solo, relevo, altitude, indice pluviometrico, safras possiveis e logistica de escoamento.',
    ctaText: 'Receber dossie da area',
    location: 'Luis Eduardo Magalhaes, Bahia',
    stats: [{ label: 'Agricultavel', value: '2.400 ha' }, { label: 'Altitude', value: '780 m' }, { label: 'Solo', value: 'Argiloso' }, { label: 'Safras', value: '2/ano' }],
    sections: premiumBaseSections,
    highlights: ['Cooperativas proximas', 'Rodovias', 'Armazens', 'Documentacao rural'],
    formTitle: 'Quero o estudo da area',
    formSubmit: 'Solicitar dossie'
  }),
  buildPremiumTemplate({
    id: 'premium-sitio-chacara',
    name: 'Sitio ou Chacara Emocional',
    description: 'Pagina para lazer rural com fotos grandes, piscina, lago, pomar, distancia da cidade e agenda.',
    thumbnail: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=1920&auto=format&fit=crop',
    group: 'Rural',
    category: 'Sitio e chacara',
    objective: 'Agendar visita',
    style: 'Rural',
    resources: ['Galeria', 'Tour virtual', 'WhatsApp', 'Agenda', 'CRM'],
    tags: ['sitio', 'chacara', 'lazer'],
    pipeline: 'Pipeline Rural',
    crmTags: ['Lead Rural', 'Lazer'],
    conversionEvent: 'lead_chacara',
    theme: { primaryColor: '#0f766e', secondaryColor: '#f97316' },
    heroTitle: 'Seu refugio perto da cidade',
    heroSubtitle: 'Casa, piscina, lago, pomar, area gourmet e visita agendada para sentir o lugar.',
    ctaText: 'Agendar visita',
    location: 'Atibaia, Sao Paulo',
    stats: [{ label: 'Area', value: '20.000 m2' }, { label: 'Casa', value: '4 quartos' }, { label: 'Lazer', value: 'Completo' }, { label: 'Distancia', value: '18 km' }],
    sections: premiumBaseSections,
    highlights: ['Fotos grandes', 'Mapa e distancia da cidade', 'Tour virtual', 'FAQ para lazer rural'],
    formTitle: 'Quero conhecer esta chacara',
    formSubmit: 'Marcar visita'
  }),
  buildPremiumTemplate({
    id: 'premium-area-rural-investimento',
    name: 'Area Rural para Investimento',
    description: 'Landing para investidores com potencial produtivo, loteamento, valorizacao, localizacao estrategica e estudo completo.',
    thumbnail: 'https://images.unsplash.com/photo-1492496913980-501348b61469?q=80&w=1920&auto=format&fit=crop',
    group: 'Rural',
    category: 'Investimento rural',
    objective: 'Receber material',
    style: 'Corporativo',
    resources: ['Estudo completo', 'Mapa', 'Formulario qualificado', 'CRM', 'Analytics'],
    tags: ['investimento', 'valorizacao', 'area rural'],
    pipeline: 'Pipeline Rural',
    crmTags: ['Lead Rural', 'Investidor'],
    conversionEvent: 'lead_investimento_rural',
    theme: { primaryColor: '#1f2937', secondaryColor: '#22c55e' },
    heroTitle: 'Area rural com tese clara de valorizacao',
    heroSubtitle: 'Potencial de uso, loteamento, producao, logistica e analise para investidores.',
    ctaText: 'Receber estudo completo',
    location: 'Campo Grande, Mato Grosso do Sul',
    stats: [{ label: 'Area', value: '5.000 ha' }, { label: 'Rodovia', value: '12 km' }, { label: 'Potencial', value: 'Alto' }, { label: 'Documento', value: 'Regular' }],
    sections: premiumBaseSections,
    highlights: ['Potencial de loteamento', 'Analise de valorizacao', 'Localizacao estrategica', 'Formulario para investidor'],
    formTitle: 'Quero analisar esta oportunidade',
    formSubmit: 'Receber estudo'
  }),
  buildPremiumTemplate({
    id: 'premium-captacao-proprietario-rural',
    name: 'Captacao de Proprietarios Rurais',
    description: 'Pagina para captar donos de fazendas com avaliacao, sigilo, analise documental e prova de autoridade.',
    thumbnail: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1920&auto=format&fit=crop',
    group: 'Captacao',
    category: 'Captacao rural',
    objective: 'Captar proprietario',
    style: 'Rural',
    resources: ['Formulario qualificado', 'LGPD', 'WhatsApp', 'CRM', 'Pipeline captacao'],
    tags: ['captacao', 'proprietario', 'fazenda'],
    pipeline: 'Pipeline Captacao de Imoveis',
    crmTags: ['Proprietario Rural', 'Captacao de Imovel'],
    conversionEvent: 'lead_vender_fazenda',
    theme: { primaryColor: '#064e3b', secondaryColor: '#d97706' },
    heroTitle: 'Quer vender sua fazenda com seguranca?',
    heroSubtitle: 'Avaliacao de mercado, analise documental, divulgacao qualificada e atendimento sigiloso.',
    ctaText: 'Enviar minha propriedade',
    location: 'Brasil',
    stats: [{ label: 'Sigilo', value: 'Total' }, { label: 'Avaliacao', value: 'Tecnica' }, { label: 'CRM', value: 'Captacao' }, { label: 'Atendimento', value: 'Especializado' }],
    sections: premiumBaseSections,
    highlights: ['Como funciona', 'Analise documental', 'Divulgacao qualificada', 'Prova de autoridade'],
    formTitle: 'Quero avaliar minha fazenda',
    formSubmit: 'Enviar propriedade'
  }),
  buildPremiumTemplate({
    id: 'premium-quero-comprar-imovel',
    name: 'Captacao Quero Comprar Imovel',
    description: 'Pagina de captura para compradores urbanos com cidade, tipo, faixa de investimento e prazo de compra.',
    thumbnail: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1920&auto=format&fit=crop',
    group: 'Captacao',
    category: 'Compradores',
    objective: 'Captar comprador',
    style: 'Moderno',
    resources: ['Formulario qualificado', 'WhatsApp', 'CRM', 'Pipeline venda', 'LGPD'],
    tags: ['comprador', 'lead urbano', 'captacao'],
    pipeline: 'Pipeline Venda Urbana',
    crmTags: ['Lead Urbano', 'Comprador'],
    conversionEvent: 'lead_quero_comprar',
    theme: { primaryColor: '#4f46e5', secondaryColor: '#06b6d4' },
    heroTitle: 'Encontre o imovel certo sem perder tempo',
    heroSubtitle: 'Informe cidade, perfil, faixa de investimento e receba oportunidades compativeis.',
    ctaText: 'Receber oportunidades',
    location: 'Brasil',
    stats: [{ label: 'Tipo', value: 'Casa/Apto' }, { label: 'Faixa', value: 'Personalizada' }, { label: 'CRM', value: 'Automatico' }, { label: 'Contato', value: 'WhatsApp' }],
    sections: premiumBaseSections,
    highlights: ['Campos dinamicos por perfil', 'Tags automaticas', 'Funil de venda urbana', 'Mensagem de WhatsApp pronta'],
    formTitle: 'Quero comprar um imovel',
    formSubmit: 'Enviar perfil'
  }),
  buildPremiumTemplate({
    id: 'premium-quero-vender-imovel',
    name: 'Captacao Quero Vender Meu Imovel',
    description: 'Landing para proprietarios urbanos com avaliacao, urgencia, situacao documental e pipeline de captacao.',
    thumbnail: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1920&auto=format&fit=crop',
    group: 'Captacao',
    category: 'Vendedores',
    objective: 'Captar vendedor',
    style: 'Institucional',
    resources: ['Avaliacao gratuita', 'Formulario qualificado', 'WhatsApp', 'CRM', 'LGPD'],
    tags: ['vendedor', 'captacao', 'avaliacao'],
    pipeline: 'Pipeline Captacao de Imoveis',
    crmTags: ['Proprietario Urbano', 'Captacao de Imovel'],
    conversionEvent: 'lead_vender_imovel',
    theme: { primaryColor: '#0f172a', secondaryColor: '#f97316' },
    heroTitle: 'Venda seu imovel com estrategia e seguranca',
    heroSubtitle: 'Receba avaliacao, plano de divulgacao e atendimento consultivo para captar compradores qualificados.',
    ctaText: 'Avaliar meu imovel',
    location: 'Brasil',
    stats: [{ label: 'Avaliacao', value: 'Gratuita' }, { label: 'Divulgacao', value: 'Qualificada' }, { label: 'CRM', value: 'Captacao' }, { label: 'LGPD', value: 'Inclusa' }],
    sections: premiumBaseSections,
    highlights: ['Valor estimado', 'Situacao documental', 'Urgencia de venda', 'Pipeline de captacao'],
    formTitle: 'Quero vender meu imovel',
    formSubmit: 'Solicitar avaliacao'
  }),
  buildPremiumTemplate({
    id: 'premium-quero-comprar-fazenda',
    name: 'Captacao Quero Comprar Fazenda',
    description: 'Pagina para comprador rural com estado desejado, area, finalidade, investimento e prazo.',
    thumbnail: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?q=80&w=1920&auto=format&fit=crop',
    group: 'Captacao',
    category: 'Comprador rural',
    objective: 'Captar comprador rural',
    style: 'Rural',
    resources: ['Formulario rural', 'WhatsApp', 'CRM', 'Pipeline rural', 'LGPD'],
    tags: ['comprar fazenda', 'rural', 'investidor'],
    pipeline: 'Pipeline Rural',
    crmTags: ['Lead Rural', 'Comprador Rural'],
    conversionEvent: 'lead_comprar_fazenda',
    theme: { primaryColor: '#14532d', secondaryColor: '#ca8a04' },
    heroTitle: 'Receba fazendas compativeis com sua estrategia',
    heroSubtitle: 'Informe estado, area, finalidade, investimento e prazo para receber oportunidades qualificadas.',
    ctaText: 'Receber fazendas',
    location: 'Brasil',
    stats: [{ label: 'Finalidade', value: 'Pecuaria/Plantio' }, { label: 'Area', value: 'Personalizada' }, { label: 'Dossie', value: 'Tecnico' }, { label: 'CRM', value: 'Rural' }],
    sections: premiumBaseSections,
    highlights: ['Finalidade da compra', 'Faixa de investimento', 'Estado desejado', 'Prazo para compra'],
    formTitle: 'Quero comprar fazenda',
    formSubmit: 'Enviar perfil rural'
  }),
  buildPremiumTemplate({
    id: 'premium-institucional-corretor',
    name: 'Pagina Institucional de Corretor',
    description: 'Pagina premium para corretor ou imobiliaria com autoridade, especialidades, prova social e captacao.',
    thumbnail: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=1920&auto=format&fit=crop',
    group: 'Institucional',
    category: 'Corretor e imobiliaria',
    objective: 'Falar com corretor',
    style: 'Institucional',
    resources: ['Prova social', 'WhatsApp', 'Formulario', 'CRM', 'SEO'],
    tags: ['corretor', 'imobiliaria', 'institucional'],
    pipeline: 'Pipeline Venda Urbana',
    crmTags: ['Lead Institucional'],
    conversionEvent: 'lead_institucional',
    theme: { primaryColor: '#111827', secondaryColor: '#4f46e5' },
    heroTitle: 'Atendimento imobiliario consultivo e orientado por dados',
    heroSubtitle: 'Apresente sua autoridade, especialidades, CRECI, portfolio e canais de contato em uma pagina profissional.',
    ctaText: 'Falar com corretor',
    location: 'Brasil',
    stats: [{ label: 'CRECI', value: 'Ativo' }, { label: 'Especialidades', value: 'Urbano/Rural' }, { label: 'CRM', value: 'Integrado' }, { label: 'SEO', value: 'Pronto' }],
    sections: premiumBaseSections,
    highlights: ['Foto do corretor', 'Redes sociais', 'Prova de autoridade', 'Formulario e WhatsApp'],
    formTitle: 'Quero falar com um especialista',
    formSubmit: 'Enviar contato'
  })
];

