import dns from 'node:dns/promises';
import fs from 'node:fs/promises';
import path from 'node:path';
import tls from 'node:tls';
import { domainToASCII } from 'node:url';
import { directAdminService } from './directAdminService.js';

const MAIN_DOMAIN = process.env.WHM_MAIN_DOMAIN || 'imobfluow.com.br';
const PLATFORM_PUBLIC_IP =
  process.env.PLATFORM_PUBLIC_IP ||
  process.env.SERVER_PUBLIC_IP ||
  process.env.APP_PUBLIC_IP ||
  process.env.VITE_PLATFORM_IP ||
  '207.58.153.219';
const PLATFORM_PUBLIC_IPS = PLATFORM_PUBLIC_IP.split(',')
  .map((ip) => ip.trim())
  .filter(Boolean);
const TRAEFIK_DYNAMIC_DIR =
  process.env.TRAEFIK_DYNAMIC_DIR || path.resolve(process.cwd(), 'traefik', 'dynamic');
const DNS_HELP_PATH = '/ajuda/dns';
const GENERATED_MARKER = '# Generated by Imobzy domainService. Do not edit manually.';
const DOMAIN_RE =
  /^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])$/;

export class DomainProvisioningError extends Error {
  constructor(code, message, statusCode = 400, details = {}) {
    super(message);
    this.name = 'DomainProvisioningError';
    this.code = code;
    this.statusCode = statusCode;
    this.details = details;
  }
}

function withTimeout(promise, timeoutMs, timeoutCode) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => {
      reject(new DomainProvisioningError(timeoutCode, 'Tempo limite excedido na verificacao do dominio.', 408));
    }, timeoutMs);
  });

  return Promise.race([promise, timeout]).finally(() => clearTimeout(timer));
}

export function normalizeDomain(domainName = '') {
  const raw = String(domainName)
    .trim()
    .toLowerCase()
    .replace(/^https?:\/\//, '')
    .replace(/:\d+$/, '')
    .replace(/\/.*$/, '');

  return domainToASCII(raw.replace(/\.$/, ''));
}

export function assertValidDomain(domainName) {
  const domain = normalizeDomain(domainName);

  if (
    !domain ||
    domain.includes('*') ||
    domain.includes('_') ||
    domain === 'localhost' ||
    domain.endsWith('.localhost') ||
    !DOMAIN_RE.test(domain)
  ) {
    throw new DomainProvisioningError(
      'INVALID_DOMAIN',
      'Dominio invalido. Informe um hostname publico, como www.cliente.com.br.',
      400
    );
  }

  return domain;
}

export function getPlatformDnsRecords(domainName) {
  const normalized = assertValidDomain(domainName);
  const name = normalized.startsWith('www.') ? 'www' : '@';
  const value = PLATFORM_PUBLIC_IPS[0] || PLATFORM_PUBLIC_IP;

  return {
    type: 'A',
    name,
    value,
    ttl: 3600,
    instructions: {
      pt: [
        'Acesse o painel DNS onde o dominio foi registrado.',
        'Crie ou edite um registro do tipo A.',
        `Use o nome ${name} e aponte para ${value}.`,
        'Se quiser usar www, crie outro registro A para www apontando para o mesmo IP ou um CNAME para o dominio principal.',
        'Nao altere registros MX, TXT, mail, smtp, pop ou webmail para nao afetar e-mails.',
        'Salve a alteracao e aguarde a propagacao do DNS.',
        'Depois clique em Verificar DNS no painel da ImobFluow.',
      ],
    },
  };
}

export function sanitizeTraefikName(domainName) {
  const domain = assertValidDomain(domainName);
  return domain.replace(/[^a-z0-9-]/g, '_');
}

export function getDomainConfigPath(domainName) {
  const fileName = `${sanitizeTraefikName(domainName)}.yml`;
  const baseDir = path.resolve(TRAEFIK_DYNAMIC_DIR);
  const targetPath = path.resolve(baseDir, fileName);

  if (!targetPath.startsWith(`${baseDir}${path.sep}`)) {
    throw new DomainProvisioningError(
      'INVALID_CONFIG_PATH',
      'Caminho de configuracao Traefik invalido.',
      400
    );
  }

  return targetPath;
}

async function resolveDomainAddresses(domain) {
  const lookupResults = await withTimeout(
    dns.lookup(domain, { all: true, family: 4 }),
    8000,
    'DNS_LOOKUP_TIMEOUT'
  );

  return [...new Set(lookupResults.map((result) => result.address))];
}

async function checkDnsRecord(domain) {
  try {
    const addresses = await resolveDomainAddresses(domain);
    const verified = addresses.some((address) => PLATFORM_PUBLIC_IPS.includes(address));

    return {
      verified,
      addresses,
      expectedIp: PLATFORM_PUBLIC_IPS[0] || PLATFORM_PUBLIC_IP,
      expectedIps: PLATFORM_PUBLIC_IPS,
    };
  } catch (error) {
    return {
      verified: false,
      addresses: [],
      expectedIp: PLATFORM_PUBLIC_IPS[0] || PLATFORM_PUBLIC_IP,
      expectedIps: PLATFORM_PUBLIC_IPS,
      error: error.code || error.message,
    };
  }
}

export function buildTraefikDomainConfig(domainName) {
  const domain = assertValidDomain(domainName);
  const routerBaseName = sanitizeTraefikName(domain);

  return `${GENERATED_MARKER}
# Domain: ${domain}

http:
  routers:
    ${routerBaseName}_api:
      rule: "Host(\`${domain}\`) && PathPrefix(\`/api\`)"
      entryPoints:
        - websecure
      priority: 1000
      tls:
        certResolver: letsencryptresolver
      service: imobfluow_api@docker

    ${routerBaseName}_frontend:
      rule: "Host(\`${domain}\`)"
      entryPoints:
        - websecure
      priority: 100
      tls:
        certResolver: letsencryptresolver
      service: imobfluow_frontend@docker
`;
}

async function ensureConfigCanBeWritten(configPath) {
  try {
    const existingConfig = await fs.readFile(configPath, 'utf8');
    if (!existingConfig.startsWith(GENERATED_MARKER)) {
      throw new DomainProvisioningError(
        'TRAEFIK_CONFIG_CONFLICT',
        'Ja existe uma configuracao Traefik nao gerenciada pelo Imobzy para este dominio.',
        409
      );
    }
  } catch (error) {
    if (error.code === 'ENOENT') return;
    throw error;
  }
}

async function writeTraefikDomainConfig(domain) {
  const configPath = getDomainConfigPath(domain);
  const dynamicDir = path.dirname(configPath);
  const tmpPath = `${configPath}.${process.pid}.${Date.now()}.tmp`;
  const config = buildTraefikDomainConfig(domain);

  await fs.mkdir(dynamicDir, { recursive: true });
  await ensureConfigCanBeWritten(configPath);
  await fs.writeFile(tmpPath, config, { encoding: 'utf8', flag: 'wx' });
  await fs.rename(tmpPath, configPath);

  return configPath;
}

export async function validateDockerDomainDns(domainName) {
  const domain = assertValidDomain(domainName);
  const dnsStatus = await checkDnsRecord(domain);

  if (!dnsStatus.verified) {
    throw new DomainProvisioningError(
      'DNS_NOT_POINTED',
      `DNS ainda nao aponta para ${dnsStatus.expectedIp}.`,
      422,
      dnsStatus
    );
  }

  return { domain, dnsStatus };
}

export async function addDockerDomain(domainName) {
  const { domain, dnsStatus } = await validateDockerDomainDns(domainName);
  const configPath = await writeTraefikDomainConfig(domain);

  return {
    success: true,
    domain,
    configPath,
    dnsRecords: getPlatformDnsRecords(domain),
    dnsStatus,
    routerNames: {
      api: `${sanitizeTraefikName(domain)}_api`,
      frontend: `${sanitizeTraefikName(domain)}_frontend`,
    },
    provisionedBy: 'docker',
  };
}

export async function removeDockerDomain(domainName) {
  const domain = assertValidDomain(domainName);
  const configPath = getDomainConfigPath(domain);

  try {
    const existingConfig = await fs.readFile(configPath, 'utf8');
    if (!existingConfig.startsWith(GENERATED_MARKER)) {
      throw new DomainProvisioningError(
        'TRAEFIK_CONFIG_CONFLICT',
        'A configuracao Traefik deste dominio nao foi gerada pelo Imobzy.',
        409
      );
    }
    await fs.unlink(configPath);
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }

  return {
    success: true,
    domain,
    configPath,
    provisionedBy: 'docker',
  };
}

function checkTlsCertificate(domain) {
  return new Promise((resolve) => {
    const socket = tls.connect(
      {
        host: domain,
        port: 443,
        servername: domain,
        rejectUnauthorized: false,
      },
      () => {
        const cert = socket.getPeerCertificate();
        const commonName = cert?.subject?.CN || '';
        const valid = socket.authorized === true;

        socket.end();
        resolve({
          valid,
          error: socket.authorizationError || null,
          commonName,
          issuer: cert?.issuer?.CN || '',
          validFrom: cert?.valid_from || null,
          validTo: cert?.valid_to || null,
        });
      }
    );

    socket.setTimeout(8000, () => {
      socket.destroy();
      resolve({
        valid: false,
        error: 'TLS_TIMEOUT',
        commonName: '',
        issuer: '',
        validFrom: null,
        validTo: null,
      });
    });

    socket.on('error', (error) => {
      resolve({
        valid: false,
        error: error.code || error.message,
        commonName: '',
        issuer: '',
        validFrom: null,
        validTo: null,
      });
    });
  });
}

export async function checkDockerDomainStatus(domainName) {
  const domain = assertValidDomain(domainName);
  const dnsRecords = getPlatformDnsRecords(domain);

  try {
    const dnsStatus = await checkDnsRecord(domain);
    const dnsVerified = dnsStatus.verified;
    const ssl = dnsVerified
      ? await checkTlsCertificate(domain)
      : {
          valid: false,
          error: 'DNS_NOT_VERIFIED',
          commonName: '',
          issuer: '',
          validFrom: null,
          validTo: null,
        };
    const verified = dnsVerified && ssl.valid;
    const configPath = getDomainConfigPath(domain);
    let provisioned = false;

    try {
      await fs.access(configPath);
      provisioned = true;
    } catch {
      provisioned = false;
    }

    return {
      success: true,
      configured: dnsVerified,
      verified,
      dnsVerified,
      sslVerified: ssl.valid,
      status: verified ? 'verified' : dnsVerified ? 'pending_ssl' : 'pending',
      provisioned,
      expectedIp: dnsStatus.expectedIp,
      expectedIps: dnsStatus.expectedIps,
      addresses: dnsStatus.addresses,
      ssl,
      dnsRecords,
      wikiUrl: DNS_HELP_PATH,
      message: verified
        ? 'DNS e certificado SSL ativos para este dominio.'
        : dnsVerified
          ? `DNS ja aponta para a ImobFluow, mas o SSL ainda nao esta valido (${ssl.error || 'aguardando certificado'}).`
        : `DNS ainda nao aponta para ${PLATFORM_PUBLIC_IP}.`,
    };
  } catch (error) {
    return {
      success: true,
      configured: false,
      verified: false,
      dnsVerified: false,
      sslVerified: false,
      status: 'pending',
      expectedIp: PLATFORM_PUBLIC_IP,
      expectedIps: PLATFORM_PUBLIC_IPS,
      addresses: [],
      provisioned: false,
      ssl: {
        valid: false,
        error: 'DNS_LOOKUP_FAILED',
        commonName: '',
        issuer: '',
        validFrom: null,
        validTo: null,
      },
      dnsRecords,
      wikiUrl: DNS_HELP_PATH,
      message: `Nao encontramos registro A para ${domain}.`,
      error: error.message,
    };
  }
}

export async function provisionTenantDomain(subdomain) {
  const normalizedSubdomain = normalizeDomain(subdomain).replace(/\..*$/, '');
  const fullDomain = `${normalizedSubdomain}.${MAIN_DOMAIN}`;
  const dnsProvisioning = await directAdminService.addTenantDNS(normalizedSubdomain);

  return {
    subdomain: normalizedSubdomain,
    fullDomain,
    dns: dnsProvisioning,
    success: true,
  };
}
