http:
  routers:
    imobzy_platform_api:
      rule: "Host(`app.imobfluow.com.br`, `imobfluow.com.br`, `www.imobfluow.com.br`, `okaimoveis.com.br`, `www.okaimoveis.com.br`, `fazendasbrasil.com`, `www.fazendasbrasil.com`, `fazendasbrasil.com.br`, `www.fazendasbrasil.com.br`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      priority: 1000
      tls:
        certResolver: letsencryptresolver
      service: imobzy_api@file

    imobzy_platform_frontend:
      rule: "Host(`app.imobfluow.com.br`, `imobfluow.com.br`, `www.imobfluow.com.br`, `okaimoveis.com.br`, `www.okaimoveis.com.br`, `fazendasbrasil.com`, `www.fazendasbrasil.com`, `fazendasbrasil.com.br`, `www.fazendasbrasil.com.br`)"
      entryPoints:
        - websecure
      priority: 100
      tls:
        certResolver: letsencryptresolver
      service: imobzy_frontend@file
