http:
  routers:
    imobzy_platform_api:
      rule: "Host(`imobfluow.com.br`, `www.imobfluow.com.br`, `imobzy.consultio.com.br`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      priority: 1000
      tls:
        certResolver: letsencryptresolver
      service: imobzy_api@file

    imobzy_platform_frontend:
      rule: "Host(`imobfluow.com.br`, `www.imobfluow.com.br`, `imobzy.consultio.com.br`)"
      entryPoints:
        - websecure
      priority: 100
      tls:
        certResolver: letsencryptresolver
      service: imobzy_frontend@file
