http:
  services:
    imobzy_frontend:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://imobfluow_frontend:80"

    imobzy_api:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://imobfluow_api:3002"
