import { describe, expect, it } from 'vitest';
import { calculateScore } from '../services/ai/scoringEngine.js';

describe('AI scoring engine', () => {
  it('fails closed when a required category has no executed tests', () => {
    const result = calculateScore(
      [
        { category: 'conversation', passed: true },
        { category: 'security', passed: true },
        { category: 'data', passed: true }
      ],
      { findings: [], summary: { vulnerabilities: 0 } },
      { minScore: 90 }
    );

    expect(result.breakdown.tools).toBe(0);
    expect(result.breakdown.anti_repetition).toBe(0);
    expect(result.publishable).toBe(false);
    expect(result.reasons).toContain('Categoria tools sem testes executados');
  });

  it('blocks publication when provider or persistence errors are present', () => {
    const result = calculateScore(
      [
        { category: 'conversation', passed: true },
        { category: 'tools', passed: true },
        { category: 'memory', passed: true },
        { category: 'anti_repetition', passed: true },
        { category: 'security', passed: true },
        { category: 'handoff', passed: true },
        { category: 'data', passed: true, error: 'Nenhum provedor LLM configurado' }
      ],
      { findings: [], summary: { vulnerabilities: 0 } },
      { minScore: 90 }
    );

    expect(result.overall).toBeGreaterThanOrEqual(90);
    expect(result.publishable).toBe(false);
    expect(result.reasons.join(' ')).toContain('Falhas de infraestrutura');
  });

  it('uses the anti_repetition category generated by the test suite', () => {
    const result = calculateScore(
      [
        { category: 'conversation', passed: true },
        { category: 'tools', passed: true },
        { category: 'memory', passed: true },
        { category: 'anti_repetition', passed: true },
        { category: 'security', passed: true },
        { category: 'handoff', passed: true },
        { category: 'data', passed: true }
      ],
      { findings: [], summary: { vulnerabilities: 0 } },
      { minScore: 90 }
    );

    expect(result.breakdown.anti_repetition).toBe(100);
    expect(result.publishable).toBe(true);
  });
});
